//go:build windows

package service

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"crewfold/internal/localipc"

	"golang.org/x/sys/windows"
)

func managePlatform(ctx context.Context, action string, config Config) (string, error) {
	switch action {
	case "install":
		if err := installLauncher(config); err != nil {
			return "", err
		}
		if _, online := daemonStatus(config.Endpoint); !online {
			if err := startDaemon(config); err != nil {
				return "", err
			}
		}
		return waitForEndpoint(ctx, config.Endpoint, true), nil
	case "uninstall":
		if _, err := managePlatform(ctx, "stop", config); err != nil {
			return "", err
		}
		if err := os.Remove(config.DefinitionPath); err != nil && !errors.Is(err, os.ErrNotExist) {
			return "", fmt.Errorf("remove Windows startup launcher: %w", err)
		}
		return "not-installed", nil
	case "start":
		if _, err := os.Stat(config.DefinitionPath); errors.Is(err, os.ErrNotExist) {
			return "", errors.New("Crewfold background startup is not installed; run `crewfold service install`")
		} else if err != nil {
			return "", fmt.Errorf("inspect Windows startup launcher: %w", err)
		}
		if _, online := daemonStatus(config.Endpoint); online {
			return "active", nil
		}
		if err := startDaemon(config); err != nil {
			return "", err
		}
		return waitForEndpoint(ctx, config.Endpoint, true), nil
	case "stop":
		pid, online := daemonStatus(config.Endpoint)
		if !online {
			if _, err := os.Stat(config.DefinitionPath); errors.Is(err, os.ErrNotExist) {
				return "not-installed", nil
			}
			return "inactive", nil
		}
		if err := requestDaemonShutdown(config.Endpoint); err != nil {
			process, findErr := os.FindProcess(pid)
			if findErr != nil {
				return "", fmt.Errorf("request daemon shutdown: %v; find process %d: %w", err, pid, findErr)
			}
			if killErr := process.Kill(); killErr != nil {
				return "", fmt.Errorf("request daemon shutdown: %v; stop process %d: %w", err, pid, killErr)
			}
		}
		return waitForEndpoint(ctx, config.Endpoint, false), nil
	case "status":
		if _, online := daemonStatus(config.Endpoint); online {
			return "active", nil
		}
		if _, err := os.Stat(config.DefinitionPath); errors.Is(err, os.ErrNotExist) {
			return "not-installed", nil
		} else if err != nil {
			return "", fmt.Errorf("inspect Windows startup launcher: %w", err)
		}
		return "inactive", nil
	default:
		panic("service action was not validated")
	}
}

func installLauncher(config Config) error {
	for _, directory := range []string{config.DataDir, filepath.Dir(config.DefinitionPath)} {
		if err := os.MkdirAll(directory, 0o700); err != nil {
			return err
		}
	}
	content, err := windowsStartupLauncher(config)
	if err != nil {
		return err
	}
	temporaryPath := config.DefinitionPath + ".tmp"
	if err := os.WriteFile(temporaryPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write temporary Windows startup launcher: %w", err)
	}
	if err := os.Rename(temporaryPath, config.DefinitionPath); err != nil {
		_ = os.Remove(temporaryPath)
		return fmt.Errorf("replace Windows startup launcher: %w", err)
	}
	return nil
}

func startDaemon(config Config) error {
	arguments := daemonArguments(config)
	command := exec.Command(config.Executable, arguments...)
	command.Dir = filepath.Dir(config.Executable)
	command.SysProcAttr = &syscall.SysProcAttr{
		CreationFlags: windows.CREATE_NEW_CONSOLE | windows.CREATE_NEW_PROCESS_GROUP,
	}
	if err := command.Start(); err != nil {
		return fmt.Errorf("start Crewfold daemon: %w", err)
	}
	if err := command.Process.Release(); err != nil {
		return fmt.Errorf("release Crewfold daemon process: %w", err)
	}
	return nil
}

func daemonArguments(config Config) []string {
	return []string{"daemon", "run", "--data-dir", config.DataDir, "--socket", config.Endpoint, "--web-address", "127.0.0.1:0"}
}

func windowsStartupLauncher(config Config) (string, error) {
	commandLine := append([]string{config.Executable}, daemonArguments(config)...)
	for index, argument := range commandLine {
		escaped, err := escapeWindowsBatchArgument(argument)
		if err != nil {
			return "", err
		}
		commandLine[index] = escaped
	}
	return "@echo off\r\n" +
		"setlocal DisableDelayedExpansion\r\n" +
		"rem Generated by Crewfold. Re-run `crewfold service install` after moving the executable.\r\n" +
		"title Crewfold service\r\n" + strings.Join(commandLine, " ") + "\r\n", nil
}

func escapeWindowsBatchArgument(argument string) (string, error) {
	if strings.ContainsAny(argument, "\r\n") {
		return "", errors.New("Windows service paths cannot contain newlines")
	}
	escaped := strings.ReplaceAll(syscall.EscapeArg(argument), "%", "%%")
	if strings.HasPrefix(escaped, `"`) {
		return escaped, nil
	}
	replacer := strings.NewReplacer("^", "^^", "&", "^&", "|", "^|", "<", "^<", ">", "^>", "(", "^(", ")", "^)")
	return replacer.Replace(escaped), nil
}

func daemonStatus(endpoint string) (int, bool) {
	ctx, cancel := context.WithTimeout(context.Background(), 250*time.Millisecond)
	defer cancel()
	connection, err := localipc.DialContext(ctx, endpoint)
	if err != nil {
		return 0, false
	}
	defer connection.Close()
	_ = connection.SetDeadline(time.Now().Add(250 * time.Millisecond))
	request := map[string]any{"id": "service-status", "method": "status", "params": map[string]any{}}
	if err := json.NewEncoder(connection).Encode(request); err != nil {
		return 0, false
	}
	var response struct {
		Result struct {
			PID int `json:"pid"`
		} `json:"result"`
		Error string `json:"error"`
	}
	if err := json.NewDecoder(bufio.NewReader(connection)).Decode(&response); err != nil || response.Error != "" || response.Result.PID <= 0 {
		return 0, false
	}
	return response.Result.PID, true
}

func requestDaemonShutdown(endpoint string) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	connection, err := localipc.DialContext(ctx, endpoint)
	if err != nil {
		return err
	}
	defer connection.Close()
	_ = connection.SetDeadline(time.Now().Add(time.Second))
	request := map[string]any{"id": "service-stop", "method": "daemon.shutdown", "params": map[string]any{}}
	if err := json.NewEncoder(connection).Encode(request); err != nil {
		return err
	}
	var response struct {
		Error string `json:"error"`
	}
	if err := json.NewDecoder(bufio.NewReader(connection)).Decode(&response); err != nil {
		return err
	}
	if response.Error != "" {
		return errors.New(response.Error)
	}
	return nil
}

func waitForEndpoint(ctx context.Context, endpoint string, wantOnline bool) string {
	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		_, online := daemonStatus(endpoint)
		if online == wantOnline {
			if wantOnline {
				return "active"
			}
			return "inactive"
		}
		select {
		case <-ctx.Done():
			if wantOnline {
				return "starting"
			}
			return "stopping"
		case <-time.After(50 * time.Millisecond):
		}
	}
	if wantOnline {
		return "starting"
	}
	return "stopping"
}
