// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package dbgen

import (
	"context"
)

const getRunLossResolution = `-- name: GetRunLossResolution :one
SELECT run_id,lost_revision,resolution,note,event_sequence,resolved_at,resolved_by
FROM run_loss_resolutions
WHERE run_id=?1
`

func (q *Queries) GetRunLossResolution(ctx context.Context, runID string) (RunLossResolution, error) {
	row := q.db.QueryRowContext(ctx, getRunLossResolution, runID)
	var i RunLossResolution
	err := row.Scan(
		&i.RunID,
		&i.LostRevision,
		&i.Resolution,
		&i.Note,
		&i.EventSequence,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const insertImmutableArtifact = `-- name: InsertImmutableArtifact :exec
INSERT INTO immutable_artifacts(content_sha256,byte_size,created_at,created_by)
VALUES(?1,?2,?3,?4)
ON CONFLICT(content_sha256) DO NOTHING
`

type InsertImmutableArtifactParams struct {
	ContentSha256 string `json:"content_sha256"`
	ByteSize      int64  `json:"byte_size"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
}

func (q *Queries) InsertImmutableArtifact(ctx context.Context, arg InsertImmutableArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertImmutableArtifact,
		arg.ContentSha256,
		arg.ByteSize,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertRunLogArtifact = `-- name: InsertRunLogArtifact :exec
INSERT INTO run_log_artifacts(
 id,run_id,kind,content_sha256,captured_bytes,omitted_bytes,truncated,created_at,created_by
) VALUES(
 ?1,?2,?3,?4,
 ?5,?6,?7,
 ?8,'subsystem:run-worker'
)
`

type InsertRunLogArtifactParams struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	Kind          string `json:"kind"`
	ContentSha256 string `json:"content_sha256"`
	CapturedBytes int64  `json:"captured_bytes"`
	OmittedBytes  int64  `json:"omitted_bytes"`
	Truncated     int64  `json:"truncated"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertRunLogArtifact(ctx context.Context, arg InsertRunLogArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertRunLogArtifact,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.ContentSha256,
		arg.CapturedBytes,
		arg.OmittedBytes,
		arg.Truncated,
		arg.CreatedAt,
	)
	return err
}

const insertRunLossResolution = `-- name: InsertRunLossResolution :exec
INSERT INTO run_loss_resolutions(
 run_id,lost_revision,resolution,note,event_sequence,resolved_at,resolved_by
) VALUES(
 ?1,?2,'owner_confirmed_effects_ended',
 ?3,?4,?5,'local-owner'
)
`

type InsertRunLossResolutionParams struct {
	RunID         string `json:"run_id"`
	LostRevision  int64  `json:"lost_revision"`
	Note          string `json:"note"`
	EventSequence int64  `json:"event_sequence"`
	ResolvedAt    string `json:"resolved_at"`
}

func (q *Queries) InsertRunLossResolution(ctx context.Context, arg InsertRunLossResolutionParams) error {
	_, err := q.db.ExecContext(ctx, insertRunLossResolution,
		arg.RunID,
		arg.LostRevision,
		arg.Note,
		arg.EventSequence,
		arg.ResolvedAt,
	)
	return err
}

const listReferencedImmutableArtifacts = `-- name: ListReferencedImmutableArtifacts :many
SELECT referenced.content_sha256,referenced.byte_size,referenced.kind
FROM (
  SELECT artifact.content_sha256 AS content_sha256,
         artifact.byte_size AS byte_size,
         'check_artifact' AS kind
  FROM immutable_artifacts artifact
  WHERE EXISTS(
    SELECT 1 FROM check_artifacts checked
    WHERE checked.content_sha256=artifact.content_sha256
  )
  UNION ALL
  SELECT artifact.content_sha256 AS content_sha256,
         artifact.byte_size AS byte_size,
         'run_log_artifact' AS kind
  FROM immutable_artifacts artifact
  WHERE EXISTS(
    SELECT 1 FROM run_log_artifacts run_log
    WHERE run_log.content_sha256=artifact.content_sha256
  )
) referenced
ORDER BY referenced.kind,referenced.content_sha256
`

type ListReferencedImmutableArtifactsRow struct {
	ContentSha256 string `json:"content_sha256"`
	ByteSize      int64  `json:"byte_size"`
	Kind          string `json:"kind"`
}

func (q *Queries) ListReferencedImmutableArtifacts(ctx context.Context) ([]ListReferencedImmutableArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReferencedImmutableArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReferencedImmutableArtifactsRow{}
	for rows.Next() {
		var i ListReferencedImmutableArtifactsRow
		if err := rows.Scan(&i.ContentSha256, &i.ByteSize, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogArtifacts = `-- name: ListRunLogArtifacts :many
SELECT id,run_id,kind,content_sha256,captured_bytes,omitted_bytes,truncated,created_at,created_by
FROM run_log_artifacts
WHERE run_id=?1
ORDER BY kind
`

func (q *Queries) ListRunLogArtifacts(ctx context.Context, runID string) ([]RunLogArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunLogArtifact{}
	for rows.Next() {
		var i RunLogArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.ContentSha256,
			&i.CapturedBytes,
			&i.OmittedBytes,
			&i.Truncated,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
