// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks_execution.sql

package dbgen

import (
	"context"
)

const checkLaunchReceiptAuthorityMatches = `-- name: CheckLaunchReceiptAuthorityMatches :one
SELECT CAST(EXISTS(
 SELECT 1
 FROM check_runs run JOIN check_jobs job ON job.check_run_id=run.id
 WHERE run.id=?1 AND run.status='requested'
  AND job.id=?2 AND job.status='leased'
  AND run.definition_sha256=?3
  AND run.repository_id=?4
  AND run.repository_object_format=?5
  AND run.checkout_id=?6
  AND run.source_type=?7
  AND run.source_actor_id=?8
  AND run.source_agent_id IS ?9
  AND run.source_agent_revision IS ?10
  AND run.source_run_id IS ?11
  AND run.source_grant_id IS ?12
  AND run.source_grant_revision IS ?13
) AS INTEGER) AS authority_matches
`

type CheckLaunchReceiptAuthorityMatchesParams struct {
	CheckRunID             string  `json:"check_run_id"`
	CheckJobID             string  `json:"check_job_id"`
	DefinitionSha256       string  `json:"definition_sha256"`
	RepositoryID           string  `json:"repository_id"`
	RepositoryObjectFormat string  `json:"repository_object_format"`
	CheckoutID             string  `json:"checkout_id"`
	SourceType             string  `json:"source_type"`
	SourceActorID          string  `json:"source_actor_id"`
	SourceAgentID          *string `json:"source_agent_id"`
	SourceAgentRevision    *int64  `json:"source_agent_revision"`
	SourceRunID            *string `json:"source_run_id"`
	SourceGrantID          *string `json:"source_grant_id"`
	SourceGrantRevision    *int64  `json:"source_grant_revision"`
}

func (q *Queries) CheckLaunchReceiptAuthorityMatches(ctx context.Context, arg CheckLaunchReceiptAuthorityMatchesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkLaunchReceiptAuthorityMatches,
		arg.CheckRunID,
		arg.CheckJobID,
		arg.DefinitionSha256,
		arg.RepositoryID,
		arg.RepositoryObjectFormat,
		arg.CheckoutID,
		arg.SourceType,
		arg.SourceActorID,
		arg.SourceAgentID,
		arg.SourceAgentRevision,
		arg.SourceRunID,
		arg.SourceGrantID,
		arg.SourceGrantRevision,
	)
	var authority_matches int64
	err := row.Scan(&authority_matches)
	return authority_matches, err
}

const countGrantActiveChecks = `-- name: CountGrantActiveChecks :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM check_runs
WHERE source_grant_id=?1 AND status IN ('starting','running')
`

func (q *Queries) CountGrantActiveChecks(ctx context.Context, grantID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGrantActiveChecks, grantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countGrantedCheckCapacity = `-- name: CountGrantedCheckCapacity :one
SELECT
 CAST(COUNT(*) AS INTEGER) AS unresolved_count,
 CAST(COALESCE(SUM(CASE WHEN status IN ('starting','running') THEN 1 ELSE 0 END),0) AS INTEGER) AS in_flight
FROM check_runs
WHERE source_type='agent_run' AND source_grant_id=?1
 AND status IN ('requested','starting','running')
`

type CountGrantedCheckCapacityRow struct {
	UnresolvedCount int64 `json:"unresolved_count"`
	InFlight        int64 `json:"in_flight"`
}

func (q *Queries) CountGrantedCheckCapacity(ctx context.Context, grantID *string) (CountGrantedCheckCapacityRow, error) {
	row := q.db.QueryRowContext(ctx, countGrantedCheckCapacity, grantID)
	var i CountGrantedCheckCapacityRow
	err := row.Scan(&i.UnresolvedCount, &i.InFlight)
	return i, err
}

const getCheckGrantMaxInFlight = `-- name: GetCheckGrantMaxInFlight :one
SELECT max_in_flight
FROM check_watch_grants
WHERE id=?1 AND revision=?2
`

type GetCheckGrantMaxInFlightParams struct {
	GrantID       string `json:"grant_id"`
	GrantRevision int64  `json:"grant_revision"`
}

func (q *Queries) GetCheckGrantMaxInFlight(ctx context.Context, arg GetCheckGrantMaxInFlightParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCheckGrantMaxInFlight, arg.GrantID, arg.GrantRevision)
	var max_in_flight int64
	err := row.Scan(&max_in_flight)
	return max_in_flight, err
}

const getCheckJobStatus = `-- name: GetCheckJobStatus :one
SELECT status FROM check_jobs WHERE check_run_id=?1
`

func (q *Queries) GetCheckJobStatus(ctx context.Context, checkRunID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCheckJobStatus, checkRunID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getCheckLaunchReceiptLaunchable = `-- name: GetCheckLaunchReceiptLaunchable :one
SELECT launchable FROM check_launch_receipts WHERE check_run_id=?1
`

func (q *Queries) GetCheckLaunchReceiptLaunchable(ctx context.Context, checkRunID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCheckLaunchReceiptLaunchable, checkRunID)
	var launchable int64
	err := row.Scan(&launchable)
	return launchable, err
}

const getCheckRepository = `-- name: GetCheckRepository :one
SELECT id, workspace_id, fingerprint, object_format, root_commits_json, revision, created_at, updated_at, created_by, updated_by FROM repositories WHERE id=?1
`

func (q *Queries) GetCheckRepository(ctx context.Context, repositoryID string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getCheckRepository, repositoryID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Fingerprint,
		&i.ObjectFormat,
		&i.RootCommitsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getCheckResultByRun = `-- name: GetCheckResultByRun :one
SELECT id, check_run_id, requirement_id, requirement_revision, definition_id, definition_content_revision, outcome, exit_code, forced, diagnostic_code, diagnostic, observation_available, repository_id, object_format, checkout_id, branch, head_commit, dirty, dirty_paths_json, observed_at, observation_diagnostic_code, observation_diagnostic, created_at, created_by FROM check_results WHERE check_run_id=?1
`

func (q *Queries) GetCheckResultByRun(ctx context.Context, checkRunID string) (CheckResult, error) {
	row := q.db.QueryRowContext(ctx, getCheckResultByRun, checkRunID)
	var i CheckResult
	err := row.Scan(
		&i.ID,
		&i.CheckRunID,
		&i.RequirementID,
		&i.RequirementRevision,
		&i.DefinitionID,
		&i.DefinitionContentRevision,
		&i.Outcome,
		&i.ExitCode,
		&i.Forced,
		&i.DiagnosticCode,
		&i.Diagnostic,
		&i.ObservationAvailable,
		&i.RepositoryID,
		&i.ObjectFormat,
		&i.CheckoutID,
		&i.Branch,
		&i.HeadCommit,
		&i.Dirty,
		&i.DirtyPathsJson,
		&i.ObservedAt,
		&i.ObservationDiagnosticCode,
		&i.ObservationDiagnostic,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getFrozenCheckCheckoutState = `-- name: GetFrozenCheckCheckoutState :one
SELECT project_id,repository_id,path,write_mode,availability,revision
FROM checkouts
WHERE id=?1
`

type GetFrozenCheckCheckoutStateRow struct {
	ProjectID    string `json:"project_id"`
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
	WriteMode    string `json:"write_mode"`
	Availability string `json:"availability"`
	Revision     int64  `json:"revision"`
}

func (q *Queries) GetFrozenCheckCheckoutState(ctx context.Context, checkoutID string) (GetFrozenCheckCheckoutStateRow, error) {
	row := q.db.QueryRowContext(ctx, getFrozenCheckCheckoutState, checkoutID)
	var i GetFrozenCheckCheckoutStateRow
	err := row.Scan(
		&i.ProjectID,
		&i.RepositoryID,
		&i.Path,
		&i.WriteMode,
		&i.Availability,
		&i.Revision,
	)
	return i, err
}

const getFrozenCheckRepository = `-- name: GetFrozenCheckRepository :one
SELECT id, workspace_id, fingerprint, object_format, root_commits_json, revision, created_at, updated_at, created_by, updated_by
FROM repositories
WHERE id=?1 AND object_format=?2
`

type GetFrozenCheckRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	ObjectFormat string `json:"object_format"`
}

func (q *Queries) GetFrozenCheckRepository(ctx context.Context, arg GetFrozenCheckRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getFrozenCheckRepository, arg.RepositoryID, arg.ObjectFormat)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Fingerprint,
		&i.ObjectFormat,
		&i.RootCommitsJson,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getLatestCheckFreshnessByResult = `-- name: GetLatestCheckFreshnessByResult :one
SELECT id, check_result_id, revision, status, reason, initially_eligible, ever_stale, observation_available, repository_id, object_format, checkout_id, branch, head_commit, dirty, dirty_paths_json, observed_at, diagnostic_code, diagnostic, created_at, created_by
FROM check_result_freshness
WHERE check_result_id=?1
ORDER BY revision DESC
LIMIT 1
`

func (q *Queries) GetLatestCheckFreshnessByResult(ctx context.Context, checkResultID string) (CheckResultFreshness, error) {
	row := q.db.QueryRowContext(ctx, getLatestCheckFreshnessByResult, checkResultID)
	var i CheckResultFreshness
	err := row.Scan(
		&i.ID,
		&i.CheckResultID,
		&i.Revision,
		&i.Status,
		&i.Reason,
		&i.InitiallyEligible,
		&i.EverStale,
		&i.ObservationAvailable,
		&i.RepositoryID,
		&i.ObjectFormat,
		&i.CheckoutID,
		&i.Branch,
		&i.HeadCommit,
		&i.Dirty,
		&i.DirtyPathsJson,
		&i.ObservedAt,
		&i.DiagnosticCode,
		&i.Diagnostic,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLatestCheckRunForRequirement = `-- name: GetLatestCheckRunForRequirement :one
SELECT id,status
FROM check_runs
WHERE requirement_id=?1 AND requirement_revision=?2
ORDER BY created_at DESC,id DESC
LIMIT 1
`

type GetLatestCheckRunForRequirementParams struct {
	RequirementID       string `json:"requirement_id"`
	RequirementRevision int64  `json:"requirement_revision"`
}

type GetLatestCheckRunForRequirementRow struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) GetLatestCheckRunForRequirement(ctx context.Context, arg GetLatestCheckRunForRequirementParams) (GetLatestCheckRunForRequirementRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestCheckRunForRequirement, arg.RequirementID, arg.RequirementRevision)
	var i GetLatestCheckRunForRequirementRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getLatestTaskRunCheckoutID = `-- name: GetLatestTaskRunCheckoutID :one
SELECT checkout_id
FROM runs
WHERE task_id=?1 AND project_id=?2
ORDER BY CASE WHEN status IN ('requested','starting','active','blocked','stopping','lost') THEN 0 ELSE 1 END,
 created_at DESC,id DESC
LIMIT 1
`

type GetLatestTaskRunCheckoutIDParams struct {
	TaskID    string `json:"task_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetLatestTaskRunCheckoutID(ctx context.Context, arg GetLatestTaskRunCheckoutIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestTaskRunCheckoutID, arg.TaskID, arg.ProjectID)
	var checkout_id string
	err := row.Scan(&checkout_id)
	return checkout_id, err
}

const getNextPendingCheckRunID = `-- name: GetNextPendingCheckRunID :one
SELECT job.check_run_id
FROM check_jobs job JOIN check_runs run ON run.id=job.check_run_id
WHERE job.status='pending' AND crewfold_timestamp_key(job.available_at)<=crewfold_timestamp_key(?1)
 AND (run.source_type='owner' OR run.status<>'requested' OR
   (SELECT COUNT(*) FROM check_runs active
    WHERE active.source_grant_id=run.source_grant_id AND active.status IN ('starting','running')) < run.source_max_in_flight)
ORDER BY crewfold_timestamp_key(job.available_at),job.check_run_id
LIMIT 1
`

func (q *Queries) GetNextPendingCheckRunID(ctx context.Context, now interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingCheckRunID, now)
	var check_run_id string
	err := row.Scan(&check_run_id)
	return check_run_id, err
}

const insertCheckLaunchReceipt = `-- name: InsertCheckLaunchReceipt :exec
INSERT INTO check_launch_receipts(
 id,check_run_id,check_job_id,operation_id,effective_spec_sha256,effective_working_directory,
 launchable,preflight_failure_code,preflight_failure_diagnostic,definition_sha256,
 source_type,source_actor_id,source_agent_id,source_agent_revision,source_run_id,source_grant_id,source_grant_revision,
 observation_available,repository_id,object_format,checkout_id,branch,head_commit,dirty,dirty_paths_json,
 observed_at,diagnostic_code,diagnostic,created_at,created_by
) VALUES(
 ?1,?2,?3,?4,?5,?6,
 ?7,NULLIF(?8,''),NULLIF(?9,''),?10,
 ?11,?12,NULLIF(?13,''),NULLIF(?14,0),NULLIF(?15,''),NULLIF(?16,''),NULLIF(?17,0),
 ?18,?19,?20,?21,NULLIF(?22,''),NULLIF(?23,''),?24,?25,
 ?26,NULLIF(?27,''),NULLIF(?28,''),?29,'crewfold-check-worker'
)
`

type InsertCheckLaunchReceiptParams struct {
	ID                         string      `json:"id"`
	CheckRunID                 string      `json:"check_run_id"`
	CheckJobID                 string      `json:"check_job_id"`
	OperationID                string      `json:"operation_id"`
	EffectiveSpecSha256        string      `json:"effective_spec_sha256"`
	EffectiveWorkingDirectory  string      `json:"effective_working_directory"`
	Launchable                 int64       `json:"launchable"`
	PreflightFailureCode       interface{} `json:"preflight_failure_code"`
	PreflightFailureDiagnostic interface{} `json:"preflight_failure_diagnostic"`
	DefinitionSha256           string      `json:"definition_sha256"`
	SourceType                 string      `json:"source_type"`
	SourceActorID              string      `json:"source_actor_id"`
	SourceAgentID              interface{} `json:"source_agent_id"`
	SourceAgentRevision        interface{} `json:"source_agent_revision"`
	SourceRunID                interface{} `json:"source_run_id"`
	SourceGrantID              interface{} `json:"source_grant_id"`
	SourceGrantRevision        interface{} `json:"source_grant_revision"`
	ObservationAvailable       int64       `json:"observation_available"`
	RepositoryID               string      `json:"repository_id"`
	ObjectFormat               string      `json:"object_format"`
	CheckoutID                 string      `json:"checkout_id"`
	Branch                     interface{} `json:"branch"`
	HeadCommit                 interface{} `json:"head_commit"`
	Dirty                      int64       `json:"dirty"`
	DirtyPathsJson             string      `json:"dirty_paths_json"`
	ObservedAt                 string      `json:"observed_at"`
	DiagnosticCode             interface{} `json:"diagnostic_code"`
	Diagnostic                 interface{} `json:"diagnostic"`
	CreatedAt                  string      `json:"created_at"`
}

func (q *Queries) InsertCheckLaunchReceipt(ctx context.Context, arg InsertCheckLaunchReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckLaunchReceipt,
		arg.ID,
		arg.CheckRunID,
		arg.CheckJobID,
		arg.OperationID,
		arg.EffectiveSpecSha256,
		arg.EffectiveWorkingDirectory,
		arg.Launchable,
		arg.PreflightFailureCode,
		arg.PreflightFailureDiagnostic,
		arg.DefinitionSha256,
		arg.SourceType,
		arg.SourceActorID,
		arg.SourceAgentID,
		arg.SourceAgentRevision,
		arg.SourceRunID,
		arg.SourceGrantID,
		arg.SourceGrantRevision,
		arg.ObservationAvailable,
		arg.RepositoryID,
		arg.ObjectFormat,
		arg.CheckoutID,
		arg.Branch,
		arg.HeadCommit,
		arg.Dirty,
		arg.DirtyPathsJson,
		arg.ObservedAt,
		arg.DiagnosticCode,
		arg.Diagnostic,
		arg.CreatedAt,
	)
	return err
}

const insertCheckRuntimeBinding = `-- name: InsertCheckRuntimeBinding :execrows
INSERT INTO check_runtime_bindings(
 check_run_id,node_id,node_fingerprint,operation_id,runtime_handle,revision,created_at,updated_at
) SELECT ?1,?2,?3,?4,?5,1,?6,?6
WHERE EXISTS(SELECT 1 FROM check_runs run WHERE run.id=?1 AND run.status='starting')
`

type InsertCheckRuntimeBindingParams struct {
	CheckRunID      string `json:"check_run_id"`
	NodeID          string `json:"node_id"`
	NodeFingerprint string `json:"node_fingerprint"`
	OperationID     string `json:"operation_id"`
	RuntimeHandle   string `json:"runtime_handle"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) InsertCheckRuntimeBinding(ctx context.Context, arg InsertCheckRuntimeBindingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCheckRuntimeBinding,
		arg.CheckRunID,
		arg.NodeID,
		arg.NodeFingerprint,
		arg.OperationID,
		arg.RuntimeHandle,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const leaseCheckJob = `-- name: LeaseCheckJob :execrows
UPDATE check_jobs
SET status='leased',lease_expires_at=?1,attempts=attempts+1,updated_at=?2
WHERE check_run_id=?3 AND status='pending'
`

type LeaseCheckJobParams struct {
	LeaseExpiresAt *string `json:"lease_expires_at"`
	UpdatedAt      string  `json:"updated_at"`
	CheckRunID     string  `json:"check_run_id"`
}

func (q *Queries) LeaseCheckJob(ctx context.Context, arg LeaseCheckJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leaseCheckJob, arg.LeaseExpiresAt, arg.UpdatedAt, arg.CheckRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCheckArtifactsForResult = `-- name: ListCheckArtifactsForResult :many
SELECT id, check_result_id, kind, content_sha256, captured_bytes, omitted_bytes, truncated, created_at
FROM check_artifacts
WHERE check_result_id=?1
ORDER BY kind
`

func (q *Queries) ListCheckArtifactsForResult(ctx context.Context, checkResultID string) ([]CheckArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listCheckArtifactsForResult, checkResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckArtifact{}
	for rows.Next() {
		var i CheckArtifact
		if err := rows.Scan(
			&i.ID,
			&i.CheckResultID,
			&i.Kind,
			&i.ContentSha256,
			&i.CapturedBytes,
			&i.OmittedBytes,
			&i.Truncated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckEvidenceForRequirement = `-- name: ListCheckEvidenceForRequirement :many
SELECT id, requirement_id, requirement_revision, check_result_id, freshness_revision, class, effect, created_at, created_by
FROM check_requirement_evidence
WHERE requirement_id=?1 AND requirement_revision=?2
ORDER BY created_at,id
`

type ListCheckEvidenceForRequirementParams struct {
	RequirementID       string `json:"requirement_id"`
	RequirementRevision int64  `json:"requirement_revision"`
}

func (q *Queries) ListCheckEvidenceForRequirement(ctx context.Context, arg ListCheckEvidenceForRequirementParams) ([]CheckRequirementEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listCheckEvidenceForRequirement, arg.RequirementID, arg.RequirementRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckRequirementEvidence{}
	for rows.Next() {
		var i CheckRequirementEvidence
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.RequirementRevision,
			&i.CheckResultID,
			&i.FreshnessRevision,
			&i.Class,
			&i.Effect,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckFreshnessHistory = `-- name: ListCheckFreshnessHistory :many
SELECT id, check_result_id, revision, status, reason, initially_eligible, ever_stale, observation_available, repository_id, object_format, checkout_id, branch, head_commit, dirty, dirty_paths_json, observed_at, diagnostic_code, diagnostic, created_at, created_by
FROM check_result_freshness
WHERE check_result_id=?1
ORDER BY revision
`

func (q *Queries) ListCheckFreshnessHistory(ctx context.Context, checkResultID string) ([]CheckResultFreshness, error) {
	rows, err := q.db.QueryContext(ctx, listCheckFreshnessHistory, checkResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckResultFreshness{}
	for rows.Next() {
		var i CheckResultFreshness
		if err := rows.Scan(
			&i.ID,
			&i.CheckResultID,
			&i.Revision,
			&i.Status,
			&i.Reason,
			&i.InitiallyEligible,
			&i.EverStale,
			&i.ObservationAvailable,
			&i.RepositoryID,
			&i.ObjectFormat,
			&i.CheckoutID,
			&i.Branch,
			&i.HeadCommit,
			&i.Dirty,
			&i.DirtyPathsJson,
			&i.ObservedAt,
			&i.DiagnosticCode,
			&i.Diagnostic,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedCheckRunIDs = `-- name: ListGrantedCheckRunIDs :many
SELECT run.id
FROM check_runs run
JOIN check_watch_grant_definitions allowed ON allowed.definition_id=run.definition_id
 AND allowed.definition_content_revision=run.definition_content_revision
 AND allowed.definition_sha256=run.definition_sha256
WHERE allowed.grant_id=?1 AND run.project_id=?2
 AND run.status='finished'
 AND (CAST(?3 AS TEXT)='' OR run.id<?3)
ORDER BY run.id DESC
LIMIT ?4
`

type ListGrantedCheckRunIDsParams struct {
	GrantID     string `json:"grant_id"`
	ProjectID   string `json:"project_id"`
	AfterRunID  string `json:"after_run_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListGrantedCheckRunIDs(ctx context.Context, arg ListGrantedCheckRunIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGrantedCheckRunIDs,
		arg.GrantID,
		arg.ProjectID,
		arg.AfterRunID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckRunRunning = `-- name: MarkCheckRunRunning :execrows
UPDATE check_runs
SET status='running',revision=revision+1,started_at=?1,updated_at=?1,updated_by='crewfold-check-worker'
WHERE id=?2 AND status='starting'
 AND EXISTS(SELECT 1 FROM check_runtime_bindings binding WHERE binding.check_run_id=check_runs.id)
`

type MarkCheckRunRunningParams struct {
	StartedAt  *string `json:"started_at"`
	CheckRunID string  `json:"check_run_id"`
}

func (q *Queries) MarkCheckRunRunning(ctx context.Context, arg MarkCheckRunRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCheckRunRunning, arg.StartedAt, arg.CheckRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markCheckRunStarting = `-- name: MarkCheckRunStarting :execrows
UPDATE check_runs
SET status='starting',revision=revision+1,updated_at=?1,updated_by='crewfold-check-worker'
WHERE id=?2 AND status='requested'
`

type MarkCheckRunStartingParams struct {
	UpdatedAt  string `json:"updated_at"`
	CheckRunID string `json:"check_run_id"`
}

func (q *Queries) MarkCheckRunStarting(ctx context.Context, arg MarkCheckRunStartingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCheckRunStarting, arg.UpdatedAt, arg.CheckRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markCheckRuntimeObserved = `-- name: MarkCheckRuntimeObserved :execrows
UPDATE check_runs
SET revision=revision+1,updated_at=?1,updated_by='crewfold-check-worker'
WHERE id=?2 AND status='starting'
 AND EXISTS(SELECT 1 FROM check_runtime_bindings binding WHERE binding.check_run_id=check_runs.id)
`

type MarkCheckRuntimeObservedParams struct {
	UpdatedAt  string `json:"updated_at"`
	CheckRunID string `json:"check_run_id"`
}

func (q *Queries) MarkCheckRuntimeObserved(ctx context.Context, arg MarkCheckRuntimeObservedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCheckRuntimeObserved, arg.UpdatedAt, arg.CheckRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoverAllCheckJobLeases = `-- name: RecoverAllCheckJobLeases :exec
UPDATE check_jobs
SET status='pending',lease_expires_at=NULL,available_at=?1,updated_at=?1
WHERE status='leased'
`

func (q *Queries) RecoverAllCheckJobLeases(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, recoverAllCheckJobLeases, now)
	return err
}

const releaseCheckJobLease = `-- name: ReleaseCheckJobLease :execrows
UPDATE check_jobs
SET status='pending',lease_expires_at=NULL,available_at=?1,updated_at=?2
WHERE check_run_id=?3 AND status='leased'
`

type ReleaseCheckJobLeaseParams struct {
	AvailableAt string `json:"available_at"`
	UpdatedAt   string `json:"updated_at"`
	CheckRunID  string `json:"check_run_id"`
}

func (q *Queries) ReleaseCheckJobLease(ctx context.Context, arg ReleaseCheckJobLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseCheckJobLease, arg.AvailableAt, arg.UpdatedAt, arg.CheckRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetExpiredCheckJobLeases = `-- name: ResetExpiredCheckJobLeases :exec
UPDATE check_jobs
SET status='pending',lease_expires_at=NULL,updated_at=?1
WHERE status='leased'
 AND crewfold_timestamp_key(lease_expires_at)<=crewfold_timestamp_key(?1)
`

func (q *Queries) ResetExpiredCheckJobLeases(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, resetExpiredCheckJobLeases, now)
	return err
}
