// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaborations.sql

package dbgen

import (
	"context"
)

const findThreadParticipantByBinding = `-- name: FindThreadParticipantByBinding :one
SELECT id, thread_id, workspace_id, agent_id, agent_name, task_id, task_title,
       project_id, project_name, assignment_id, assignment_revision,
       agent_revision, task_revision, ordinal, status, invited_at, invited_by
FROM thread_participants
WHERE thread_id = ?1
  AND agent_id = ?2
  AND task_id = ?3
`

type FindThreadParticipantByBindingParams struct {
	ThreadID string `json:"thread_id"`
	AgentID  string `json:"agent_id"`
	TaskID   string `json:"task_id"`
}

func (q *Queries) FindThreadParticipantByBinding(ctx context.Context, arg FindThreadParticipantByBindingParams) (ThreadParticipant, error) {
	row := q.db.QueryRowContext(ctx, findThreadParticipantByBinding, arg.ThreadID, arg.AgentID, arg.TaskID)
	var i ThreadParticipant
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.WorkspaceID,
		&i.AgentID,
		&i.AgentName,
		&i.TaskID,
		&i.TaskTitle,
		&i.ProjectID,
		&i.ProjectName,
		&i.AssignmentID,
		&i.AssignmentRevision,
		&i.AgentRevision,
		&i.TaskRevision,
		&i.Ordinal,
		&i.Status,
		&i.InvitedAt,
		&i.InvitedBy,
	)
	return i, err
}

const getEligibleParticipantAssignment = `-- name: GetEligibleParticipantAssignment :one
SELECT ta.id AS assignment_id, ta.revision AS assignment_revision, ta.lease_expires_at
FROM task_assignments ta
WHERE ta.task_id = ?1
  AND ta.agent_id = ?2
  AND ta.status = 'active'
  AND crewfold_timestamp_key(ta.lease_expires_at) > crewfold_timestamp_key(CAST(?3 AS TEXT))
LIMIT 1
`

type GetEligibleParticipantAssignmentParams struct {
	TaskID     string `json:"task_id"`
	AgentID    string `json:"agent_id"`
	ObservedAt string `json:"observed_at"`
}

type GetEligibleParticipantAssignmentRow struct {
	AssignmentID       string `json:"assignment_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
	LeaseExpiresAt     string `json:"lease_expires_at"`
}

func (q *Queries) GetEligibleParticipantAssignment(ctx context.Context, arg GetEligibleParticipantAssignmentParams) (GetEligibleParticipantAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getEligibleParticipantAssignment, arg.TaskID, arg.AgentID, arg.ObservedAt)
	var i GetEligibleParticipantAssignmentRow
	err := row.Scan(&i.AssignmentID, &i.AssignmentRevision, &i.LeaseExpiresAt)
	return i, err
}

const getParticipantThreadState = `-- name: GetParticipantThreadState :one
SELECT id, workspace_id, COALESCE(project_id, '') AS project_id,
       COALESCE(task_id, '') AS task_id, subject, status, revision,
       created_at, updated_at, created_by, updated_by, kind, participant_revision,
       initial_participant_count
FROM message_threads
WHERE id = ?1 AND workspace_id = ?2
  AND kind = 'participant_bound'
`

type GetParticipantThreadStateParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetParticipantThreadStateRow struct {
	ID                      string `json:"id"`
	WorkspaceID             string `json:"workspace_id"`
	ProjectID               string `json:"project_id"`
	TaskID                  string `json:"task_id"`
	Subject                 string `json:"subject"`
	Status                  string `json:"status"`
	Revision                int64  `json:"revision"`
	CreatedAt               string `json:"created_at"`
	UpdatedAt               string `json:"updated_at"`
	CreatedBy               string `json:"created_by"`
	UpdatedBy               string `json:"updated_by"`
	Kind                    string `json:"kind"`
	ParticipantRevision     int64  `json:"participant_revision"`
	InitialParticipantCount int64  `json:"initial_participant_count"`
}

func (q *Queries) GetParticipantThreadState(ctx context.Context, arg GetParticipantThreadStateParams) (GetParticipantThreadStateRow, error) {
	row := q.db.QueryRowContext(ctx, getParticipantThreadState, arg.ID, arg.WorkspaceID)
	var i GetParticipantThreadStateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.Subject,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Kind,
		&i.ParticipantRevision,
		&i.InitialParticipantCount,
	)
	return i, err
}

const insertParticipantThread = `-- name: InsertParticipantThread :exec
INSERT INTO message_threads(
    id, workspace_id, project_id, task_id, subject, status, revision,
    created_at, updated_at, created_by, updated_by, kind, participant_revision,
    initial_participant_count
) VALUES (
    ?1, ?2, NULL, NULL, ?3, 'open', 1,
    ?4, ?4, ?5, ?5,
    'participant_bound', 1, ?6
)
`

type InsertParticipantThreadParams struct {
	ID                      string `json:"id"`
	WorkspaceID             string `json:"workspace_id"`
	Subject                 string `json:"subject"`
	CreatedAt               string `json:"created_at"`
	CreatedBy               string `json:"created_by"`
	InitialParticipantCount int64  `json:"initial_participant_count"`
}

func (q *Queries) InsertParticipantThread(ctx context.Context, arg InsertParticipantThreadParams) error {
	_, err := q.db.ExecContext(ctx, insertParticipantThread,
		arg.ID,
		arg.WorkspaceID,
		arg.Subject,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.InitialParticipantCount,
	)
	return err
}

const insertThreadParticipant = `-- name: InsertThreadParticipant :exec
INSERT INTO thread_participants(
    id, thread_id, workspace_id, agent_id, agent_name, task_id, task_title,
    project_id, project_name, assignment_id, assignment_revision,
    agent_revision, task_revision, ordinal, status, invited_at, invited_by
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10, ?11,
    ?12, ?13, ?14,
    'active', ?15, ?16
)
`

type InsertThreadParticipantParams struct {
	ID                 string `json:"id"`
	ThreadID           string `json:"thread_id"`
	WorkspaceID        string `json:"workspace_id"`
	AgentID            string `json:"agent_id"`
	AgentName          string `json:"agent_name"`
	TaskID             string `json:"task_id"`
	TaskTitle          string `json:"task_title"`
	ProjectID          string `json:"project_id"`
	ProjectName        string `json:"project_name"`
	AssignmentID       string `json:"assignment_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
	AgentRevision      int64  `json:"agent_revision"`
	TaskRevision       int64  `json:"task_revision"`
	Ordinal            int64  `json:"ordinal"`
	InvitedAt          string `json:"invited_at"`
	InvitedBy          string `json:"invited_by"`
}

func (q *Queries) InsertThreadParticipant(ctx context.Context, arg InsertThreadParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertThreadParticipant,
		arg.ID,
		arg.ThreadID,
		arg.WorkspaceID,
		arg.AgentID,
		arg.AgentName,
		arg.TaskID,
		arg.TaskTitle,
		arg.ProjectID,
		arg.ProjectName,
		arg.AssignmentID,
		arg.AssignmentRevision,
		arg.AgentRevision,
		arg.TaskRevision,
		arg.Ordinal,
		arg.InvitedAt,
		arg.InvitedBy,
	)
	return err
}

const listThreadParticipants = `-- name: ListThreadParticipants :many
SELECT id, thread_id, workspace_id, agent_id, agent_name, task_id, task_title,
       project_id, project_name, assignment_id, assignment_revision,
       agent_revision, task_revision, ordinal, status, invited_at, invited_by
FROM thread_participants
WHERE thread_id = ?
ORDER BY ordinal
`

func (q *Queries) ListThreadParticipants(ctx context.Context, threadID string) ([]ThreadParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listThreadParticipants, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadParticipant{}
	for rows.Next() {
		var i ThreadParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.AgentName,
			&i.TaskID,
			&i.TaskTitle,
			&i.ProjectID,
			&i.ProjectName,
			&i.AssignmentID,
			&i.AssignmentRevision,
			&i.AgentRevision,
			&i.TaskRevision,
			&i.Ordinal,
			&i.Status,
			&i.InvitedAt,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadParticipantsByAgent = `-- name: ListThreadParticipantsByAgent :many
SELECT id, thread_id, workspace_id, agent_id, agent_name, task_id, task_title,
       project_id, project_name, assignment_id, assignment_revision,
       agent_revision, task_revision, ordinal, status, invited_at, invited_by
FROM thread_participants
WHERE thread_id = ?1
  AND agent_id = ?2
  AND status = 'active'
ORDER BY ordinal
`

type ListThreadParticipantsByAgentParams struct {
	ThreadID string `json:"thread_id"`
	AgentID  string `json:"agent_id"`
}

func (q *Queries) ListThreadParticipantsByAgent(ctx context.Context, arg ListThreadParticipantsByAgentParams) ([]ThreadParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listThreadParticipantsByAgent, arg.ThreadID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadParticipant{}
	for rows.Next() {
		var i ThreadParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkspaceID,
			&i.AgentID,
			&i.AgentName,
			&i.TaskID,
			&i.TaskTitle,
			&i.ProjectID,
			&i.ProjectName,
			&i.AssignmentID,
			&i.AssignmentRevision,
			&i.AgentRevision,
			&i.TaskRevision,
			&i.Ordinal,
			&i.Status,
			&i.InvitedAt,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runAuthorizedForMessage = `-- name: RunAuthorizedForMessage :one
SELECT CAST(EXISTS (
    SELECT 1
    FROM messages m
    JOIN message_threads th ON th.id = m.thread_id
    JOIN message_recipients mr ON mr.message_id = m.id
    JOIN runs r ON r.id = ?1
    LEFT JOIN thread_participants p ON p.id = mr.recipient_participant_id
    WHERE m.id = ?2
      AND mr.recipient_agent_id = r.agent_id
      AND r.workspace_id = m.workspace_id
      AND (
        (th.kind = 'direct' AND (m.project_id IS NULL OR m.project_id = r.project_id))
        OR
        (th.kind = 'participant_bound'
          AND p.thread_id = th.id
          AND p.status = 'active'
          AND p.agent_id = r.agent_id
          AND p.project_id = r.project_id
          AND p.task_id = r.task_id
          AND (SELECT COUNT(*) FROM thread_participants roster WHERE roster.thread_id = th.id) BETWEEN 2 AND 8
          AND (SELECT COUNT(*) FROM thread_participants roster WHERE roster.thread_id = th.id) >= th.initial_participant_count
          AND (SELECT COUNT(*) FROM thread_participants roster WHERE roster.thread_id = th.id) = th.initial_participant_count + th.participant_revision - 1
          AND (SELECT COUNT(DISTINCT roster.project_id) FROM thread_participants roster WHERE roster.thread_id = th.id) >= 2)
      )
) AS INTEGER) AS authorized
`

type RunAuthorizedForMessageParams struct {
	RunID     string `json:"run_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) RunAuthorizedForMessage(ctx context.Context, arg RunAuthorizedForMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, runAuthorizedForMessage, arg.RunID, arg.MessageID)
	var authorized int64
	err := row.Scan(&authorized)
	return authorized, err
}
