// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contradictions.sql

package dbgen

import (
	"context"
)

const confirmKnowledgeContradiction = `-- name: ConfirmKnowledgeContradiction :execrows
UPDATE knowledge_contradictions
SET status = 'open', state_revision = state_revision + 1,
    confirmed_at = ?1, confirmed_by = ?2,
    confirmed_by_type = ?3, confirm_note = ?4,
    confirm_event_sequence = ?5
WHERE id = ?6 AND state_revision = ?7
  AND status = 'proposed'
`

type ConfirmKnowledgeContradictionParams struct {
	ConfirmedAt           *string `json:"confirmed_at"`
	ConfirmedBy           *string `json:"confirmed_by"`
	ConfirmedByType       *string `json:"confirmed_by_type"`
	ConfirmNote           *string `json:"confirm_note"`
	ConfirmEventSequence  *int64  `json:"confirm_event_sequence"`
	ID                    string  `json:"id"`
	ExpectedStateRevision int64   `json:"expected_state_revision"`
}

func (q *Queries) ConfirmKnowledgeContradiction(ctx context.Context, arg ConfirmKnowledgeContradictionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, confirmKnowledgeContradiction,
		arg.ConfirmedAt,
		arg.ConfirmedBy,
		arg.ConfirmedByType,
		arg.ConfirmNote,
		arg.ConfirmEventSequence,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countKnowledgeContradictionAuthorityChecks = `-- name: CountKnowledgeContradictionAuthorityChecks :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM knowledge_contradiction_authority_checks
WHERE workspace_id = ?1
  AND contradiction_id = ?2
`

type CountKnowledgeContradictionAuthorityChecksParams struct {
	WorkspaceID     string `json:"workspace_id"`
	ContradictionID string `json:"contradiction_id"`
}

func (q *Queries) CountKnowledgeContradictionAuthorityChecks(ctx context.Context, arg CountKnowledgeContradictionAuthorityChecksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKnowledgeContradictionAuthorityChecks, arg.WorkspaceID, arg.ContradictionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOpenKnowledgeContradictionsForRevision = `-- name: CountOpenKnowledgeContradictionsForRevision :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM knowledge_contradictions
WHERE workspace_id = ?1 AND status = 'open'
  AND (left_revision_id = ?2 OR right_revision_id = ?2)
`

type CountOpenKnowledgeContradictionsForRevisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	RevisionID  string `json:"revision_id"`
}

func (q *Queries) CountOpenKnowledgeContradictionsForRevision(ctx context.Context, arg CountOpenKnowledgeContradictionsForRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenKnowledgeContradictionsForRevision, arg.WorkspaceID, arg.RevisionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const dismissKnowledgeContradiction = `-- name: DismissKnowledgeContradiction :execrows
UPDATE knowledge_contradictions
SET status = 'dismissed', state_revision = state_revision + 1,
    dismissed_at = ?1, dismissed_by = ?2,
    dismissed_by_type = ?3, dismiss_note = ?4,
    dismiss_event_sequence = ?5
WHERE id = ?6 AND state_revision = ?7
  AND status IN ('proposed', 'open')
`

type DismissKnowledgeContradictionParams struct {
	DismissedAt           *string `json:"dismissed_at"`
	DismissedBy           *string `json:"dismissed_by"`
	DismissedByType       *string `json:"dismissed_by_type"`
	DismissNote           *string `json:"dismiss_note"`
	DismissEventSequence  *int64  `json:"dismiss_event_sequence"`
	ID                    string  `json:"id"`
	ExpectedStateRevision int64   `json:"expected_state_revision"`
}

func (q *Queries) DismissKnowledgeContradiction(ctx context.Context, arg DismissKnowledgeContradictionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissKnowledgeContradiction,
		arg.DismissedAt,
		arg.DismissedBy,
		arg.DismissedByType,
		arg.DismissNote,
		arg.DismissEventSequence,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContradictionReporterRunScope = `-- name: GetContradictionReporterRunScope :one
SELECT workspace_id, project_id, task_id, status
FROM runs
WHERE id = ?1
`

type GetContradictionReporterRunScopeRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	Status      string `json:"status"`
}

func (q *Queries) GetContradictionReporterRunScope(ctx context.Context, runID string) (GetContradictionReporterRunScopeRow, error) {
	row := q.db.QueryRowContext(ctx, getContradictionReporterRunScope, runID)
	var i GetContradictionReporterRunScopeRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.Status,
	)
	return i, err
}

const getKnowledgeContradiction = `-- name: GetKnowledgeContradiction :one
SELECT id, workspace_id, project_id, left_revision_id, right_revision_id,
       status, state_revision, report_note, reported_at, reported_by,
       reported_by_type, detected_event_sequence,
       confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
       dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
       resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
       resolution_event_sequence, resolution_cause_event_sequence
FROM knowledge_contradictions
WHERE workspace_id = ?1 AND id = ?2
`

type GetKnowledgeContradictionParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetKnowledgeContradiction(ctx context.Context, arg GetKnowledgeContradictionParams) (KnowledgeContradiction, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeContradiction, arg.WorkspaceID, arg.ID)
	var i KnowledgeContradiction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.LeftRevisionID,
		&i.RightRevisionID,
		&i.Status,
		&i.StateRevision,
		&i.ReportNote,
		&i.ReportedAt,
		&i.ReportedBy,
		&i.ReportedByType,
		&i.DetectedEventSequence,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.ConfirmedByType,
		&i.ConfirmNote,
		&i.ConfirmEventSequence,
		&i.DismissedAt,
		&i.DismissedBy,
		&i.DismissedByType,
		&i.DismissNote,
		&i.DismissEventSequence,
		&i.ResolutionReason,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.ResolvedByType,
		&i.ResolutionNote,
		&i.ResolutionEventSequence,
		&i.ResolutionCauseEventSequence,
	)
	return i, err
}

const getKnowledgeContradictionAuthorityCheckByKey = `-- name: GetKnowledgeContradictionAuthorityCheckByKey :one
SELECT id, workspace_id, contradiction_id, action, actor_id, actor_type,
       outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
FROM knowledge_contradiction_authority_checks
WHERE actor_type = ?1 AND actor_id = ?2
  AND action = ?3 AND idempotency_key = ?4
`

type GetKnowledgeContradictionAuthorityCheckByKeyParams struct {
	ActorType      string `json:"actor_type"`
	ActorID        string `json:"actor_id"`
	Action         string `json:"action"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetKnowledgeContradictionAuthorityCheckByKey(ctx context.Context, arg GetKnowledgeContradictionAuthorityCheckByKeyParams) (KnowledgeContradictionAuthorityCheck, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeContradictionAuthorityCheckByKey,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.IdempotencyKey,
	)
	var i KnowledgeContradictionAuthorityCheck
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ContradictionID,
		&i.Action,
		&i.ActorID,
		&i.ActorType,
		&i.Outcome,
		&i.Reason,
		&i.Note,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.EventSequence,
		&i.CreatedAt,
	)
	return i, err
}

const getKnowledgeContradictionByPair = `-- name: GetKnowledgeContradictionByPair :one
SELECT id, workspace_id, project_id, left_revision_id, right_revision_id,
       status, state_revision, report_note, reported_at, reported_by,
       reported_by_type, detected_event_sequence,
       confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
       dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
       resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
       resolution_event_sequence, resolution_cause_event_sequence
FROM knowledge_contradictions
WHERE workspace_id = ?1
  AND left_revision_id = ?2
  AND right_revision_id = ?3
`

type GetKnowledgeContradictionByPairParams struct {
	WorkspaceID     string `json:"workspace_id"`
	LeftRevisionID  string `json:"left_revision_id"`
	RightRevisionID string `json:"right_revision_id"`
}

func (q *Queries) GetKnowledgeContradictionByPair(ctx context.Context, arg GetKnowledgeContradictionByPairParams) (KnowledgeContradiction, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeContradictionByPair, arg.WorkspaceID, arg.LeftRevisionID, arg.RightRevisionID)
	var i KnowledgeContradiction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.LeftRevisionID,
		&i.RightRevisionID,
		&i.Status,
		&i.StateRevision,
		&i.ReportNote,
		&i.ReportedAt,
		&i.ReportedBy,
		&i.ReportedByType,
		&i.DetectedEventSequence,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.ConfirmedByType,
		&i.ConfirmNote,
		&i.ConfirmEventSequence,
		&i.DismissedAt,
		&i.DismissedBy,
		&i.DismissedByType,
		&i.DismissNote,
		&i.DismissEventSequence,
		&i.ResolutionReason,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.ResolvedByType,
		&i.ResolutionNote,
		&i.ResolutionEventSequence,
		&i.ResolutionCauseEventSequence,
	)
	return i, err
}

const insertKnowledgeContradiction = `-- name: InsertKnowledgeContradiction :exec
INSERT INTO knowledge_contradictions(
    id, workspace_id, project_id, left_revision_id, right_revision_id,
    status, state_revision, report_note, reported_at, reported_by,
    reported_by_type, detected_event_sequence
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, 'proposed', 1,
    ?6, ?7, ?8,
    ?9, ?10
)
`

type InsertKnowledgeContradictionParams struct {
	ID                    string `json:"id"`
	WorkspaceID           string `json:"workspace_id"`
	ProjectID             string `json:"project_id"`
	LeftRevisionID        string `json:"left_revision_id"`
	RightRevisionID       string `json:"right_revision_id"`
	ReportNote            string `json:"report_note"`
	ReportedAt            string `json:"reported_at"`
	ReportedBy            string `json:"reported_by"`
	ReportedByType        string `json:"reported_by_type"`
	DetectedEventSequence int64  `json:"detected_event_sequence"`
}

func (q *Queries) InsertKnowledgeContradiction(ctx context.Context, arg InsertKnowledgeContradictionParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeContradiction,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.LeftRevisionID,
		arg.RightRevisionID,
		arg.ReportNote,
		arg.ReportedAt,
		arg.ReportedBy,
		arg.ReportedByType,
		arg.DetectedEventSequence,
	)
	return err
}

const insertKnowledgeContradictionAuthorityCheck = `-- name: InsertKnowledgeContradictionAuthorityCheck :exec
INSERT INTO knowledge_contradiction_authority_checks(
    id, workspace_id, contradiction_id, action, actor_id, actor_type,
    outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8, ?9,
    ?10, ?11,
    ?12, ?13
)
`

type InsertKnowledgeContradictionAuthorityCheckParams struct {
	ID              string  `json:"id"`
	WorkspaceID     string  `json:"workspace_id"`
	ContradictionID string  `json:"contradiction_id"`
	Action          string  `json:"action"`
	ActorID         string  `json:"actor_id"`
	ActorType       string  `json:"actor_type"`
	Outcome         string  `json:"outcome"`
	Reason          string  `json:"reason"`
	Note            *string `json:"note"`
	IdempotencyKey  string  `json:"idempotency_key"`
	RequestHash     string  `json:"request_hash"`
	EventSequence   int64   `json:"event_sequence"`
	CreatedAt       string  `json:"created_at"`
}

func (q *Queries) InsertKnowledgeContradictionAuthorityCheck(ctx context.Context, arg InsertKnowledgeContradictionAuthorityCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeContradictionAuthorityCheck,
		arg.ID,
		arg.WorkspaceID,
		arg.ContradictionID,
		arg.Action,
		arg.ActorID,
		arg.ActorType,
		arg.Outcome,
		arg.Reason,
		arg.Note,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.EventSequence,
		arg.CreatedAt,
	)
	return err
}

const listAllOpenKnowledgeContradictionsForRevision = `-- name: ListAllOpenKnowledgeContradictionsForRevision :many
SELECT id, workspace_id, project_id, left_revision_id, right_revision_id,
       status, state_revision, report_note, reported_at, reported_by,
       reported_by_type, detected_event_sequence,
       confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
       dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
       resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
       resolution_event_sequence, resolution_cause_event_sequence
FROM knowledge_contradictions
WHERE workspace_id = ?1 AND status = 'open'
  AND (left_revision_id = ?2 OR right_revision_id = ?2)
ORDER BY id
`

type ListAllOpenKnowledgeContradictionsForRevisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	RevisionID  string `json:"revision_id"`
}

func (q *Queries) ListAllOpenKnowledgeContradictionsForRevision(ctx context.Context, arg ListAllOpenKnowledgeContradictionsForRevisionParams) ([]KnowledgeContradiction, error) {
	rows, err := q.db.QueryContext(ctx, listAllOpenKnowledgeContradictionsForRevision, arg.WorkspaceID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeContradiction{}
	for rows.Next() {
		var i KnowledgeContradiction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.LeftRevisionID,
			&i.RightRevisionID,
			&i.Status,
			&i.StateRevision,
			&i.ReportNote,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.ReportedByType,
			&i.DetectedEventSequence,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.ConfirmedByType,
			&i.ConfirmNote,
			&i.ConfirmEventSequence,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.DismissedByType,
			&i.DismissNote,
			&i.DismissEventSequence,
			&i.ResolutionReason,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolvedByType,
			&i.ResolutionNote,
			&i.ResolutionEventSequence,
			&i.ResolutionCauseEventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeContradictionAuthorityChecks = `-- name: ListKnowledgeContradictionAuthorityChecks :many
SELECT id, workspace_id, contradiction_id, action, actor_id, actor_type,
       outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
FROM knowledge_contradiction_authority_checks
WHERE workspace_id = ?1
  AND contradiction_id = ?2
ORDER BY event_sequence DESC, id DESC
LIMIT 200
`

type ListKnowledgeContradictionAuthorityChecksParams struct {
	WorkspaceID     string `json:"workspace_id"`
	ContradictionID string `json:"contradiction_id"`
}

func (q *Queries) ListKnowledgeContradictionAuthorityChecks(ctx context.Context, arg ListKnowledgeContradictionAuthorityChecksParams) ([]KnowledgeContradictionAuthorityCheck, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeContradictionAuthorityChecks, arg.WorkspaceID, arg.ContradictionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeContradictionAuthorityCheck{}
	for rows.Next() {
		var i KnowledgeContradictionAuthorityCheck
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ContradictionID,
			&i.Action,
			&i.ActorID,
			&i.ActorType,
			&i.Outcome,
			&i.Reason,
			&i.Note,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.EventSequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeContradictionIDs = `-- name: ListKnowledgeContradictionIDs :many
SELECT id
FROM knowledge_contradictions
WHERE workspace_id = ?1
  AND (?2 = '' OR project_id = ?2)
  AND ((?3 = '' AND status IN ('proposed', 'open')) OR status = ?3)
  AND (?4 = '' OR left_revision_id = ?4
       OR right_revision_id = ?4)
ORDER BY crewfold_timestamp_key(reported_at) DESC, id DESC
LIMIT ?5
`

type ListKnowledgeContradictionIDsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	ProjectID   interface{} `json:"project_id"`
	Status      interface{} `json:"status"`
	RevisionID  interface{} `json:"revision_id"`
	ResultLimit int64       `json:"result_limit"`
}

func (q *Queries) ListKnowledgeContradictionIDs(ctx context.Context, arg ListKnowledgeContradictionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeContradictionIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.RevisionID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenKnowledgeContradictionsForRevision = `-- name: ListOpenKnowledgeContradictionsForRevision :many
SELECT id, workspace_id, project_id, left_revision_id, right_revision_id,
       status, state_revision, report_note, reported_at, reported_by,
       reported_by_type, detected_event_sequence,
       confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
       dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
       resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
       resolution_event_sequence, resolution_cause_event_sequence
FROM knowledge_contradictions
WHERE workspace_id = ?1 AND status = 'open'
  AND (left_revision_id = ?2 OR right_revision_id = ?2)
ORDER BY id
LIMIT 200
`

type ListOpenKnowledgeContradictionsForRevisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	RevisionID  string `json:"revision_id"`
}

func (q *Queries) ListOpenKnowledgeContradictionsForRevision(ctx context.Context, arg ListOpenKnowledgeContradictionsForRevisionParams) ([]KnowledgeContradiction, error) {
	rows, err := q.db.QueryContext(ctx, listOpenKnowledgeContradictionsForRevision, arg.WorkspaceID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeContradiction{}
	for rows.Next() {
		var i KnowledgeContradiction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.LeftRevisionID,
			&i.RightRevisionID,
			&i.Status,
			&i.StateRevision,
			&i.ReportNote,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.ReportedByType,
			&i.DetectedEventSequence,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.ConfirmedByType,
			&i.ConfirmNote,
			&i.ConfirmEventSequence,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.DismissedByType,
			&i.DismissNote,
			&i.DismissEventSequence,
			&i.ResolutionReason,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolvedByType,
			&i.ResolutionNote,
			&i.ResolutionEventSequence,
			&i.ResolutionCauseEventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveKnowledgeContradiction = `-- name: ResolveKnowledgeContradiction :execrows
UPDATE knowledge_contradictions
SET status = 'resolved', state_revision = state_revision + 1,
    resolution_reason = ?1, resolved_at = ?2,
    resolved_by = ?3, resolved_by_type = ?4,
    resolution_note = ?5,
    resolution_event_sequence = ?6,
    resolution_cause_event_sequence = ?7
WHERE id = ?8 AND state_revision = ?9
  AND status = 'open'
`

type ResolveKnowledgeContradictionParams struct {
	ResolutionReason             *string `json:"resolution_reason"`
	ResolvedAt                   *string `json:"resolved_at"`
	ResolvedBy                   *string `json:"resolved_by"`
	ResolvedByType               *string `json:"resolved_by_type"`
	ResolutionNote               *string `json:"resolution_note"`
	ResolutionEventSequence      *int64  `json:"resolution_event_sequence"`
	ResolutionCauseEventSequence *int64  `json:"resolution_cause_event_sequence"`
	ID                           string  `json:"id"`
	ExpectedStateRevision        int64   `json:"expected_state_revision"`
}

func (q *Queries) ResolveKnowledgeContradiction(ctx context.Context, arg ResolveKnowledgeContradictionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveKnowledgeContradiction,
		arg.ResolutionReason,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.ResolvedByType,
		arg.ResolutionNote,
		arg.ResolutionEventSequence,
		arg.ResolutionCauseEventSequence,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
