// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_packets.sql

package dbgen

import (
	"context"
)

const countContextDependencies = `-- name: CountContextDependencies :one
SELECT COUNT(*) FROM task_dependencies WHERE task_id = ?
`

func (q *Queries) CountContextDependencies(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContextDependencies, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContextDependents = `-- name: CountContextDependents :one
SELECT COUNT(*) FROM task_dependencies WHERE depends_on_task_id = ?
`

func (q *Queries) CountContextDependents(ctx context.Context, dependsOnTaskID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContextDependents, dependsOnTaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContextParticipantThreads = `-- name: CountContextParticipantThreads :one
SELECT COUNT(*)
FROM message_threads thread JOIN thread_participants participant ON participant.thread_id = thread.id
WHERE thread.workspace_id = ? AND thread.kind = 'participant_bound' AND thread.status = 'open'
  AND participant.status = 'active' AND participant.agent_id = ?
  AND participant.project_id = ? AND participant.task_id = ?
`

type CountContextParticipantThreadsParams struct {
	WorkspaceID string `json:"workspace_id"`
	AgentID     string `json:"agent_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
}

func (q *Queries) CountContextParticipantThreads(ctx context.Context, arg CountContextParticipantThreadsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContextParticipantThreads,
		arg.WorkspaceID,
		arg.AgentID,
		arg.ProjectID,
		arg.TaskID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContextEventCursor = `-- name: GetContextEventCursor :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER) FROM events
`

func (q *Queries) GetContextEventCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getContextEventCursor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getContextRepositoryFingerprint = `-- name: GetContextRepositoryFingerprint :one
SELECT fingerprint FROM repositories WHERE id = ? AND workspace_id = ?
`

type GetContextRepositoryFingerprintParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetContextRepositoryFingerprint(ctx context.Context, arg GetContextRepositoryFingerprintParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getContextRepositoryFingerprint, arg.ID, arg.WorkspaceID)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const getWorkspaceContextPacket = `-- name: GetWorkspaceContextPacket :one
SELECT packet_json, project_id, task_id, agent_id, checkout_id, content_hash, byte_size
FROM context_packets WHERE id = ? AND workspace_id = ?
`

type GetWorkspaceContextPacketParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetWorkspaceContextPacketRow struct {
	PacketJson  string `json:"packet_json"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	AgentID     string `json:"agent_id"`
	CheckoutID  string `json:"checkout_id"`
	ContentHash string `json:"content_hash"`
	ByteSize    int64  `json:"byte_size"`
}

func (q *Queries) GetWorkspaceContextPacket(ctx context.Context, arg GetWorkspaceContextPacketParams) (GetWorkspaceContextPacketRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceContextPacket, arg.ID, arg.WorkspaceID)
	var i GetWorkspaceContextPacketRow
	err := row.Scan(
		&i.PacketJson,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentID,
		&i.CheckoutID,
		&i.ContentHash,
		&i.ByteSize,
	)
	return i, err
}

const insertContextPacket = `-- name: InsertContextPacket :exec
INSERT INTO context_packets(
    id, workspace_id, project_id, task_id, agent_id, checkout_id, packet_json,
    content_hash, byte_size, created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContextPacketParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	AgentID     string `json:"agent_id"`
	CheckoutID  string `json:"checkout_id"`
	PacketJson  string `json:"packet_json"`
	ContentHash string `json:"content_hash"`
	ByteSize    int64  `json:"byte_size"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) InsertContextPacket(ctx context.Context, arg InsertContextPacketParams) error {
	_, err := q.db.ExecContext(ctx, insertContextPacket,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.AgentID,
		arg.CheckoutID,
		arg.PacketJson,
		arg.ContentHash,
		arg.ByteSize,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const listContextDependencies = `-- name: ListContextDependencies :many
SELECT task.id, task.title, task.status, task.revision
FROM task_dependencies dependency JOIN tasks task ON task.id = dependency.depends_on_task_id
WHERE dependency.task_id = ? ORDER BY task.id
`

type ListContextDependenciesRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Status   string `json:"status"`
	Revision int64  `json:"revision"`
}

func (q *Queries) ListContextDependencies(ctx context.Context, taskID string) ([]ListContextDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listContextDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContextDependenciesRow{}
	for rows.Next() {
		var i ListContextDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextDependents = `-- name: ListContextDependents :many
SELECT task.id, task.title, task.status, task.revision
FROM task_dependencies dependency JOIN tasks task ON task.id = dependency.task_id
WHERE dependency.depends_on_task_id = ? ORDER BY task.id LIMIT ?
`

type ListContextDependentsParams struct {
	DependsOnTaskID string `json:"depends_on_task_id"`
	Limit           int64  `json:"limit"`
}

type ListContextDependentsRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Status   string `json:"status"`
	Revision int64  `json:"revision"`
}

func (q *Queries) ListContextDependents(ctx context.Context, arg ListContextDependentsParams) ([]ListContextDependentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContextDependents, arg.DependsOnTaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContextDependentsRow{}
	for rows.Next() {
		var i ListContextDependentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextParticipantThreadIDs = `-- name: ListContextParticipantThreadIDs :many
SELECT thread.id
FROM message_threads thread JOIN thread_participants participant ON participant.thread_id = thread.id
WHERE thread.workspace_id = ? AND thread.kind = 'participant_bound' AND thread.status = 'open'
  AND participant.status = 'active' AND participant.agent_id = ?
  AND participant.project_id = ? AND participant.task_id = ?
ORDER BY crewfold_timestamp_key(thread.updated_at) DESC, thread.id ASC LIMIT ?
`

type ListContextParticipantThreadIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	AgentID     string `json:"agent_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListContextParticipantThreadIDs(ctx context.Context, arg ListContextParticipantThreadIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listContextParticipantThreadIDs,
		arg.WorkspaceID,
		arg.AgentID,
		arg.ProjectID,
		arg.TaskID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
