// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_deltas.sql

package dbgen

import (
	"context"
)

const acknowledgeRunContextDelta = `-- name: AcknowledgeRunContextDelta :execrows
UPDATE run_context_delta_state
SET status = 'ready', revision = revision + 1, pending_delta_id = NULL,
    last_acknowledged_delta_id = ?, updated_at = ?
WHERE run_id = ? AND context_packet_id = ? AND status = 'pending_ack'
  AND revision = ? AND pending_delta_id = ? AND last_sequence = ?
`

type AcknowledgeRunContextDeltaParams struct {
	LastAcknowledgedDeltaID *string `json:"last_acknowledged_delta_id"`
	UpdatedAt               string  `json:"updated_at"`
	RunID                   string  `json:"run_id"`
	ContextPacketID         string  `json:"context_packet_id"`
	Revision                int64   `json:"revision"`
	PendingDeltaID          *string `json:"pending_delta_id"`
	LastSequence            int64   `json:"last_sequence"`
}

func (q *Queries) AcknowledgeRunContextDelta(ctx context.Context, arg AcknowledgeRunContextDeltaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeRunContextDelta,
		arg.LastAcknowledgedDeltaID,
		arg.UpdatedAt,
		arg.RunID,
		arg.ContextPacketID,
		arg.Revision,
		arg.PendingDeltaID,
		arg.LastSequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceRunContextDeltaScan = `-- name: AdvanceRunContextDeltaScan :execrows
UPDATE run_context_delta_state
SET revision = revision + 1, scan_event_sequence = ?, updated_at = ?
WHERE run_id = ? AND context_packet_id = ? AND status = 'ready'
  AND revision = ? AND scan_event_sequence = ? AND pending_delta_id IS NULL
`

type AdvanceRunContextDeltaScanParams struct {
	ScanEventSequence   int64  `json:"scan_event_sequence"`
	UpdatedAt           string `json:"updated_at"`
	RunID               string `json:"run_id"`
	ContextPacketID     string `json:"context_packet_id"`
	Revision            int64  `json:"revision"`
	ScanEventSequence_2 int64  `json:"scan_event_sequence_2"`
}

func (q *Queries) AdvanceRunContextDeltaScan(ctx context.Context, arg AdvanceRunContextDeltaScanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceRunContextDeltaScan,
		arg.ScanEventSequence,
		arg.UpdatedAt,
		arg.RunID,
		arg.ContextPacketID,
		arg.Revision,
		arg.ScanEventSequence_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContextDeltaAcknowledgement = `-- name: GetContextDeltaAcknowledgement :one
SELECT id, run_id, context_packet_id, delta_id, sequence,
       acknowledged_at, acknowledged_by, idempotency_key, request_hash, event_sequence
FROM context_delta_acknowledgements
WHERE delta_id = ? AND run_id = ?
`

type GetContextDeltaAcknowledgementParams struct {
	DeltaID string `json:"delta_id"`
	RunID   string `json:"run_id"`
}

func (q *Queries) GetContextDeltaAcknowledgement(ctx context.Context, arg GetContextDeltaAcknowledgementParams) (ContextDeltaAcknowledgement, error) {
	row := q.db.QueryRowContext(ctx, getContextDeltaAcknowledgement, arg.DeltaID, arg.RunID)
	var i ContextDeltaAcknowledgement
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ContextPacketID,
		&i.DeltaID,
		&i.Sequence,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.EventSequence,
	)
	return i, err
}

const getContextDeltaByID = `-- name: GetContextDeltaByID :one
SELECT id, run_id, context_packet_id, sequence, parent_delta_id,
       from_event_sequence, through_event_sequence, delta_json, content_hash,
       byte_size, built_event_sequence, created_at, created_by
FROM context_deltas
WHERE id = ?
`

func (q *Queries) GetContextDeltaByID(ctx context.Context, id string) (ContextDelta, error) {
	row := q.db.QueryRowContext(ctx, getContextDeltaByID, id)
	var i ContextDelta
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ContextPacketID,
		&i.Sequence,
		&i.ParentDeltaID,
		&i.FromEventSequence,
		&i.ThroughEventSequence,
		&i.DeltaJson,
		&i.ContentHash,
		&i.ByteSize,
		&i.BuiltEventSequence,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getRunContextDeltaByID = `-- name: GetRunContextDeltaByID :one
SELECT id, run_id, context_packet_id, sequence, parent_delta_id,
       from_event_sequence, through_event_sequence, delta_json, content_hash,
       byte_size, built_event_sequence, created_at, created_by
FROM context_deltas
WHERE id = ? AND run_id = ?
`

type GetRunContextDeltaByIDParams struct {
	ID    string `json:"id"`
	RunID string `json:"run_id"`
}

func (q *Queries) GetRunContextDeltaByID(ctx context.Context, arg GetRunContextDeltaByIDParams) (ContextDelta, error) {
	row := q.db.QueryRowContext(ctx, getRunContextDeltaByID, arg.ID, arg.RunID)
	var i ContextDelta
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ContextPacketID,
		&i.Sequence,
		&i.ParentDeltaID,
		&i.FromEventSequence,
		&i.ThroughEventSequence,
		&i.DeltaJson,
		&i.ContentHash,
		&i.ByteSize,
		&i.BuiltEventSequence,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getRunContextDeltaState = `-- name: GetRunContextDeltaState :one
SELECT run_id, context_packet_id, status, revision, scan_event_sequence,
       last_sequence, last_delta_id, pending_delta_id,
       last_acknowledged_delta_id, delta_count, cumulative_byte_size,
       rebase_reason, rebase_event_sequence, created_at, updated_at
FROM run_context_delta_state
WHERE run_id = ?
`

func (q *Queries) GetRunContextDeltaState(ctx context.Context, runID string) (RunContextDeltaState, error) {
	row := q.db.QueryRowContext(ctx, getRunContextDeltaState, runID)
	var i RunContextDeltaState
	err := row.Scan(
		&i.RunID,
		&i.ContextPacketID,
		&i.Status,
		&i.Revision,
		&i.ScanEventSequence,
		&i.LastSequence,
		&i.LastDeltaID,
		&i.PendingDeltaID,
		&i.LastAcknowledgedDeltaID,
		&i.DeltaCount,
		&i.CumulativeByteSize,
		&i.RebaseReason,
		&i.RebaseEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceContextDeltaByID = `-- name: GetWorkspaceContextDeltaByID :one
SELECT delta.id, delta.run_id, delta.context_packet_id, delta.sequence, delta.parent_delta_id,
       delta.from_event_sequence, delta.through_event_sequence, delta.delta_json, delta.content_hash,
       delta.byte_size, delta.built_event_sequence, delta.created_at, delta.created_by
FROM context_deltas delta
JOIN runs run ON run.id = delta.run_id
WHERE delta.id = ? AND run.workspace_id = ?
`

type GetWorkspaceContextDeltaByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetWorkspaceContextDeltaByID(ctx context.Context, arg GetWorkspaceContextDeltaByIDParams) (ContextDelta, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceContextDeltaByID, arg.ID, arg.WorkspaceID)
	var i ContextDelta
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ContextPacketID,
		&i.Sequence,
		&i.ParentDeltaID,
		&i.FromEventSequence,
		&i.ThroughEventSequence,
		&i.DeltaJson,
		&i.ContentHash,
		&i.ByteSize,
		&i.BuiltEventSequence,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertContextDelta = `-- name: InsertContextDelta :exec
INSERT INTO context_deltas(
    id, run_id, context_packet_id, sequence, parent_delta_id,
    from_event_sequence, through_event_sequence, delta_json, content_hash,
    byte_size, built_event_sequence, created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContextDeltaParams struct {
	ID                   string  `json:"id"`
	RunID                string  `json:"run_id"`
	ContextPacketID      string  `json:"context_packet_id"`
	Sequence             int64   `json:"sequence"`
	ParentDeltaID        *string `json:"parent_delta_id"`
	FromEventSequence    int64   `json:"from_event_sequence"`
	ThroughEventSequence int64   `json:"through_event_sequence"`
	DeltaJson            string  `json:"delta_json"`
	ContentHash          string  `json:"content_hash"`
	ByteSize             int64   `json:"byte_size"`
	BuiltEventSequence   int64   `json:"built_event_sequence"`
	CreatedAt            string  `json:"created_at"`
	CreatedBy            string  `json:"created_by"`
}

func (q *Queries) InsertContextDelta(ctx context.Context, arg InsertContextDeltaParams) error {
	_, err := q.db.ExecContext(ctx, insertContextDelta,
		arg.ID,
		arg.RunID,
		arg.ContextPacketID,
		arg.Sequence,
		arg.ParentDeltaID,
		arg.FromEventSequence,
		arg.ThroughEventSequence,
		arg.DeltaJson,
		arg.ContentHash,
		arg.ByteSize,
		arg.BuiltEventSequence,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertContextDeltaAcknowledgement = `-- name: InsertContextDeltaAcknowledgement :exec
INSERT INTO context_delta_acknowledgements(
    id, run_id, context_packet_id, delta_id, sequence,
    acknowledged_at, acknowledged_by, idempotency_key, request_hash, event_sequence
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertContextDeltaAcknowledgementParams struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	ContextPacketID string `json:"context_packet_id"`
	DeltaID         string `json:"delta_id"`
	Sequence        int64  `json:"sequence"`
	AcknowledgedAt  string `json:"acknowledged_at"`
	AcknowledgedBy  string `json:"acknowledged_by"`
	IdempotencyKey  string `json:"idempotency_key"`
	RequestHash     string `json:"request_hash"`
	EventSequence   int64  `json:"event_sequence"`
}

func (q *Queries) InsertContextDeltaAcknowledgement(ctx context.Context, arg InsertContextDeltaAcknowledgementParams) error {
	_, err := q.db.ExecContext(ctx, insertContextDeltaAcknowledgement,
		arg.ID,
		arg.RunID,
		arg.ContextPacketID,
		arg.DeltaID,
		arg.Sequence,
		arg.AcknowledgedAt,
		arg.AcknowledgedBy,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.EventSequence,
	)
	return err
}

const insertRunContextDeltaState = `-- name: InsertRunContextDeltaState :exec
INSERT INTO run_context_delta_state(
    run_id, context_packet_id, status, revision, scan_event_sequence,
    last_sequence, last_delta_id, pending_delta_id, last_acknowledged_delta_id,
    delta_count, cumulative_byte_size, rebase_reason, rebase_event_sequence,
    created_at, updated_at
) VALUES (?, ?, 'ready', 1, ?, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, ?, ?)
`

type InsertRunContextDeltaStateParams struct {
	RunID             string `json:"run_id"`
	ContextPacketID   string `json:"context_packet_id"`
	ScanEventSequence int64  `json:"scan_event_sequence"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) InsertRunContextDeltaState(ctx context.Context, arg InsertRunContextDeltaStateParams) error {
	_, err := q.db.ExecContext(ctx, insertRunContextDeltaState,
		arg.RunID,
		arg.ContextPacketID,
		arg.ScanEventSequence,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAllRunContextDeltas = `-- name: ListAllRunContextDeltas :many
SELECT id, run_id, context_packet_id, sequence, parent_delta_id,
       from_event_sequence, through_event_sequence, delta_json, content_hash,
       byte_size, built_event_sequence, created_at, created_by
FROM context_deltas
WHERE run_id = ?
ORDER BY sequence
`

func (q *Queries) ListAllRunContextDeltas(ctx context.Context, runID string) ([]ContextDelta, error) {
	rows, err := q.db.QueryContext(ctx, listAllRunContextDeltas, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextDelta{}
	for rows.Next() {
		var i ContextDelta
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ContextPacketID,
			&i.Sequence,
			&i.ParentDeltaID,
			&i.FromEventSequence,
			&i.ThroughEventSequence,
			&i.DeltaJson,
			&i.ContentHash,
			&i.ByteSize,
			&i.BuiltEventSequence,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunContextDeltas = `-- name: ListRunContextDeltas :many
SELECT id, run_id, context_packet_id, sequence, parent_delta_id,
       from_event_sequence, through_event_sequence, delta_json, content_hash,
       byte_size, built_event_sequence, created_at, created_by
FROM context_deltas
WHERE run_id = ? AND sequence > ?
ORDER BY sequence
LIMIT ?
`

type ListRunContextDeltasParams struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListRunContextDeltas(ctx context.Context, arg ListRunContextDeltasParams) ([]ContextDelta, error) {
	rows, err := q.db.QueryContext(ctx, listRunContextDeltas, arg.RunID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextDelta{}
	for rows.Next() {
		var i ContextDelta
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ContextPacketID,
			&i.Sequence,
			&i.ParentDeltaID,
			&i.FromEventSequence,
			&i.ThroughEventSequence,
			&i.DeltaJson,
			&i.ContentHash,
			&i.ByteSize,
			&i.BuiltEventSequence,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunContextDeltaPending = `-- name: MarkRunContextDeltaPending :execrows
UPDATE run_context_delta_state
SET status = 'pending_ack', revision = revision + 1,
    scan_event_sequence = ?, last_sequence = ?, last_delta_id = ?,
    pending_delta_id = ?, delta_count = delta_count + 1,
    cumulative_byte_size = cumulative_byte_size + ?, updated_at = ?
WHERE run_id = ? AND context_packet_id = ? AND status = 'ready'
  AND revision = ? AND scan_event_sequence = ? AND last_sequence = ?
  AND pending_delta_id IS NULL
`

type MarkRunContextDeltaPendingParams struct {
	ScanEventSequence   int64   `json:"scan_event_sequence"`
	LastSequence        int64   `json:"last_sequence"`
	LastDeltaID         *string `json:"last_delta_id"`
	PendingDeltaID      *string `json:"pending_delta_id"`
	CumulativeByteSize  int64   `json:"cumulative_byte_size"`
	UpdatedAt           string  `json:"updated_at"`
	RunID               string  `json:"run_id"`
	ContextPacketID     string  `json:"context_packet_id"`
	Revision            int64   `json:"revision"`
	ScanEventSequence_2 int64   `json:"scan_event_sequence_2"`
	LastSequence_2      int64   `json:"last_sequence_2"`
}

func (q *Queries) MarkRunContextDeltaPending(ctx context.Context, arg MarkRunContextDeltaPendingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRunContextDeltaPending,
		arg.ScanEventSequence,
		arg.LastSequence,
		arg.LastDeltaID,
		arg.PendingDeltaID,
		arg.CumulativeByteSize,
		arg.UpdatedAt,
		arg.RunID,
		arg.ContextPacketID,
		arg.Revision,
		arg.ScanEventSequence_2,
		arg.LastSequence_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markRunContextRebaseRequired = `-- name: MarkRunContextRebaseRequired :execrows
UPDATE run_context_delta_state
SET status = 'rebase_required', revision = revision + 1,
    scan_event_sequence = ?, rebase_reason = ?, rebase_event_sequence = ?, updated_at = ?
WHERE run_id = ? AND context_packet_id = ? AND status = 'ready'
  AND revision = ? AND scan_event_sequence = ? AND pending_delta_id IS NULL
`

type MarkRunContextRebaseRequiredParams struct {
	ScanEventSequence   int64   `json:"scan_event_sequence"`
	RebaseReason        *string `json:"rebase_reason"`
	RebaseEventSequence *int64  `json:"rebase_event_sequence"`
	UpdatedAt           string  `json:"updated_at"`
	RunID               string  `json:"run_id"`
	ContextPacketID     string  `json:"context_packet_id"`
	Revision            int64   `json:"revision"`
	ScanEventSequence_2 int64   `json:"scan_event_sequence_2"`
}

func (q *Queries) MarkRunContextRebaseRequired(ctx context.Context, arg MarkRunContextRebaseRequiredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRunContextRebaseRequired,
		arg.ScanEventSequence,
		arg.RebaseReason,
		arg.RebaseEventSequence,
		arg.UpdatedAt,
		arg.RunID,
		arg.ContextPacketID,
		arg.Revision,
		arg.ScanEventSequence_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
