// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curator.sql

package dbgen

import (
	"context"
)

const getCuratorAutoAcceptanceByKnowledge = `-- name: GetCuratorAutoAcceptanceByKnowledge :one
SELECT id, workspace_id, project_id, rule_id, rule_name, rule_revision,
       derivation_id, knowledge_revision_id, authority_check_id,
       knowledge_event_sequence, event_sequence, created_at, actor_id, actor_type
FROM curator_auto_acceptances
WHERE workspace_id = ?1
  AND knowledge_revision_id = ?2
`

type GetCuratorAutoAcceptanceByKnowledgeParams struct {
	WorkspaceID         string `json:"workspace_id"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
}

func (q *Queries) GetCuratorAutoAcceptanceByKnowledge(ctx context.Context, arg GetCuratorAutoAcceptanceByKnowledgeParams) (CuratorAutoAcceptance, error) {
	row := q.db.QueryRowContext(ctx, getCuratorAutoAcceptanceByKnowledge, arg.WorkspaceID, arg.KnowledgeRevisionID)
	var i CuratorAutoAcceptance
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleRevision,
		&i.DerivationID,
		&i.KnowledgeRevisionID,
		&i.AuthorityCheckID,
		&i.KnowledgeEventSequence,
		&i.EventSequence,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorType,
	)
	return i, err
}

const getCuratorDerivationByKnowledge = `-- name: GetCuratorDerivationByKnowledge :one
SELECT id, workspace_id, project_id, rule_id, rule_name, rule_revision,
       source_type, source_id, source_revision, source_content_hash,
       knowledge_revision_id, output_content_hash, created_at, created_by,
       event_sequence
FROM curator_derivations
WHERE workspace_id = ?1
  AND knowledge_revision_id = ?2
`

type GetCuratorDerivationByKnowledgeParams struct {
	WorkspaceID         string `json:"workspace_id"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
}

func (q *Queries) GetCuratorDerivationByKnowledge(ctx context.Context, arg GetCuratorDerivationByKnowledgeParams) (CuratorDerivation, error) {
	row := q.db.QueryRowContext(ctx, getCuratorDerivationByKnowledge, arg.WorkspaceID, arg.KnowledgeRevisionID)
	var i CuratorDerivation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleRevision,
		&i.SourceType,
		&i.SourceID,
		&i.SourceRevision,
		&i.SourceContentHash,
		&i.KnowledgeRevisionID,
		&i.OutputContentHash,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.EventSequence,
	)
	return i, err
}

const getCuratorMeetingProposalSource = `-- name: GetCuratorMeetingProposalSource :one
SELECT mp.id AS proposal_id, mp.revision AS proposal_revision, mp.summary,
       mp.proposed_at, m.id AS meeting_id, m.agenda, m.workspace_id, m.project_id,
       mp.status AS proposal_status, m.status AS meeting_status
FROM meeting_proposals mp
JOIN meetings m ON m.id = mp.meeting_id
WHERE mp.id = ?1
`

type GetCuratorMeetingProposalSourceRow struct {
	ProposalID       string `json:"proposal_id"`
	ProposalRevision int64  `json:"proposal_revision"`
	Summary          string `json:"summary"`
	ProposedAt       string `json:"proposed_at"`
	MeetingID        string `json:"meeting_id"`
	Agenda           string `json:"agenda"`
	WorkspaceID      string `json:"workspace_id"`
	ProjectID        string `json:"project_id"`
	ProposalStatus   string `json:"proposal_status"`
	MeetingStatus    string `json:"meeting_status"`
}

func (q *Queries) GetCuratorMeetingProposalSource(ctx context.Context, proposalID string) (GetCuratorMeetingProposalSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getCuratorMeetingProposalSource, proposalID)
	var i GetCuratorMeetingProposalSourceRow
	err := row.Scan(
		&i.ProposalID,
		&i.ProposalRevision,
		&i.Summary,
		&i.ProposedAt,
		&i.MeetingID,
		&i.Agenda,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ProposalStatus,
		&i.MeetingStatus,
	)
	return i, err
}

const getEffectiveCuratorRule = `-- name: GetEffectiveCuratorRule :one
SELECT id, workspace_id, name, revision, enabled, created_at, created_by, event_sequence
FROM curator_rules
WHERE workspace_id = ?1 AND name = ?2
ORDER BY revision DESC
LIMIT 1
`

type GetEffectiveCuratorRuleParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetEffectiveCuratorRule(ctx context.Context, arg GetEffectiveCuratorRuleParams) (CuratorRule, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveCuratorRule, arg.WorkspaceID, arg.Name)
	var i CuratorRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Revision,
		&i.Enabled,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.EventSequence,
	)
	return i, err
}

const insertCuratorAutoAcceptance = `-- name: InsertCuratorAutoAcceptance :exec
INSERT INTO curator_auto_acceptances(
    id, workspace_id, project_id, rule_id, rule_name, rule_revision,
    derivation_id, knowledge_revision_id, authority_check_id,
    knowledge_event_sequence, event_sequence, created_at, actor_id, actor_type
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8,
    ?9, ?10,
    ?11, ?12, ?13,
    ?14
)
`

type InsertCuratorAutoAcceptanceParams struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	RuleID                 string `json:"rule_id"`
	RuleName               string `json:"rule_name"`
	RuleRevision           int64  `json:"rule_revision"`
	DerivationID           string `json:"derivation_id"`
	KnowledgeRevisionID    string `json:"knowledge_revision_id"`
	AuthorityCheckID       string `json:"authority_check_id"`
	KnowledgeEventSequence int64  `json:"knowledge_event_sequence"`
	EventSequence          int64  `json:"event_sequence"`
	CreatedAt              string `json:"created_at"`
	ActorID                string `json:"actor_id"`
	ActorType              string `json:"actor_type"`
}

func (q *Queries) InsertCuratorAutoAcceptance(ctx context.Context, arg InsertCuratorAutoAcceptanceParams) error {
	_, err := q.db.ExecContext(ctx, insertCuratorAutoAcceptance,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.RuleID,
		arg.RuleName,
		arg.RuleRevision,
		arg.DerivationID,
		arg.KnowledgeRevisionID,
		arg.AuthorityCheckID,
		arg.KnowledgeEventSequence,
		arg.EventSequence,
		arg.CreatedAt,
		arg.ActorID,
		arg.ActorType,
	)
	return err
}

const insertCuratorDerivation = `-- name: InsertCuratorDerivation :exec
INSERT INTO curator_derivations(
    id, workspace_id, project_id, rule_id, rule_name, rule_revision,
    source_type, source_id, source_revision, source_content_hash,
    knowledge_revision_id, output_content_hash, created_at, created_by,
    event_sequence
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8, ?9,
    ?10, ?11,
    ?12, ?13,
    ?14, ?15
)
`

type InsertCuratorDerivationParams struct {
	ID                  string `json:"id"`
	WorkspaceID         string `json:"workspace_id"`
	ProjectID           string `json:"project_id"`
	RuleID              string `json:"rule_id"`
	RuleName            string `json:"rule_name"`
	RuleRevision        int64  `json:"rule_revision"`
	SourceType          string `json:"source_type"`
	SourceID            string `json:"source_id"`
	SourceRevision      int64  `json:"source_revision"`
	SourceContentHash   string `json:"source_content_hash"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
	OutputContentHash   string `json:"output_content_hash"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
	EventSequence       int64  `json:"event_sequence"`
}

func (q *Queries) InsertCuratorDerivation(ctx context.Context, arg InsertCuratorDerivationParams) error {
	_, err := q.db.ExecContext(ctx, insertCuratorDerivation,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.RuleID,
		arg.RuleName,
		arg.RuleRevision,
		arg.SourceType,
		arg.SourceID,
		arg.SourceRevision,
		arg.SourceContentHash,
		arg.KnowledgeRevisionID,
		arg.OutputContentHash,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.EventSequence,
	)
	return err
}

const insertCuratorRule = `-- name: InsertCuratorRule :exec
INSERT INTO curator_rules(
    id, workspace_id, name, revision, enabled, created_at, created_by, event_sequence
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8
)
`

type InsertCuratorRuleParams struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Revision      int64  `json:"revision"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
	EventSequence int64  `json:"event_sequence"`
}

func (q *Queries) InsertCuratorRule(ctx context.Context, arg InsertCuratorRuleParams) error {
	_, err := q.db.ExecContext(ctx, insertCuratorRule,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Revision,
		arg.Enabled,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.EventSequence,
	)
	return err
}

const listCuratorEligibleRevisionIDs = `-- name: ListCuratorEligibleRevisionIDs :many
SELECT kr.id
FROM curator_derivations d
JOIN knowledge_revisions kr ON kr.id = d.knowledge_revision_id
JOIN knowledge_items ki ON ki.id = kr.item_id
WHERE d.workspace_id = ?1
  AND d.project_id = ?2
  AND d.rule_name = ?3
  AND d.event_sequence <= ?4
  AND ki.workspace_id = d.workspace_id
  AND ki.project_id = d.project_id
  AND kr.review_status = 'proposed'
  AND kr.currency_status = 'pending'
ORDER BY crewfold_timestamp_key(kr.proposed_at), kr.id
LIMIT ?5
`

type ListCuratorEligibleRevisionIDsParams struct {
	WorkspaceID      string `json:"workspace_id"`
	ProjectID        string `json:"project_id"`
	RuleName         string `json:"rule_name"`
	MaxEventSequence int64  `json:"max_event_sequence"`
	ResultLimit      int64  `json:"result_limit"`
}

func (q *Queries) ListCuratorEligibleRevisionIDs(ctx context.Context, arg ListCuratorEligibleRevisionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCuratorEligibleRevisionIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.RuleName,
		arg.MaxEventSequence,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuratorMeetingProposalCandidates = `-- name: ListCuratorMeetingProposalCandidates :many
SELECT mp.id AS proposal_id, mp.revision AS proposal_revision, mp.summary,
       mp.proposed_at, m.id AS meeting_id, m.agenda, m.workspace_id, m.project_id,
       mp.status AS proposal_status, m.status AS meeting_status
FROM meeting_proposals mp
JOIN meetings m ON m.id = mp.meeting_id
WHERE m.workspace_id = ?1
  AND m.project_id = ?2
  AND mp.status = 'accepted'
  AND m.status = 'concluded'
  AND NOT EXISTS (
      SELECT 1
      FROM curator_derivations d
      WHERE d.workspace_id = m.workspace_id
        AND d.rule_name = ?3
        AND d.source_type = 'meeting_proposal'
        AND d.source_id = mp.id
        AND d.source_revision = mp.revision
  )
ORDER BY
  CASE WHEN length(CAST(m.agenda AS BLOB)) BETWEEN 1 AND 160
             AND instr(m.agenda, char(0)) = 0
             AND crewfold_utf8_valid(m.agenda) = 1
             AND length(CAST(mp.summary AS BLOB)) BETWEEN 1 AND 2048
             AND instr(mp.summary, char(0)) = 0
             AND crewfold_utf8_valid(mp.summary) = 1
       THEN 0 ELSE 1 END,
  crewfold_timestamp_key(mp.proposed_at), mp.id
LIMIT ?4
`

type ListCuratorMeetingProposalCandidatesParams struct {
	WorkspaceID    string `json:"workspace_id"`
	ProjectID      string `json:"project_id"`
	RuleName       string `json:"rule_name"`
	CandidateLimit int64  `json:"candidate_limit"`
}

type ListCuratorMeetingProposalCandidatesRow struct {
	ProposalID       string `json:"proposal_id"`
	ProposalRevision int64  `json:"proposal_revision"`
	Summary          string `json:"summary"`
	ProposedAt       string `json:"proposed_at"`
	MeetingID        string `json:"meeting_id"`
	Agenda           string `json:"agenda"`
	WorkspaceID      string `json:"workspace_id"`
	ProjectID        string `json:"project_id"`
	ProposalStatus   string `json:"proposal_status"`
	MeetingStatus    string `json:"meeting_status"`
}

func (q *Queries) ListCuratorMeetingProposalCandidates(ctx context.Context, arg ListCuratorMeetingProposalCandidatesParams) ([]ListCuratorMeetingProposalCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCuratorMeetingProposalCandidates,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.RuleName,
		arg.CandidateLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCuratorMeetingProposalCandidatesRow{}
	for rows.Next() {
		var i ListCuratorMeetingProposalCandidatesRow
		if err := rows.Scan(
			&i.ProposalID,
			&i.ProposalRevision,
			&i.Summary,
			&i.ProposedAt,
			&i.MeetingID,
			&i.Agenda,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ProposalStatus,
			&i.MeetingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuratorQueueRevisionIDs = `-- name: ListCuratorQueueRevisionIDs :many
SELECT kr.id
FROM knowledge_revisions kr
JOIN knowledge_items ki ON ki.id = kr.item_id
WHERE ki.workspace_id = ?1
  AND ki.project_id = ?2
  AND kr.review_status = 'proposed'
  AND kr.currency_status = 'pending'
  AND (
      CAST(?3 AS TEXT) = ''
      OR crewfold_timestamp_key(kr.proposed_at) > crewfold_timestamp_key(CAST(?3 AS TEXT))
      OR (crewfold_timestamp_key(kr.proposed_at) = crewfold_timestamp_key(CAST(?3 AS TEXT))
          AND kr.id > ?4)
  )
ORDER BY crewfold_timestamp_key(kr.proposed_at), kr.id
LIMIT ?5
`

type ListCuratorQueueRevisionIDsParams struct {
	WorkspaceID     string `json:"workspace_id"`
	ProjectID       string `json:"project_id"`
	AfterProposedAt string `json:"after_proposed_at"`
	AfterRevisionID string `json:"after_revision_id"`
	ResultLimit     int64  `json:"result_limit"`
}

func (q *Queries) ListCuratorQueueRevisionIDs(ctx context.Context, arg ListCuratorQueueRevisionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCuratorQueueRevisionIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AfterProposedAt,
		arg.AfterRevisionID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
