// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package dbgen

import (
	"context"
)

const acceptKnowledgeRevision = `-- name: AcceptKnowledgeRevision :execrows
UPDATE knowledge_revisions
SET review_status = 'accepted', currency_status = 'current',
    state_revision = state_revision + 1,
    accepted_at = ?1, accepted_by = ?2,
    accepted_by_type = ?3, decision_note = ?4
WHERE id = ?5 AND state_revision = ?6
  AND review_status = 'proposed' AND currency_status = 'pending'
`

type AcceptKnowledgeRevisionParams struct {
	AcceptedAt            *string `json:"accepted_at"`
	AcceptedBy            *string `json:"accepted_by"`
	AcceptedByType        *string `json:"accepted_by_type"`
	DecisionNote          *string `json:"decision_note"`
	ID                    string  `json:"id"`
	ExpectedStateRevision int64   `json:"expected_state_revision"`
}

func (q *Queries) AcceptKnowledgeRevision(ctx context.Context, arg AcceptKnowledgeRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptKnowledgeRevision,
		arg.AcceptedAt,
		arg.AcceptedBy,
		arg.AcceptedByType,
		arg.DecisionNote,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findAcceptedKnowledgeSuccessor = `-- name: FindAcceptedKnowledgeSuccessor :one
SELECT successor.id
FROM knowledge_revisions successor
JOIN knowledge_items ki ON ki.id = successor.item_id
WHERE successor.supersedes_revision_id = ?1
  AND successor.review_status = 'accepted'
  AND ki.workspace_id = ?2
LIMIT 1
`

type FindAcceptedKnowledgeSuccessorParams struct {
	RevisionID  *string `json:"revision_id"`
	WorkspaceID string  `json:"workspace_id"`
}

func (q *Queries) FindAcceptedKnowledgeSuccessor(ctx context.Context, arg FindAcceptedKnowledgeSuccessorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findAcceptedKnowledgeSuccessor, arg.RevisionID, arg.WorkspaceID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findLiveKnowledgeSuccessor = `-- name: FindLiveKnowledgeSuccessor :one
SELECT id
FROM knowledge_revisions
WHERE supersedes_revision_id = ? AND review_status IN ('proposed', 'accepted')
LIMIT 1
`

func (q *Queries) FindLiveKnowledgeSuccessor(ctx context.Context, supersedesRevisionID *string) (string, error) {
	row := q.db.QueryRowContext(ctx, findLiveKnowledgeSuccessor, supersedesRevisionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getKnowledgeActorRunWorkspace = `-- name: GetKnowledgeActorRunWorkspace :one
SELECT workspace_id
FROM runs
WHERE id = ?
`

func (q *Queries) GetKnowledgeActorRunWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeActorRunWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getKnowledgeAuthorityCheckByKey = `-- name: GetKnowledgeAuthorityCheckByKey :one
SELECT id, workspace_id, revision_id, action, actor_id, actor_type,
       outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
FROM knowledge_authority_checks
WHERE actor_type = ?1 AND actor_id = ?2
  AND action = ?3 AND idempotency_key = ?4
`

type GetKnowledgeAuthorityCheckByKeyParams struct {
	ActorType      string `json:"actor_type"`
	ActorID        string `json:"actor_id"`
	Action         string `json:"action"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetKnowledgeAuthorityCheckByKey(ctx context.Context, arg GetKnowledgeAuthorityCheckByKeyParams) (KnowledgeAuthorityCheck, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeAuthorityCheckByKey,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.IdempotencyKey,
	)
	var i KnowledgeAuthorityCheck
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RevisionID,
		&i.Action,
		&i.ActorID,
		&i.ActorType,
		&i.Outcome,
		&i.Reason,
		&i.Note,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.EventSequence,
		&i.CreatedAt,
	)
	return i, err
}

const getKnowledgeRevision = `-- name: GetKnowledgeRevision :one
SELECT kr.id, kr.item_id, ki.workspace_id, ki.project_id,
       COALESCE(binding.task_id, ki.task_scope_id, '') AS task_scope_id, ki.type,
       kr.revision_number, kr.state_revision, kr.title, kr.body, kr.content_hash,
       kr.review_status, kr.currency_status, kr.confidence, kr.verification_status,
       kr.freshness_policy, kr.fresh_until, kr.supersedes_revision_id,
       kr.proposed_at, kr.proposed_by, kr.proposed_by_type,
       kr.accepted_at, kr.accepted_by, kr.accepted_by_type,
       kr.rejected_at, kr.rejected_by, kr.rejected_by_type,
       kr.stale_at, kr.stale_by, kr.stale_by_type,
       kr.decision_note, kr.stale_reason
FROM knowledge_revisions kr
JOIN knowledge_items ki ON ki.id = kr.item_id
LEFT JOIN knowledge_item_task_scopes binding ON binding.item_id = ki.id
WHERE kr.id = ?1 AND ki.workspace_id = ?2
`

type GetKnowledgeRevisionParams struct {
	RevisionID  string `json:"revision_id"`
	WorkspaceID string `json:"workspace_id"`
}

type GetKnowledgeRevisionRow struct {
	ID                   string  `json:"id"`
	ItemID               string  `json:"item_id"`
	WorkspaceID          string  `json:"workspace_id"`
	ProjectID            string  `json:"project_id"`
	TaskScopeID          string  `json:"task_scope_id"`
	Type                 string  `json:"type"`
	RevisionNumber       int64   `json:"revision_number"`
	StateRevision        int64   `json:"state_revision"`
	Title                string  `json:"title"`
	Body                 string  `json:"body"`
	ContentHash          string  `json:"content_hash"`
	ReviewStatus         string  `json:"review_status"`
	CurrencyStatus       string  `json:"currency_status"`
	Confidence           string  `json:"confidence"`
	VerificationStatus   string  `json:"verification_status"`
	FreshnessPolicy      string  `json:"freshness_policy"`
	FreshUntil           *string `json:"fresh_until"`
	SupersedesRevisionID *string `json:"supersedes_revision_id"`
	ProposedAt           string  `json:"proposed_at"`
	ProposedBy           string  `json:"proposed_by"`
	ProposedByType       string  `json:"proposed_by_type"`
	AcceptedAt           *string `json:"accepted_at"`
	AcceptedBy           *string `json:"accepted_by"`
	AcceptedByType       *string `json:"accepted_by_type"`
	RejectedAt           *string `json:"rejected_at"`
	RejectedBy           *string `json:"rejected_by"`
	RejectedByType       *string `json:"rejected_by_type"`
	StaleAt              *string `json:"stale_at"`
	StaleBy              *string `json:"stale_by"`
	StaleByType          *string `json:"stale_by_type"`
	DecisionNote         *string `json:"decision_note"`
	StaleReason          *string `json:"stale_reason"`
}

func (q *Queries) GetKnowledgeRevision(ctx context.Context, arg GetKnowledgeRevisionParams) (GetKnowledgeRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeRevision, arg.RevisionID, arg.WorkspaceID)
	var i GetKnowledgeRevisionRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskScopeID,
		&i.Type,
		&i.RevisionNumber,
		&i.StateRevision,
		&i.Title,
		&i.Body,
		&i.ContentHash,
		&i.ReviewStatus,
		&i.CurrencyStatus,
		&i.Confidence,
		&i.VerificationStatus,
		&i.FreshnessPolicy,
		&i.FreshUntil,
		&i.SupersedesRevisionID,
		&i.ProposedAt,
		&i.ProposedBy,
		&i.ProposedByType,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.AcceptedByType,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.RejectedByType,
		&i.StaleAt,
		&i.StaleBy,
		&i.StaleByType,
		&i.DecisionNote,
		&i.StaleReason,
	)
	return i, err
}

const getKnowledgeSourceMeeting = `-- name: GetKnowledgeSourceMeeting :one
SELECT workspace_id, project_id, revision, status
FROM meetings
WHERE id = ?
`

type GetKnowledgeSourceMeetingRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Revision    int64  `json:"revision"`
	Status      string `json:"status"`
}

func (q *Queries) GetKnowledgeSourceMeeting(ctx context.Context, id string) (GetKnowledgeSourceMeetingRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeSourceMeeting, id)
	var i GetKnowledgeSourceMeetingRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Revision,
		&i.Status,
	)
	return i, err
}

const getKnowledgeSourceMeetingProposal = `-- name: GetKnowledgeSourceMeetingProposal :one
SELECT m.workspace_id, m.project_id, mp.revision, mp.status AS proposal_status,
       m.status AS meeting_status
FROM meeting_proposals mp
JOIN meetings m ON m.id = mp.meeting_id
WHERE mp.id = ?
`

type GetKnowledgeSourceMeetingProposalRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ProjectID      string `json:"project_id"`
	Revision       int64  `json:"revision"`
	ProposalStatus string `json:"proposal_status"`
	MeetingStatus  string `json:"meeting_status"`
}

func (q *Queries) GetKnowledgeSourceMeetingProposal(ctx context.Context, id string) (GetKnowledgeSourceMeetingProposalRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeSourceMeetingProposal, id)
	var i GetKnowledgeSourceMeetingProposalRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Revision,
		&i.ProposalStatus,
		&i.MeetingStatus,
	)
	return i, err
}

const getKnowledgeSourceTask = `-- name: GetKnowledgeSourceTask :one
SELECT workspace_id, project_id, revision
FROM tasks
WHERE id = ?
`

type GetKnowledgeSourceTaskRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Revision    int64  `json:"revision"`
}

func (q *Queries) GetKnowledgeSourceTask(ctx context.Context, id string) (GetKnowledgeSourceTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeSourceTask, id)
	var i GetKnowledgeSourceTaskRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID, &i.Revision)
	return i, err
}

const getKnowledgeTaskScopeAnchor = `-- name: GetKnowledgeTaskScopeAnchor :one
SELECT task_id, workspace_id, project_id, created_at, created_by
FROM knowledge_task_scope_anchors
WHERE task_id = ?1
`

func (q *Queries) GetKnowledgeTaskScopeAnchor(ctx context.Context, taskID string) (KnowledgeTaskScopeAnchor, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeTaskScopeAnchor, taskID)
	var i KnowledgeTaskScopeAnchor
	err := row.Scan(
		&i.TaskID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertKnowledgeAuthorityCheck = `-- name: InsertKnowledgeAuthorityCheck :exec
INSERT INTO knowledge_authority_checks(
    id, workspace_id, revision_id, action, actor_id, actor_type,
    outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11,
    ?12, ?13
)
`

type InsertKnowledgeAuthorityCheckParams struct {
	ID             string  `json:"id"`
	WorkspaceID    string  `json:"workspace_id"`
	RevisionID     string  `json:"revision_id"`
	Action         string  `json:"action"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	Outcome        string  `json:"outcome"`
	Reason         string  `json:"reason"`
	Note           *string `json:"note"`
	IdempotencyKey string  `json:"idempotency_key"`
	RequestHash    string  `json:"request_hash"`
	EventSequence  int64   `json:"event_sequence"`
	CreatedAt      string  `json:"created_at"`
}

func (q *Queries) InsertKnowledgeAuthorityCheck(ctx context.Context, arg InsertKnowledgeAuthorityCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeAuthorityCheck,
		arg.ID,
		arg.WorkspaceID,
		arg.RevisionID,
		arg.Action,
		arg.ActorID,
		arg.ActorType,
		arg.Outcome,
		arg.Reason,
		arg.Note,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.EventSequence,
		arg.CreatedAt,
	)
	return err
}

const insertKnowledgeItem = `-- name: InsertKnowledgeItem :exec
INSERT INTO knowledge_items(
    id, workspace_id, project_id, task_scope_id, type,
    created_at, created_by, created_by_type
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8
)
`

type InsertKnowledgeItemParams struct {
	ID            string  `json:"id"`
	WorkspaceID   string  `json:"workspace_id"`
	ProjectID     string  `json:"project_id"`
	TaskScopeID   *string `json:"task_scope_id"`
	Type          string  `json:"type"`
	CreatedAt     string  `json:"created_at"`
	CreatedBy     string  `json:"created_by"`
	CreatedByType string  `json:"created_by_type"`
}

func (q *Queries) InsertKnowledgeItem(ctx context.Context, arg InsertKnowledgeItemParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskScopeID,
		arg.Type,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.CreatedByType,
	)
	return err
}

const insertKnowledgeItemTaskScope = `-- name: InsertKnowledgeItemTaskScope :exec
INSERT INTO knowledge_item_task_scopes(item_id, task_id)
VALUES (?1, ?2)
`

type InsertKnowledgeItemTaskScopeParams struct {
	ItemID string `json:"item_id"`
	TaskID string `json:"task_id"`
}

func (q *Queries) InsertKnowledgeItemTaskScope(ctx context.Context, arg InsertKnowledgeItemTaskScopeParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeItemTaskScope, arg.ItemID, arg.TaskID)
	return err
}

const insertKnowledgeRevision = `-- name: InsertKnowledgeRevision :exec
INSERT INTO knowledge_revisions(
    id, item_id, revision_number, state_revision, title, body, content_hash,
    review_status, currency_status, confidence, verification_status,
    freshness_policy, fresh_until, supersedes_revision_id,
    proposed_at, proposed_by, proposed_by_type
) VALUES (
    ?1, ?2, ?3, 1,
    ?4, ?5, ?6, 'proposed', 'pending',
    ?7, ?8, ?9,
    ?10, ?11,
    ?12, ?13, ?14
)
`

type InsertKnowledgeRevisionParams struct {
	ID                   string  `json:"id"`
	ItemID               string  `json:"item_id"`
	RevisionNumber       int64   `json:"revision_number"`
	Title                string  `json:"title"`
	Body                 string  `json:"body"`
	ContentHash          string  `json:"content_hash"`
	Confidence           string  `json:"confidence"`
	VerificationStatus   string  `json:"verification_status"`
	FreshnessPolicy      string  `json:"freshness_policy"`
	FreshUntil           *string `json:"fresh_until"`
	SupersedesRevisionID *string `json:"supersedes_revision_id"`
	ProposedAt           string  `json:"proposed_at"`
	ProposedBy           string  `json:"proposed_by"`
	ProposedByType       string  `json:"proposed_by_type"`
}

func (q *Queries) InsertKnowledgeRevision(ctx context.Context, arg InsertKnowledgeRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeRevision,
		arg.ID,
		arg.ItemID,
		arg.RevisionNumber,
		arg.Title,
		arg.Body,
		arg.ContentHash,
		arg.Confidence,
		arg.VerificationStatus,
		arg.FreshnessPolicy,
		arg.FreshUntil,
		arg.SupersedesRevisionID,
		arg.ProposedAt,
		arg.ProposedBy,
		arg.ProposedByType,
	)
	return err
}

const insertKnowledgeSource = `-- name: InsertKnowledgeSource :exec
INSERT INTO knowledge_sources(
    revision_id, ordinal, source_type, source_id, source_revision, role
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertKnowledgeSourceParams struct {
	RevisionID     string `json:"revision_id"`
	Ordinal        int64  `json:"ordinal"`
	SourceType     string `json:"source_type"`
	SourceID       string `json:"source_id"`
	SourceRevision int64  `json:"source_revision"`
	Role           string `json:"role"`
}

func (q *Queries) InsertKnowledgeSource(ctx context.Context, arg InsertKnowledgeSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeSource,
		arg.RevisionID,
		arg.Ordinal,
		arg.SourceType,
		arg.SourceID,
		arg.SourceRevision,
		arg.Role,
	)
	return err
}

const insertKnowledgeTaskScopeAnchor = `-- name: InsertKnowledgeTaskScopeAnchor :exec
INSERT INTO knowledge_task_scope_anchors(task_id, workspace_id, project_id, created_at, created_by)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(task_id) DO NOTHING
`

type InsertKnowledgeTaskScopeAnchorParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) InsertKnowledgeTaskScopeAnchor(ctx context.Context, arg InsertKnowledgeTaskScopeAnchorParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeTaskScopeAnchor,
		arg.TaskID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const listKnowledgeAuthorityChecks = `-- name: ListKnowledgeAuthorityChecks :many
SELECT id, workspace_id, revision_id, action, actor_id, actor_type,
       outcome, reason, note, idempotency_key, request_hash, event_sequence, created_at
FROM knowledge_authority_checks
WHERE workspace_id = ?1
  AND (?2 = '' OR revision_id = ?2)
ORDER BY created_at, id
`

type ListKnowledgeAuthorityChecksParams struct {
	WorkspaceID string      `json:"workspace_id"`
	RevisionID  interface{} `json:"revision_id"`
}

func (q *Queries) ListKnowledgeAuthorityChecks(ctx context.Context, arg ListKnowledgeAuthorityChecksParams) ([]KnowledgeAuthorityCheck, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeAuthorityChecks, arg.WorkspaceID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeAuthorityCheck{}
	for rows.Next() {
		var i KnowledgeAuthorityCheck
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RevisionID,
			&i.Action,
			&i.ActorID,
			&i.ActorType,
			&i.Outcome,
			&i.Reason,
			&i.Note,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.EventSequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeRevisionIDs = `-- name: ListKnowledgeRevisionIDs :many
SELECT kr.id
FROM knowledge_revisions kr
JOIN knowledge_items ki ON ki.id = kr.item_id
LEFT JOIN knowledge_item_task_scopes binding ON binding.item_id = ki.id
WHERE ki.workspace_id = ?1
  AND ki.project_id = ?2
  AND (?3 = '' OR COALESCE(binding.task_id, ki.task_scope_id) = ?3)
  AND (?4 = '' OR ki.type = ?4)
  AND (?5 = '' OR kr.review_status = ?5)
  AND (?6 = '' OR kr.currency_status = ?6)
ORDER BY kr.proposed_at DESC, kr.id DESC
LIMIT 200
`

type ListKnowledgeRevisionIDsParams struct {
	WorkspaceID    string      `json:"workspace_id"`
	ProjectID      string      `json:"project_id"`
	TaskScopeID    interface{} `json:"task_scope_id"`
	Type           interface{} `json:"type"`
	ReviewStatus   interface{} `json:"review_status"`
	CurrencyStatus interface{} `json:"currency_status"`
}

func (q *Queries) ListKnowledgeRevisionIDs(ctx context.Context, arg ListKnowledgeRevisionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeRevisionIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskScopeID,
		arg.Type,
		arg.ReviewStatus,
		arg.CurrencyStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeRevisionSources = `-- name: ListKnowledgeRevisionSources :many
SELECT revision_id, ordinal, source_type, source_id, source_revision, role
FROM knowledge_sources
WHERE revision_id = ?
ORDER BY ordinal
`

func (q *Queries) ListKnowledgeRevisionSources(ctx context.Context, revisionID string) ([]KnowledgeSource, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeRevisionSources, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeSource{}
	for rows.Next() {
		var i KnowledgeSource
		if err := rows.Scan(
			&i.RevisionID,
			&i.Ordinal,
			&i.SourceType,
			&i.SourceID,
			&i.SourceRevision,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKnowledgeRevisionStale = `-- name: MarkKnowledgeRevisionStale :execrows
UPDATE knowledge_revisions
SET currency_status = 'stale', state_revision = state_revision + 1,
    stale_at = ?1, stale_by = ?2,
    stale_by_type = ?3, stale_reason = ?4
WHERE id = ?5 AND state_revision = ?6
  AND review_status = 'accepted' AND currency_status = 'current'
`

type MarkKnowledgeRevisionStaleParams struct {
	StaleAt               *string `json:"stale_at"`
	StaleBy               *string `json:"stale_by"`
	StaleByType           *string `json:"stale_by_type"`
	StaleReason           *string `json:"stale_reason"`
	ID                    string  `json:"id"`
	ExpectedStateRevision int64   `json:"expected_state_revision"`
}

func (q *Queries) MarkKnowledgeRevisionStale(ctx context.Context, arg MarkKnowledgeRevisionStaleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markKnowledgeRevisionStale,
		arg.StaleAt,
		arg.StaleBy,
		arg.StaleByType,
		arg.StaleReason,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const maxKnowledgeRevisionNumber = `-- name: MaxKnowledgeRevisionNumber :one
SELECT CAST(COALESCE(MAX(revision_number), 0) AS INTEGER) AS revision_number
FROM knowledge_revisions
WHERE item_id = ?
`

func (q *Queries) MaxKnowledgeRevisionNumber(ctx context.Context, itemID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxKnowledgeRevisionNumber, itemID)
	var revision_number int64
	err := row.Scan(&revision_number)
	return revision_number, err
}

const rejectKnowledgeRevision = `-- name: RejectKnowledgeRevision :execrows
UPDATE knowledge_revisions
SET review_status = 'rejected', currency_status = 'pending',
    state_revision = state_revision + 1,
    rejected_at = ?1, rejected_by = ?2,
    rejected_by_type = ?3, decision_note = ?4
WHERE id = ?5 AND state_revision = ?6
  AND review_status = 'proposed' AND currency_status = 'pending'
`

type RejectKnowledgeRevisionParams struct {
	RejectedAt            *string `json:"rejected_at"`
	RejectedBy            *string `json:"rejected_by"`
	RejectedByType        *string `json:"rejected_by_type"`
	DecisionNote          *string `json:"decision_note"`
	ID                    string  `json:"id"`
	ExpectedStateRevision int64   `json:"expected_state_revision"`
}

func (q *Queries) RejectKnowledgeRevision(ctx context.Context, arg RejectKnowledgeRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rejectKnowledgeRevision,
		arg.RejectedAt,
		arg.RejectedBy,
		arg.RejectedByType,
		arg.DecisionNote,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeKnowledgeRevision = `-- name: SupersedeKnowledgeRevision :execrows
UPDATE knowledge_revisions
SET currency_status = 'superseded', state_revision = state_revision + 1
WHERE id = ?1 AND state_revision = ?2
  AND review_status = 'accepted' AND currency_status = 'current'
`

type SupersedeKnowledgeRevisionParams struct {
	ID                    string `json:"id"`
	ExpectedStateRevision int64  `json:"expected_state_revision"`
}

func (q *Queries) SupersedeKnowledgeRevision(ctx context.Context, arg SupersedeKnowledgeRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, supersedeKnowledgeRevision, arg.ID, arg.ExpectedStateRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
