// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meeting_actions.sql

package dbgen

import (
	"context"
)

const hasLiveTaskRun = `-- name: HasLiveTaskRun :one
SELECT EXISTS(
    SELECT 1 FROM runs
    WHERE task_id = ? AND status NOT IN ('stopped', 'lost', 'completed', 'start_failed', 'failed')
)
`

func (q *Queries) HasLiveTaskRun(ctx context.Context, taskID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasLiveTaskRun, taskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertMeetingAssignment = `-- name: InsertMeetingAssignment :exec
INSERT INTO task_assignments(
    id, task_id, agent_id, status, lease_expires_at, revision,
    created_at, updated_at, created_by, updated_by
) VALUES (
    ?1, ?2, ?3, 'active',
    ?4, 1, ?5, ?6,
    ?7, ?8
)
`

type InsertMeetingAssignmentParams struct {
	ID             string `json:"id"`
	TaskID         string `json:"task_id"`
	AgentID        string `json:"agent_id"`
	LeaseExpiresAt string `json:"lease_expires_at"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
	CreatedBy      string `json:"created_by"`
	UpdatedBy      string `json:"updated_by"`
}

func (q *Queries) InsertMeetingAssignment(ctx context.Context, arg InsertMeetingAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingAssignment,
		arg.ID,
		arg.TaskID,
		arg.AgentID,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const insertMeetingDependency = `-- name: InsertMeetingDependency :exec
INSERT INTO task_dependencies(task_id, depends_on_task_id, created_at, created_by)
VALUES (?1, ?2, ?3, ?4)
`

type InsertMeetingDependencyParams struct {
	TaskID          string `json:"task_id"`
	DependsOnTaskID string `json:"depends_on_task_id"`
	CreatedAt       string `json:"created_at"`
	CreatedBy       string `json:"created_by"`
}

func (q *Queries) InsertMeetingDependency(ctx context.Context, arg InsertMeetingDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingDependency,
		arg.TaskID,
		arg.DependsOnTaskID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertMeetingTaskRole = `-- name: InsertMeetingTaskRole :exec
INSERT INTO task_roles(task_id, agent_id, role, source_meeting_id, created_at, created_by)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
`

type InsertMeetingTaskRoleParams struct {
	TaskID          string `json:"task_id"`
	AgentID         string `json:"agent_id"`
	Role            string `json:"role"`
	SourceMeetingID string `json:"source_meeting_id"`
	CreatedAt       string `json:"created_at"`
	CreatedBy       string `json:"created_by"`
}

func (q *Queries) InsertMeetingTaskRole(ctx context.Context, arg InsertMeetingTaskRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingTaskRole,
		arg.TaskID,
		arg.AgentID,
		arg.Role,
		arg.SourceMeetingID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertSplitTask = `-- name: InsertSplitTask :exec
INSERT INTO tasks(
    id, workspace_id, project_id, objective_id, title, description, status, blocked_reason,
    priority, budget_tokens, budget_cost_cents, budget_time_seconds, revision,
    created_at, updated_at, created_by, updated_by
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, NULL,
    ?8, ?9, ?10,
    ?11, 1, ?12, ?13,
    ?14, ?15
)
`

type InsertSplitTaskParams struct {
	ID                string  `json:"id"`
	WorkspaceID       string  `json:"workspace_id"`
	ProjectID         string  `json:"project_id"`
	ObjectiveID       *string `json:"objective_id"`
	Title             string  `json:"title"`
	Description       *string `json:"description"`
	Status            string  `json:"status"`
	Priority          int64   `json:"priority"`
	BudgetTokens      int64   `json:"budget_tokens"`
	BudgetCostCents   int64   `json:"budget_cost_cents"`
	BudgetTimeSeconds int64   `json:"budget_time_seconds"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
	CreatedBy         string  `json:"created_by"`
	UpdatedBy         string  `json:"updated_by"`
}

func (q *Queries) InsertSplitTask(ctx context.Context, arg InsertSplitTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertSplitTask,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.BudgetTokens,
		arg.BudgetCostCents,
		arg.BudgetTimeSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const meetingDependencyExists = `-- name: MeetingDependencyExists :one
SELECT EXISTS(
    SELECT 1 FROM task_dependencies
    WHERE task_id = ?1 AND depends_on_task_id = ?2
)
`

type MeetingDependencyExistsParams struct {
	TaskID          string `json:"task_id"`
	DependsOnTaskID string `json:"depends_on_task_id"`
}

func (q *Queries) MeetingDependencyExists(ctx context.Context, arg MeetingDependencyExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, meetingDependencyExists, arg.TaskID, arg.DependsOnTaskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releaseMeetingClaim = `-- name: ReleaseMeetingClaim :exec
UPDATE work_claims
SET status = ?1, revision = ?2,
    updated_at = ?3, updated_by = ?4
WHERE id = ?5
`

type ReleaseMeetingClaimParams struct {
	Status    string `json:"status"`
	Revision  int64  `json:"revision"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	ID        string `json:"id"`
}

func (q *Queries) ReleaseMeetingClaim(ctx context.Context, arg ReleaseMeetingClaimParams) error {
	_, err := q.db.ExecContext(ctx, releaseMeetingClaim,
		arg.Status,
		arg.Revision,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const releaseTaskAssignmentsForMeeting = `-- name: ReleaseTaskAssignmentsForMeeting :exec
UPDATE task_assignments
SET status = 'released', revision = revision + 1,
    updated_at = ?1, updated_by = ?2
WHERE task_id = ?3 AND status = 'active'
`

type ReleaseTaskAssignmentsForMeetingParams struct {
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	TaskID    string `json:"task_id"`
}

func (q *Queries) ReleaseTaskAssignmentsForMeeting(ctx context.Context, arg ReleaseTaskAssignmentsForMeetingParams) error {
	_, err := q.db.ExecContext(ctx, releaseTaskAssignmentsForMeeting, arg.UpdatedAt, arg.UpdatedBy, arg.TaskID)
	return err
}

const setMeetingTaskAssigned = `-- name: SetMeetingTaskAssigned :exec
UPDATE tasks
SET status = 'assigned', revision = ?1,
    updated_at = ?2, updated_by = ?3
WHERE id = ?4
`

type SetMeetingTaskAssignedParams struct {
	Revision  int64  `json:"revision"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	ID        string `json:"id"`
}

func (q *Queries) SetMeetingTaskAssigned(ctx context.Context, arg SetMeetingTaskAssignedParams) error {
	_, err := q.db.ExecContext(ctx, setMeetingTaskAssigned,
		arg.Revision,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const setMeetingTaskCancelled = `-- name: SetMeetingTaskCancelled :exec
UPDATE tasks
SET status = 'cancelled', blocked_reason = NULL, revision = ?1,
    updated_at = ?2, updated_by = ?3
WHERE id = ?4
`

type SetMeetingTaskCancelledParams struct {
	Revision  int64  `json:"revision"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	ID        string `json:"id"`
}

func (q *Queries) SetMeetingTaskCancelled(ctx context.Context, arg SetMeetingTaskCancelledParams) error {
	_, err := q.db.ExecContext(ctx, setMeetingTaskCancelled,
		arg.Revision,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const touchMeetingTask = `-- name: TouchMeetingTask :exec
UPDATE tasks
SET revision = ?1, updated_at = ?2, updated_by = ?3
WHERE id = ?4
`

type TouchMeetingTaskParams struct {
	Revision  int64  `json:"revision"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
	ID        string `json:"id"`
}

func (q *Queries) TouchMeetingTask(ctx context.Context, arg TouchMeetingTaskParams) error {
	_, err := q.db.ExecContext(ctx, touchMeetingTask,
		arg.Revision,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
