// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetings.sql

package dbgen

import (
	"context"
)

const decideMeetingProposal = `-- name: DecideMeetingProposal :exec
UPDATE meeting_proposals
SET status = ?1, revision = revision + 1,
    decided_at = ?2, decision_note = ?3
WHERE id = ?4
`

type DecideMeetingProposalParams struct {
	Status       string  `json:"status"`
	DecidedAt    *string `json:"decided_at"`
	DecisionNote *string `json:"decision_note"`
	ID           string  `json:"id"`
}

func (q *Queries) DecideMeetingProposal(ctx context.Context, arg DecideMeetingProposalParams) error {
	_, err := q.db.ExecContext(ctx, decideMeetingProposal,
		arg.Status,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.ID,
	)
	return err
}

const findActiveMeetingForOverlap = `-- name: FindActiveMeetingForOverlap :one
SELECT id
FROM meetings
WHERE overlap_id = ? AND status NOT IN ('concluded', 'cancelled')
LIMIT 1
`

func (q *Queries) FindActiveMeetingForOverlap(ctx context.Context, overlapID string) (string, error) {
	row := q.db.QueryRowContext(ctx, findActiveMeetingForOverlap, overlapID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMeeting = `-- name: GetMeeting :one
SELECT id, workspace_id, project_id, overlap_id, agenda, facilitator_agent_id, policy,
       reviewer_agent_id, allowed_actions_json, status, frozen_input_json,
       frozen_input_hash, deadline_at, stalled_reason, revision,
       created_at, updated_at, created_by, updated_by
FROM meetings
WHERE id = ? AND workspace_id = ?
`

type GetMeetingParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMeeting(ctx context.Context, arg GetMeetingParams) (Meeting, error) {
	row := q.db.QueryRowContext(ctx, getMeeting, arg.ID, arg.WorkspaceID)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.OverlapID,
		&i.Agenda,
		&i.FacilitatorAgentID,
		&i.Policy,
		&i.ReviewerAgentID,
		&i.AllowedActionsJson,
		&i.Status,
		&i.FrozenInputJson,
		&i.FrozenInputHash,
		&i.DeadlineAt,
		&i.StalledReason,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getMeetingContribution = `-- name: GetMeetingContribution :one
SELECT id, meeting_id, agent_id, round, summary, evidence_json, submitted_at
FROM meeting_contributions
WHERE meeting_id = ? AND agent_id = ? AND round = ?
`

type GetMeetingContributionParams struct {
	MeetingID string `json:"meeting_id"`
	AgentID   string `json:"agent_id"`
	Round     string `json:"round"`
}

func (q *Queries) GetMeetingContribution(ctx context.Context, arg GetMeetingContributionParams) (MeetingContribution, error) {
	row := q.db.QueryRowContext(ctx, getMeetingContribution, arg.MeetingID, arg.AgentID, arg.Round)
	var i MeetingContribution
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AgentID,
		&i.Round,
		&i.Summary,
		&i.EvidenceJson,
		&i.SubmittedAt,
	)
	return i, err
}

const getMeetingProposal = `-- name: GetMeetingProposal :one
SELECT id, meeting_id, proposed_by, summary, status, revision, proposed_at,
       decided_at, decision_note
FROM meeting_proposals
WHERE meeting_id = ?
`

func (q *Queries) GetMeetingProposal(ctx context.Context, meetingID string) (MeetingProposal, error) {
	row := q.db.QueryRowContext(ctx, getMeetingProposal, meetingID)
	var i MeetingProposal
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.ProposedBy,
		&i.Summary,
		&i.Status,
		&i.Revision,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.DecisionNote,
	)
	return i, err
}

const insertMeeting = `-- name: InsertMeeting :exec
INSERT INTO meetings(
    id, workspace_id, project_id, overlap_id, agenda, facilitator_agent_id, policy,
    reviewer_agent_id, allowed_actions_json, status, frozen_input_json, frozen_input_hash,
    deadline_at, stalled_reason, revision, created_at, updated_at, created_by, updated_by
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11,
    ?12, ?13, ?14, ?15,
    ?16, ?17, ?18, ?19
)
`

type InsertMeetingParams struct {
	ID                 string  `json:"id"`
	WorkspaceID        string  `json:"workspace_id"`
	ProjectID          string  `json:"project_id"`
	OverlapID          string  `json:"overlap_id"`
	Agenda             string  `json:"agenda"`
	FacilitatorAgentID string  `json:"facilitator_agent_id"`
	Policy             string  `json:"policy"`
	ReviewerAgentID    *string `json:"reviewer_agent_id"`
	AllowedActionsJson string  `json:"allowed_actions_json"`
	Status             string  `json:"status"`
	FrozenInputJson    string  `json:"frozen_input_json"`
	FrozenInputHash    string  `json:"frozen_input_hash"`
	DeadlineAt         string  `json:"deadline_at"`
	StalledReason      *string `json:"stalled_reason"`
	Revision           int64   `json:"revision"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	CreatedBy          string  `json:"created_by"`
	UpdatedBy          string  `json:"updated_by"`
}

func (q *Queries) InsertMeeting(ctx context.Context, arg InsertMeetingParams) error {
	_, err := q.db.ExecContext(ctx, insertMeeting,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.OverlapID,
		arg.Agenda,
		arg.FacilitatorAgentID,
		arg.Policy,
		arg.ReviewerAgentID,
		arg.AllowedActionsJson,
		arg.Status,
		arg.FrozenInputJson,
		arg.FrozenInputHash,
		arg.DeadlineAt,
		arg.StalledReason,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const insertMeetingAction = `-- name: InsertMeetingAction :exec
INSERT INTO meeting_actions(
    id, proposal_id, ordinal, type, payload_json, status
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMeetingActionParams struct {
	ID          string `json:"id"`
	ProposalID  string `json:"proposal_id"`
	Ordinal     int64  `json:"ordinal"`
	Type        string `json:"type"`
	PayloadJson string `json:"payload_json"`
	Status      string `json:"status"`
}

func (q *Queries) InsertMeetingAction(ctx context.Context, arg InsertMeetingActionParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingAction,
		arg.ID,
		arg.ProposalID,
		arg.Ordinal,
		arg.Type,
		arg.PayloadJson,
		arg.Status,
	)
	return err
}

const insertMeetingContribution = `-- name: InsertMeetingContribution :exec
INSERT INTO meeting_contributions(
    id, meeting_id, agent_id, round, summary, evidence_json, submitted_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMeetingContributionParams struct {
	ID           string `json:"id"`
	MeetingID    string `json:"meeting_id"`
	AgentID      string `json:"agent_id"`
	Round        string `json:"round"`
	Summary      string `json:"summary"`
	EvidenceJson string `json:"evidence_json"`
	SubmittedAt  string `json:"submitted_at"`
}

func (q *Queries) InsertMeetingContribution(ctx context.Context, arg InsertMeetingContributionParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingContribution,
		arg.ID,
		arg.MeetingID,
		arg.AgentID,
		arg.Round,
		arg.Summary,
		arg.EvidenceJson,
		arg.SubmittedAt,
	)
	return err
}

const insertMeetingParticipant = `-- name: InsertMeetingParticipant :exec
INSERT INTO meeting_participants(meeting_id, agent_id, task_id, ordinal, status)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertMeetingParticipantParams struct {
	MeetingID string  `json:"meeting_id"`
	AgentID   string  `json:"agent_id"`
	TaskID    *string `json:"task_id"`
	Ordinal   int64   `json:"ordinal"`
	Status    string  `json:"status"`
}

func (q *Queries) InsertMeetingParticipant(ctx context.Context, arg InsertMeetingParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingParticipant,
		arg.MeetingID,
		arg.AgentID,
		arg.TaskID,
		arg.Ordinal,
		arg.Status,
	)
	return err
}

const insertMeetingProposal = `-- name: InsertMeetingProposal :exec
INSERT INTO meeting_proposals(
    id, meeting_id, proposed_by, summary, status, revision, proposed_at
) VALUES (?, ?, ?, ?, ?, 1, ?)
`

type InsertMeetingProposalParams struct {
	ID         string `json:"id"`
	MeetingID  string `json:"meeting_id"`
	ProposedBy string `json:"proposed_by"`
	Summary    string `json:"summary"`
	Status     string `json:"status"`
	ProposedAt string `json:"proposed_at"`
}

func (q *Queries) InsertMeetingProposal(ctx context.Context, arg InsertMeetingProposalParams) error {
	_, err := q.db.ExecContext(ctx, insertMeetingProposal,
		arg.ID,
		arg.MeetingID,
		arg.ProposedBy,
		arg.Summary,
		arg.Status,
		arg.ProposedAt,
	)
	return err
}

const listMeetingActions = `-- name: ListMeetingActions :many
SELECT id, proposal_id, ordinal, type, payload_json, status,
       result_entity_id, diagnostic, applied_at
FROM meeting_actions
WHERE proposal_id = ?
ORDER BY ordinal
`

func (q *Queries) ListMeetingActions(ctx context.Context, proposalID string) ([]MeetingAction, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingActions, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingAction{}
	for rows.Next() {
		var i MeetingAction
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.Ordinal,
			&i.Type,
			&i.PayloadJson,
			&i.Status,
			&i.ResultEntityID,
			&i.Diagnostic,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingContributions = `-- name: ListMeetingContributions :many
SELECT id, meeting_id, agent_id, round, summary, evidence_json, submitted_at
FROM meeting_contributions
WHERE meeting_id = ?
ORDER BY submitted_at, id
`

func (q *Queries) ListMeetingContributions(ctx context.Context, meetingID string) ([]MeetingContribution, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingContributions, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingContribution{}
	for rows.Next() {
		var i MeetingContribution
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.AgentID,
			&i.Round,
			&i.Summary,
			&i.EvidenceJson,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingParticipants = `-- name: ListMeetingParticipants :many
SELECT meeting_id, agent_id, task_id, ordinal, status
FROM meeting_participants
WHERE meeting_id = ?
ORDER BY ordinal
`

func (q *Queries) ListMeetingParticipants(ctx context.Context, meetingID string) ([]MeetingParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingParticipant{}
	for rows.Next() {
		var i MeetingParticipant
		if err := rows.Scan(
			&i.MeetingID,
			&i.AgentID,
			&i.TaskID,
			&i.Ordinal,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMeetingActionApplied = `-- name: MarkMeetingActionApplied :exec
UPDATE meeting_actions
SET status = ?1, result_entity_id = ?2, applied_at = ?3
WHERE id = ?4
`

type MarkMeetingActionAppliedParams struct {
	Status         string  `json:"status"`
	ResultEntityID *string `json:"result_entity_id"`
	AppliedAt      *string `json:"applied_at"`
	ID             string  `json:"id"`
}

func (q *Queries) MarkMeetingActionApplied(ctx context.Context, arg MarkMeetingActionAppliedParams) error {
	_, err := q.db.ExecContext(ctx, markMeetingActionApplied,
		arg.Status,
		arg.ResultEntityID,
		arg.AppliedAt,
		arg.ID,
	)
	return err
}

const maxEventSequence = `-- name: MaxEventSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER) AS sequence FROM events
`

func (q *Queries) MaxEventSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxEventSequence)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const updateMeetingParticipantStatus = `-- name: UpdateMeetingParticipantStatus :exec
UPDATE meeting_participants
SET status = ?
WHERE meeting_id = ? AND agent_id = ?
`

type UpdateMeetingParticipantStatusParams struct {
	Status    string `json:"status"`
	MeetingID string `json:"meeting_id"`
	AgentID   string `json:"agent_id"`
}

func (q *Queries) UpdateMeetingParticipantStatus(ctx context.Context, arg UpdateMeetingParticipantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMeetingParticipantStatus, arg.Status, arg.MeetingID, arg.AgentID)
	return err
}

const updateMeetingState = `-- name: UpdateMeetingState :exec
UPDATE meetings
SET status = ?1, stalled_reason = ?2,
    revision = ?3, updated_at = ?4, updated_by = ?5
WHERE id = ?6
`

type UpdateMeetingStateParams struct {
	Status        string  `json:"status"`
	StalledReason *string `json:"stalled_reason"`
	Revision      int64   `json:"revision"`
	UpdatedAt     string  `json:"updated_at"`
	UpdatedBy     string  `json:"updated_by"`
	ID            string  `json:"id"`
}

func (q *Queries) UpdateMeetingState(ctx context.Context, arg UpdateMeetingStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMeetingState,
		arg.Status,
		arg.StalledReason,
		arg.Revision,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
