// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type ContextDelta struct {
	ID                   string  `json:"id"`
	RunID                string  `json:"run_id"`
	ContextPacketID      string  `json:"context_packet_id"`
	Sequence             int64   `json:"sequence"`
	ParentDeltaID        *string `json:"parent_delta_id"`
	FromEventSequence    int64   `json:"from_event_sequence"`
	ThroughEventSequence int64   `json:"through_event_sequence"`
	DeltaJson            string  `json:"delta_json"`
	ContentHash          string  `json:"content_hash"`
	ByteSize             int64   `json:"byte_size"`
	BuiltEventSequence   int64   `json:"built_event_sequence"`
	CreatedAt            string  `json:"created_at"`
	CreatedBy            string  `json:"created_by"`
}

type ContextDeltaAcknowledgement struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	ContextPacketID string `json:"context_packet_id"`
	DeltaID         string `json:"delta_id"`
	Sequence        int64  `json:"sequence"`
	AcknowledgedAt  string `json:"acknowledged_at"`
	AcknowledgedBy  string `json:"acknowledged_by"`
	IdempotencyKey  string `json:"idempotency_key"`
	RequestHash     string `json:"request_hash"`
	EventSequence   int64  `json:"event_sequence"`
}

type CuratorAutoAcceptance struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	RuleID                 string `json:"rule_id"`
	RuleName               string `json:"rule_name"`
	RuleRevision           int64  `json:"rule_revision"`
	DerivationID           string `json:"derivation_id"`
	KnowledgeRevisionID    string `json:"knowledge_revision_id"`
	AuthorityCheckID       string `json:"authority_check_id"`
	KnowledgeEventSequence int64  `json:"knowledge_event_sequence"`
	EventSequence          int64  `json:"event_sequence"`
	CreatedAt              string `json:"created_at"`
	ActorID                string `json:"actor_id"`
	ActorType              string `json:"actor_type"`
}

type CuratorDerivation struct {
	ID                  string `json:"id"`
	WorkspaceID         string `json:"workspace_id"`
	ProjectID           string `json:"project_id"`
	RuleID              string `json:"rule_id"`
	RuleName            string `json:"rule_name"`
	RuleRevision        int64  `json:"rule_revision"`
	SourceType          string `json:"source_type"`
	SourceID            string `json:"source_id"`
	SourceRevision      int64  `json:"source_revision"`
	SourceContentHash   string `json:"source_content_hash"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
	OutputContentHash   string `json:"output_content_hash"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
	EventSequence       int64  `json:"event_sequence"`
}

type CuratorRule struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Revision      int64  `json:"revision"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
	EventSequence int64  `json:"event_sequence"`
}

type KnowledgeAuthorityCheck struct {
	ID             string  `json:"id"`
	WorkspaceID    string  `json:"workspace_id"`
	RevisionID     string  `json:"revision_id"`
	Action         string  `json:"action"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	Outcome        string  `json:"outcome"`
	Reason         string  `json:"reason"`
	Note           *string `json:"note"`
	IdempotencyKey string  `json:"idempotency_key"`
	RequestHash    string  `json:"request_hash"`
	EventSequence  int64   `json:"event_sequence"`
	CreatedAt      string  `json:"created_at"`
}

type KnowledgeContradiction struct {
	ID                           string  `json:"id"`
	WorkspaceID                  string  `json:"workspace_id"`
	ProjectID                    string  `json:"project_id"`
	LeftRevisionID               string  `json:"left_revision_id"`
	RightRevisionID              string  `json:"right_revision_id"`
	Status                       string  `json:"status"`
	StateRevision                int64   `json:"state_revision"`
	ReportNote                   string  `json:"report_note"`
	ReportedAt                   string  `json:"reported_at"`
	ReportedBy                   string  `json:"reported_by"`
	ReportedByType               string  `json:"reported_by_type"`
	DetectedEventSequence        int64   `json:"detected_event_sequence"`
	ConfirmedAt                  *string `json:"confirmed_at"`
	ConfirmedBy                  *string `json:"confirmed_by"`
	ConfirmedByType              *string `json:"confirmed_by_type"`
	ConfirmNote                  *string `json:"confirm_note"`
	ConfirmEventSequence         *int64  `json:"confirm_event_sequence"`
	DismissedAt                  *string `json:"dismissed_at"`
	DismissedBy                  *string `json:"dismissed_by"`
	DismissedByType              *string `json:"dismissed_by_type"`
	DismissNote                  *string `json:"dismiss_note"`
	DismissEventSequence         *int64  `json:"dismiss_event_sequence"`
	ResolutionReason             *string `json:"resolution_reason"`
	ResolvedAt                   *string `json:"resolved_at"`
	ResolvedBy                   *string `json:"resolved_by"`
	ResolvedByType               *string `json:"resolved_by_type"`
	ResolutionNote               *string `json:"resolution_note"`
	ResolutionEventSequence      *int64  `json:"resolution_event_sequence"`
	ResolutionCauseEventSequence *int64  `json:"resolution_cause_event_sequence"`
}

type KnowledgeContradictionAuthorityCheck struct {
	ID              string  `json:"id"`
	WorkspaceID     string  `json:"workspace_id"`
	ContradictionID string  `json:"contradiction_id"`
	Action          string  `json:"action"`
	ActorID         string  `json:"actor_id"`
	ActorType       string  `json:"actor_type"`
	Outcome         string  `json:"outcome"`
	Reason          string  `json:"reason"`
	Note            *string `json:"note"`
	IdempotencyKey  string  `json:"idempotency_key"`
	RequestHash     string  `json:"request_hash"`
	EventSequence   int64   `json:"event_sequence"`
	CreatedAt       string  `json:"created_at"`
}

type KnowledgeImport struct {
	ID                      string `json:"id"`
	BundleID                string `json:"bundle_id"`
	WorkspaceID             string `json:"workspace_id"`
	ProjectID               string `json:"project_id"`
	ContentSha256           string `json:"content_sha256"`
	RenderingSha256         string `json:"rendering_sha256"`
	ManifestJson            []byte `json:"manifest_json"`
	Markdown                []byte `json:"markdown"`
	IdempotencyKey          string `json:"idempotency_key"`
	RequestHash             string `json:"request_hash"`
	ImportedAt              string `json:"imported_at"`
	ImportedBy              string `json:"imported_by"`
	ImportedByType          string `json:"imported_by_type"`
	CreatedWorkspace        int64  `json:"created_workspace"`
	CreatedProject          int64  `json:"created_project"`
	CreatedTaskScopeAnchors int64  `json:"created_task_scope_anchors"`
	CompletedEventSequence  int64  `json:"completed_event_sequence"`
}

type KnowledgeSource struct {
	RevisionID     string `json:"revision_id"`
	Ordinal        int64  `json:"ordinal"`
	SourceType     string `json:"source_type"`
	SourceID       string `json:"source_id"`
	SourceRevision int64  `json:"source_revision"`
	Role           string `json:"role"`
}

type KnowledgeTaskScopeAnchor struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

type Meeting struct {
	ID                 string  `json:"id"`
	WorkspaceID        string  `json:"workspace_id"`
	ProjectID          string  `json:"project_id"`
	OverlapID          string  `json:"overlap_id"`
	Agenda             string  `json:"agenda"`
	FacilitatorAgentID string  `json:"facilitator_agent_id"`
	Policy             string  `json:"policy"`
	ReviewerAgentID    *string `json:"reviewer_agent_id"`
	AllowedActionsJson string  `json:"allowed_actions_json"`
	Status             string  `json:"status"`
	FrozenInputJson    string  `json:"frozen_input_json"`
	FrozenInputHash    string  `json:"frozen_input_hash"`
	DeadlineAt         string  `json:"deadline_at"`
	StalledReason      *string `json:"stalled_reason"`
	Revision           int64   `json:"revision"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	CreatedBy          string  `json:"created_by"`
	UpdatedBy          string  `json:"updated_by"`
}

type MeetingAction struct {
	ID             string  `json:"id"`
	ProposalID     string  `json:"proposal_id"`
	Ordinal        int64   `json:"ordinal"`
	Type           string  `json:"type"`
	PayloadJson    string  `json:"payload_json"`
	Status         string  `json:"status"`
	ResultEntityID *string `json:"result_entity_id"`
	Diagnostic     *string `json:"diagnostic"`
	AppliedAt      *string `json:"applied_at"`
}

type MeetingContribution struct {
	ID           string `json:"id"`
	MeetingID    string `json:"meeting_id"`
	AgentID      string `json:"agent_id"`
	Round        string `json:"round"`
	Summary      string `json:"summary"`
	EvidenceJson string `json:"evidence_json"`
	SubmittedAt  string `json:"submitted_at"`
}

type MeetingParticipant struct {
	MeetingID string  `json:"meeting_id"`
	AgentID   string  `json:"agent_id"`
	TaskID    *string `json:"task_id"`
	Ordinal   int64   `json:"ordinal"`
	Status    string  `json:"status"`
}

type MeetingProposal struct {
	ID           string  `json:"id"`
	MeetingID    string  `json:"meeting_id"`
	ProposedBy   string  `json:"proposed_by"`
	Summary      string  `json:"summary"`
	Status       string  `json:"status"`
	Revision     int64   `json:"revision"`
	ProposedAt   string  `json:"proposed_at"`
	DecidedAt    *string `json:"decided_at"`
	DecisionNote *string `json:"decision_note"`
}

type RunContextDeltaState struct {
	RunID                   string  `json:"run_id"`
	ContextPacketID         string  `json:"context_packet_id"`
	Status                  string  `json:"status"`
	Revision                int64   `json:"revision"`
	ScanEventSequence       int64   `json:"scan_event_sequence"`
	LastSequence            int64   `json:"last_sequence"`
	LastDeltaID             *string `json:"last_delta_id"`
	PendingDeltaID          *string `json:"pending_delta_id"`
	LastAcknowledgedDeltaID *string `json:"last_acknowledged_delta_id"`
	DeltaCount              int64   `json:"delta_count"`
	CumulativeByteSize      int64   `json:"cumulative_byte_size"`
	RebaseReason            *string `json:"rebase_reason"`
	RebaseEventSequence     *int64  `json:"rebase_event_sequence"`
	CreatedAt               string  `json:"created_at"`
	UpdatedAt               string  `json:"updated_at"`
}

type ThreadParticipant struct {
	ID                 string `json:"id"`
	ThreadID           string `json:"thread_id"`
	WorkspaceID        string `json:"workspace_id"`
	AgentID            string `json:"agent_id"`
	AgentName          string `json:"agent_name"`
	TaskID             string `json:"task_id"`
	TaskTitle          string `json:"task_title"`
	ProjectID          string `json:"project_id"`
	ProjectName        string `json:"project_name"`
	AssignmentID       string `json:"assignment_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
	AgentRevision      int64  `json:"agent_revision"`
	TaskRevision       int64  `json:"task_revision"`
	Ordinal            int64  `json:"ordinal"`
	Status             string `json:"status"`
	InvitedAt          string `json:"invited_at"`
	InvitedBy          string `json:"invited_by"`
}
