// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type Agent struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	Name           string `json:"name"`
	Role           string `json:"role"`
	Provider       string `json:"provider"`
	Runtime        string `json:"runtime"`
	Enabled        int64  `json:"enabled"`
	MaxConcurrency int64  `json:"max_concurrency"`
	Revision       int64  `json:"revision"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
	CreatedBy      string `json:"created_by"`
	UpdatedBy      string `json:"updated_by"`
}

type CheckArtifact struct {
	ID            string `json:"id"`
	CheckResultID string `json:"check_result_id"`
	Kind          string `json:"kind"`
	ContentSha256 string `json:"content_sha256"`
	CapturedBytes int64  `json:"captured_bytes"`
	OmittedBytes  int64  `json:"omitted_bytes"`
	Truncated     int64  `json:"truncated"`
	CreatedAt     string `json:"created_at"`
}

type CheckJob struct {
	ID             string  `json:"id"`
	CheckRunID     string  `json:"check_run_id"`
	Status         string  `json:"status"`
	AvailableAt    string  `json:"available_at"`
	LeaseExpiresAt *string `json:"lease_expires_at"`
	Attempts       int64   `json:"attempts"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

type CheckLaunchReceipt struct {
	ID                         string  `json:"id"`
	CheckRunID                 string  `json:"check_run_id"`
	CheckJobID                 string  `json:"check_job_id"`
	OperationID                string  `json:"operation_id"`
	EffectiveSpecSha256        string  `json:"effective_spec_sha256"`
	EffectiveWorkingDirectory  string  `json:"effective_working_directory"`
	Launchable                 int64   `json:"launchable"`
	PreflightFailureCode       *string `json:"preflight_failure_code"`
	PreflightFailureDiagnostic *string `json:"preflight_failure_diagnostic"`
	DefinitionSha256           string  `json:"definition_sha256"`
	SourceType                 string  `json:"source_type"`
	SourceActorID              string  `json:"source_actor_id"`
	SourceAgentID              *string `json:"source_agent_id"`
	SourceAgentRevision        *int64  `json:"source_agent_revision"`
	SourceRunID                *string `json:"source_run_id"`
	SourceGrantID              *string `json:"source_grant_id"`
	SourceGrantRevision        *int64  `json:"source_grant_revision"`
	ObservationAvailable       int64   `json:"observation_available"`
	RepositoryID               string  `json:"repository_id"`
	ObjectFormat               string  `json:"object_format"`
	CheckoutID                 string  `json:"checkout_id"`
	Branch                     *string `json:"branch"`
	HeadCommit                 *string `json:"head_commit"`
	Dirty                      int64   `json:"dirty"`
	DirtyPathsJson             string  `json:"dirty_paths_json"`
	ObservedAt                 string  `json:"observed_at"`
	DiagnosticCode             *string `json:"diagnostic_code"`
	Diagnostic                 *string `json:"diagnostic"`
	CreatedAt                  string  `json:"created_at"`
	CreatedBy                  string  `json:"created_by"`
}

type CheckPolicy struct {
	WorkspaceID                 string  `json:"workspace_id"`
	ProjectID                   string  `json:"project_id"`
	RepairProposalsEnabled      int64   `json:"repair_proposals_enabled"`
	RepairLaunchProfileID       *string `json:"repair_launch_profile_id"`
	RepairLaunchProfileRevision *int64  `json:"repair_launch_profile_revision"`
	MaxOpenRepairProposals      int64   `json:"max_open_repair_proposals"`
	Revision                    int64   `json:"revision"`
	CreatedAt                   string  `json:"created_at"`
	UpdatedAt                   string  `json:"updated_at"`
	CreatedBy                   string  `json:"created_by"`
	UpdatedBy                   string  `json:"updated_by"`
}

type CheckRepairDecision struct {
	ID               string  `json:"id"`
	RepairProposalID string  `json:"repair_proposal_id"`
	Decision         string  `json:"decision"`
	ProposalRevision int64   `json:"proposal_revision"`
	Note             *string `json:"note"`
	CreatedAt        string  `json:"created_at"`
	CreatedBy        string  `json:"created_by"`
}

type CheckRepairEffect struct {
	ID                 string `json:"id"`
	RepairProposalID   string `json:"repair_proposal_id"`
	RepairTaskID       string `json:"repair_task_id"`
	SchedulingIntentID string `json:"scheduling_intent_id"`
	CreatedAt          string `json:"created_at"`
}

type CheckRepairProposal struct {
	ID                          string `json:"id"`
	WorkspaceID                 string `json:"workspace_id"`
	ProjectID                   string `json:"project_id"`
	ObjectiveID                 string `json:"objective_id"`
	ObjectiveRevision           int64  `json:"objective_revision"`
	TaskID                      string `json:"task_id"`
	TaskRevision                int64  `json:"task_revision"`
	RequirementID               string `json:"requirement_id"`
	RequirementRevision         int64  `json:"requirement_revision"`
	CheckResultID               string `json:"check_result_id"`
	FreshnessRevision           int64  `json:"freshness_revision"`
	SourceRepositoryID          string `json:"source_repository_id"`
	SourceCheckoutID            string `json:"source_checkout_id"`
	SourceHeadCommit            string `json:"source_head_commit"`
	PolicyRevision              int64  `json:"policy_revision"`
	RepairLaunchProfileID       string `json:"repair_launch_profile_id"`
	RepairLaunchProfileRevision int64  `json:"repair_launch_profile_revision"`
	SourceRunID                 string `json:"source_run_id"`
	SourceAgentID               string `json:"source_agent_id"`
	SourceAgentRevision         int64  `json:"source_agent_revision"`
	SourceGrantID               string `json:"source_grant_id"`
	SourceGrantRevision         int64  `json:"source_grant_revision"`
	Rationale                   string `json:"rationale"`
	RepairTaskTitle             string `json:"repair_task_title"`
	RepairTaskDescription       string `json:"repair_task_description"`
	RepairTaskPriority          int64  `json:"repair_task_priority"`
	RepairBudgetTokens          int64  `json:"repair_budget_tokens"`
	RepairBudgetCostCents       int64  `json:"repair_budget_cost_cents"`
	RepairBudgetTimeSeconds     int64  `json:"repair_budget_time_seconds"`
	RecipeSha256                string `json:"recipe_sha256"`
	Status                      string `json:"status"`
	Revision                    int64  `json:"revision"`
	CreatedAt                   string `json:"created_at"`
	UpdatedAt                   string `json:"updated_at"`
	CreatedBy                   string `json:"created_by"`
	UpdatedBy                   string `json:"updated_by"`
}

type CheckRequirementEvidence struct {
	ID                  string `json:"id"`
	RequirementID       string `json:"requirement_id"`
	RequirementRevision int64  `json:"requirement_revision"`
	CheckResultID       string `json:"check_result_id"`
	FreshnessRevision   int64  `json:"freshness_revision"`
	Class               string `json:"class"`
	Effect              string `json:"effect"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
}

type CheckResult struct {
	ID                        string  `json:"id"`
	CheckRunID                string  `json:"check_run_id"`
	RequirementID             string  `json:"requirement_id"`
	RequirementRevision       int64   `json:"requirement_revision"`
	DefinitionID              string  `json:"definition_id"`
	DefinitionContentRevision int64   `json:"definition_content_revision"`
	Outcome                   string  `json:"outcome"`
	ExitCode                  *int64  `json:"exit_code"`
	Forced                    int64   `json:"forced"`
	DiagnosticCode            *string `json:"diagnostic_code"`
	Diagnostic                *string `json:"diagnostic"`
	ObservationAvailable      int64   `json:"observation_available"`
	RepositoryID              string  `json:"repository_id"`
	ObjectFormat              string  `json:"object_format"`
	CheckoutID                string  `json:"checkout_id"`
	Branch                    *string `json:"branch"`
	HeadCommit                *string `json:"head_commit"`
	Dirty                     int64   `json:"dirty"`
	DirtyPathsJson            string  `json:"dirty_paths_json"`
	ObservedAt                string  `json:"observed_at"`
	ObservationDiagnosticCode *string `json:"observation_diagnostic_code"`
	ObservationDiagnostic     *string `json:"observation_diagnostic"`
	CreatedAt                 string  `json:"created_at"`
	CreatedBy                 string  `json:"created_by"`
}

type CheckResultFreshness struct {
	ID                   string  `json:"id"`
	CheckResultID        string  `json:"check_result_id"`
	Revision             int64   `json:"revision"`
	Status               string  `json:"status"`
	Reason               string  `json:"reason"`
	InitiallyEligible    int64   `json:"initially_eligible"`
	EverStale            int64   `json:"ever_stale"`
	ObservationAvailable int64   `json:"observation_available"`
	RepositoryID         string  `json:"repository_id"`
	ObjectFormat         string  `json:"object_format"`
	CheckoutID           string  `json:"checkout_id"`
	Branch               *string `json:"branch"`
	HeadCommit           *string `json:"head_commit"`
	Dirty                int64   `json:"dirty"`
	DirtyPathsJson       string  `json:"dirty_paths_json"`
	ObservedAt           string  `json:"observed_at"`
	DiagnosticCode       *string `json:"diagnostic_code"`
	Diagnostic           *string `json:"diagnostic"`
	CreatedAt            string  `json:"created_at"`
	CreatedBy            string  `json:"created_by"`
}

type CheckRoute struct {
	ID                        string  `json:"id"`
	WorkspaceID               string  `json:"workspace_id"`
	ProjectID                 string  `json:"project_id"`
	DefinitionID              *string `json:"definition_id"`
	DefinitionContentRevision *int64  `json:"definition_content_revision"`
	Trigger                   string  `json:"trigger"`
	Duty                      string  `json:"duty"`
	AgentID                   string  `json:"agent_id"`
	AgentRevision             int64   `json:"agent_revision"`
	Status                    string  `json:"status"`
	Revision                  int64   `json:"revision"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
	CreatedBy                 string  `json:"created_by"`
	UpdatedBy                 string  `json:"updated_by"`
}

type ContextDelta struct {
	ID                   string  `json:"id"`
	RunID                string  `json:"run_id"`
	ContextPacketID      string  `json:"context_packet_id"`
	Sequence             int64   `json:"sequence"`
	ParentDeltaID        *string `json:"parent_delta_id"`
	FromEventSequence    int64   `json:"from_event_sequence"`
	ThroughEventSequence int64   `json:"through_event_sequence"`
	DeltaJson            string  `json:"delta_json"`
	ContentHash          string  `json:"content_hash"`
	ByteSize             int64   `json:"byte_size"`
	BuiltEventSequence   int64   `json:"built_event_sequence"`
	CreatedAt            string  `json:"created_at"`
	CreatedBy            string  `json:"created_by"`
}

type ContextDeltaAcknowledgement struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	ContextPacketID string `json:"context_packet_id"`
	DeltaID         string `json:"delta_id"`
	Sequence        int64  `json:"sequence"`
	AcknowledgedAt  string `json:"acknowledged_at"`
	AcknowledgedBy  string `json:"acknowledged_by"`
	IdempotencyKey  string `json:"idempotency_key"`
	RequestHash     string `json:"request_hash"`
	EventSequence   int64  `json:"event_sequence"`
}

type CuratorAutoAcceptance struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	RuleID                 string `json:"rule_id"`
	RuleName               string `json:"rule_name"`
	RuleRevision           int64  `json:"rule_revision"`
	DerivationID           string `json:"derivation_id"`
	KnowledgeRevisionID    string `json:"knowledge_revision_id"`
	AuthorityCheckID       string `json:"authority_check_id"`
	KnowledgeEventSequence int64  `json:"knowledge_event_sequence"`
	EventSequence          int64  `json:"event_sequence"`
	CreatedAt              string `json:"created_at"`
	ActorID                string `json:"actor_id"`
	ActorType              string `json:"actor_type"`
}

type CuratorDerivation struct {
	ID                  string `json:"id"`
	WorkspaceID         string `json:"workspace_id"`
	ProjectID           string `json:"project_id"`
	RuleID              string `json:"rule_id"`
	RuleName            string `json:"rule_name"`
	RuleRevision        int64  `json:"rule_revision"`
	SourceType          string `json:"source_type"`
	SourceID            string `json:"source_id"`
	SourceRevision      int64  `json:"source_revision"`
	SourceContentHash   string `json:"source_content_hash"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
	OutputContentHash   string `json:"output_content_hash"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
	EventSequence       int64  `json:"event_sequence"`
}

type CuratorRule struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Revision      int64  `json:"revision"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
	EventSequence int64  `json:"event_sequence"`
}

type DeliverableCommitment struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	ObjectiveID            string `json:"objective_id"`
	TaskID                 string `json:"task_id"`
	CommitmentKey          string `json:"commitment_key"`
	Title                  string `json:"title"`
	Description            string `json:"description"`
	AcceptanceCriteriaJson string `json:"acceptance_criteria_json"`
	ContentJson            string `json:"content_json"`
	ContentSha256          string `json:"content_sha256"`
	CreatedAt              string `json:"created_at"`
	CreatedBy              string `json:"created_by"`
}

type Event struct {
	Sequence       int64   `json:"sequence"`
	EventID        string  `json:"event_id"`
	Type           string  `json:"type"`
	SchemaVersion  int64   `json:"schema_version"`
	OccurredAt     string  `json:"occurred_at"`
	RecordedAt     string  `json:"recorded_at"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	WorkspaceID    string  `json:"workspace_id"`
	EntityType     string  `json:"entity_type"`
	EntityID       string  `json:"entity_id"`
	EntityRevision int64   `json:"entity_revision"`
	CorrelationID  string  `json:"correlation_id"`
	CausationID    *string `json:"causation_id"`
	DataJson       string  `json:"data_json"`
}

type KnowledgeAuthorityCheck struct {
	ID             string  `json:"id"`
	WorkspaceID    string  `json:"workspace_id"`
	RevisionID     string  `json:"revision_id"`
	Action         string  `json:"action"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	Outcome        string  `json:"outcome"`
	Reason         string  `json:"reason"`
	Note           *string `json:"note"`
	IdempotencyKey string  `json:"idempotency_key"`
	RequestHash    string  `json:"request_hash"`
	EventSequence  int64   `json:"event_sequence"`
	CreatedAt      string  `json:"created_at"`
}

type KnowledgeContradiction struct {
	ID                           string  `json:"id"`
	WorkspaceID                  string  `json:"workspace_id"`
	ProjectID                    string  `json:"project_id"`
	LeftRevisionID               string  `json:"left_revision_id"`
	RightRevisionID              string  `json:"right_revision_id"`
	Status                       string  `json:"status"`
	StateRevision                int64   `json:"state_revision"`
	ReportNote                   string  `json:"report_note"`
	ReportedAt                   string  `json:"reported_at"`
	ReportedBy                   string  `json:"reported_by"`
	ReportedByType               string  `json:"reported_by_type"`
	DetectedEventSequence        int64   `json:"detected_event_sequence"`
	ConfirmedAt                  *string `json:"confirmed_at"`
	ConfirmedBy                  *string `json:"confirmed_by"`
	ConfirmedByType              *string `json:"confirmed_by_type"`
	ConfirmNote                  *string `json:"confirm_note"`
	ConfirmEventSequence         *int64  `json:"confirm_event_sequence"`
	DismissedAt                  *string `json:"dismissed_at"`
	DismissedBy                  *string `json:"dismissed_by"`
	DismissedByType              *string `json:"dismissed_by_type"`
	DismissNote                  *string `json:"dismiss_note"`
	DismissEventSequence         *int64  `json:"dismiss_event_sequence"`
	ResolutionReason             *string `json:"resolution_reason"`
	ResolvedAt                   *string `json:"resolved_at"`
	ResolvedBy                   *string `json:"resolved_by"`
	ResolvedByType               *string `json:"resolved_by_type"`
	ResolutionNote               *string `json:"resolution_note"`
	ResolutionEventSequence      *int64  `json:"resolution_event_sequence"`
	ResolutionCauseEventSequence *int64  `json:"resolution_cause_event_sequence"`
}

type KnowledgeContradictionAuthorityCheck struct {
	ID              string  `json:"id"`
	WorkspaceID     string  `json:"workspace_id"`
	ContradictionID string  `json:"contradiction_id"`
	Action          string  `json:"action"`
	ActorID         string  `json:"actor_id"`
	ActorType       string  `json:"actor_type"`
	Outcome         string  `json:"outcome"`
	Reason          string  `json:"reason"`
	Note            *string `json:"note"`
	IdempotencyKey  string  `json:"idempotency_key"`
	RequestHash     string  `json:"request_hash"`
	EventSequence   int64   `json:"event_sequence"`
	CreatedAt       string  `json:"created_at"`
}

type KnowledgeImport struct {
	ID                      string `json:"id"`
	BundleID                string `json:"bundle_id"`
	WorkspaceID             string `json:"workspace_id"`
	ProjectID               string `json:"project_id"`
	ContentSha256           string `json:"content_sha256"`
	RenderingSha256         string `json:"rendering_sha256"`
	ManifestJson            []byte `json:"manifest_json"`
	Markdown                []byte `json:"markdown"`
	IdempotencyKey          string `json:"idempotency_key"`
	RequestHash             string `json:"request_hash"`
	ImportedAt              string `json:"imported_at"`
	ImportedBy              string `json:"imported_by"`
	ImportedByType          string `json:"imported_by_type"`
	CreatedWorkspace        int64  `json:"created_workspace"`
	CreatedProject          int64  `json:"created_project"`
	CreatedTaskScopeAnchors int64  `json:"created_task_scope_anchors"`
	CompletedEventSequence  int64  `json:"completed_event_sequence"`
}

type KnowledgeSource struct {
	RevisionID     string `json:"revision_id"`
	Ordinal        int64  `json:"ordinal"`
	SourceType     string `json:"source_type"`
	SourceID       string `json:"source_id"`
	SourceRevision int64  `json:"source_revision"`
	Role           string `json:"role"`
}

type KnowledgeTaskScopeAnchor struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

type ManagementBriefing struct {
	ID                   string  `json:"id"`
	Revision             int64   `json:"revision"`
	WorkspaceID          string  `json:"workspace_id"`
	ScopeType            string  `json:"scope_type"`
	ScopeID              string  `json:"scope_id"`
	EventCursor          int64   `json:"event_cursor"`
	CutoffEventSequence  int64   `json:"cutoff_event_sequence"`
	CheckpointID         string  `json:"checkpoint_id"`
	SinceEventSequence   int64   `json:"since_event_sequence"`
	EvaluatedAt          string  `json:"evaluated_at"`
	CaughtUp             int64   `json:"caught_up"`
	UnknownEventType     *string `json:"unknown_event_type"`
	UnknownEventSequence *int64  `json:"unknown_event_sequence"`
	ContentJson          string  `json:"content_json"`
	ContentSha256        string  `json:"content_sha256"`
	ByteSize             int64   `json:"byte_size"`
	CreatedAt            string  `json:"created_at"`
}

type ManagementBriefingClaim struct {
	BriefingID          string  `json:"briefing_id"`
	Ordinal             int64   `json:"ordinal"`
	ClaimID             string  `json:"claim_id"`
	SemanticKey         string  `json:"semantic_key"`
	Kind                string  `json:"kind"`
	Urgency             string  `json:"urgency"`
	Summary             string  `json:"summary"`
	Status              string  `json:"status"`
	ProjectID           *string `json:"project_id"`
	SourceEventSequence int64   `json:"source_event_sequence"`
	ClaimJson           string  `json:"claim_json"`
}

type ManagementBriefingClaimSource struct {
	BriefingID       string `json:"briefing_id"`
	ClaimID          string `json:"claim_id"`
	Ordinal          int64  `json:"ordinal"`
	EntityType       string `json:"entity_type"`
	EntityID         string `json:"entity_id"`
	EntityRevision   int64  `json:"entity_revision"`
	ContentSha256    string `json:"content_sha256"`
	EventSequence    int64  `json:"event_sequence"`
	EvidenceClass    string `json:"evidence_class"`
	EvidenceEffect   string `json:"evidence_effect"`
	PinnedFreshness  string `json:"pinned_freshness"`
	CurrentFreshness string `json:"current_freshness"`
}

type ManagementBriefingReceipt struct {
	BriefingID  string `json:"briefing_id"`
	ClaimCount  int64  `json:"claim_count"`
	SourceCount int64  `json:"source_count"`
	SealedAt    string `json:"sealed_at"`
}

type Meeting struct {
	ID                 string  `json:"id"`
	WorkspaceID        string  `json:"workspace_id"`
	ProjectID          string  `json:"project_id"`
	OverlapID          string  `json:"overlap_id"`
	Agenda             string  `json:"agenda"`
	FacilitatorAgentID string  `json:"facilitator_agent_id"`
	Policy             string  `json:"policy"`
	ReviewerAgentID    *string `json:"reviewer_agent_id"`
	AllowedActionsJson string  `json:"allowed_actions_json"`
	Status             string  `json:"status"`
	FrozenInputJson    string  `json:"frozen_input_json"`
	FrozenInputHash    string  `json:"frozen_input_hash"`
	DeadlineAt         string  `json:"deadline_at"`
	StalledReason      *string `json:"stalled_reason"`
	Revision           int64   `json:"revision"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	CreatedBy          string  `json:"created_by"`
	UpdatedBy          string  `json:"updated_by"`
}

type MeetingAction struct {
	ID             string  `json:"id"`
	ProposalID     string  `json:"proposal_id"`
	Ordinal        int64   `json:"ordinal"`
	Type           string  `json:"type"`
	PayloadJson    string  `json:"payload_json"`
	Status         string  `json:"status"`
	ResultEntityID *string `json:"result_entity_id"`
	Diagnostic     *string `json:"diagnostic"`
	AppliedAt      *string `json:"applied_at"`
}

type MeetingContribution struct {
	ID           string `json:"id"`
	MeetingID    string `json:"meeting_id"`
	AgentID      string `json:"agent_id"`
	Round        string `json:"round"`
	Summary      string `json:"summary"`
	EvidenceJson string `json:"evidence_json"`
	SubmittedAt  string `json:"submitted_at"`
}

type MeetingParticipant struct {
	MeetingID string  `json:"meeting_id"`
	AgentID   string  `json:"agent_id"`
	TaskID    *string `json:"task_id"`
	Ordinal   int64   `json:"ordinal"`
	Status    string  `json:"status"`
}

type MeetingProposal struct {
	ID           string  `json:"id"`
	MeetingID    string  `json:"meeting_id"`
	ProposedBy   string  `json:"proposed_by"`
	Summary      string  `json:"summary"`
	Status       string  `json:"status"`
	Revision     int64   `json:"revision"`
	ProposedAt   string  `json:"proposed_at"`
	DecidedAt    *string `json:"decided_at"`
	DecisionNote *string `json:"decision_note"`
}

type Objective struct {
	ID                string `json:"id"`
	WorkspaceID       string `json:"workspace_id"`
	ProjectID         string `json:"project_id"`
	Title             string `json:"title"`
	Status            string `json:"status"`
	BudgetTokens      int64  `json:"budget_tokens"`
	BudgetCostCents   int64  `json:"budget_cost_cents"`
	BudgetTimeSeconds int64  `json:"budget_time_seconds"`
	Revision          int64  `json:"revision"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
	CreatedBy         string `json:"created_by"`
	UpdatedBy         string `json:"updated_by"`
}

type OutcomeAssessment struct {
	ID                     string  `json:"id"`
	WorkspaceID            string  `json:"workspace_id"`
	ProjectID              string  `json:"project_id"`
	ObjectiveID            string  `json:"objective_id"`
	TaskID                 string  `json:"task_id"`
	CommitmentID           string  `json:"commitment_id"`
	Revision               int64   `json:"revision"`
	StateRevision          int64   `json:"state_revision"`
	ReviewState            string  `json:"review_state"`
	Conclusion             string  `json:"conclusion"`
	DeliveredScopeJson     string  `json:"delivered_scope_json"`
	UnmetScopeJson         string  `json:"unmet_scope_json"`
	ContentJson            string  `json:"content_json"`
	ContentSha256          string  `json:"content_sha256"`
	SupersedesAssessmentID *string `json:"supersedes_assessment_id"`
	ProposedAt             string  `json:"proposed_at"`
	ProposedBy             string  `json:"proposed_by"`
	DecidedAt              *string `json:"decided_at"`
	DecidedBy              *string `json:"decided_by"`
	DecisionNote           *string `json:"decision_note"`
}

type OutcomeAssessmentAcceptanceBasis struct {
	AssessmentID  string `json:"assessment_id"`
	EventSequence int64  `json:"event_sequence"`
	SourceSha256  string `json:"source_sha256"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
}

type OutcomeAssessmentDecisionRef struct {
	AssessmentID  string `json:"assessment_id"`
	Ordinal       int64  `json:"ordinal"`
	RevisionID    string `json:"revision_id"`
	ContentSha256 string `json:"content_sha256"`
	EventSequence int64  `json:"event_sequence"`
}

type OutcomeAssessmentDeviation struct {
	AssessmentID        string  `json:"assessment_id"`
	Ordinal             int64   `json:"ordinal"`
	Kind                string  `json:"kind"`
	Summary             string  `json:"summary"`
	RelatedTaskID       *string `json:"related_task_id"`
	RelatedTaskRevision *int64  `json:"related_task_revision"`
}

type OutcomeAssessmentEffect struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Kind         string `json:"kind"`
	Direction    string `json:"direction"`
	Summary      string `json:"summary"`
}

type OutcomeAssessmentEvidenceRef struct {
	AssessmentID    string `json:"assessment_id"`
	Ordinal         int64  `json:"ordinal"`
	SourceType      string `json:"source_type"`
	SourceID        string `json:"source_id"`
	SourceRevision  int64  `json:"source_revision"`
	SourceSha256    string `json:"source_sha256"`
	EventSequence   int64  `json:"event_sequence"`
	Class           string `json:"class"`
	Effect          string `json:"effect"`
	PinnedFreshness string `json:"pinned_freshness"`
}

type OutcomeAssessmentFollowUpTask struct {
	AssessmentID  string `json:"assessment_id"`
	Ordinal       int64  `json:"ordinal"`
	TaskID        string `json:"task_id"`
	TaskRevision  int64  `json:"task_revision"`
	EventSequence int64  `json:"event_sequence"`
}

type OutcomeAssessmentGovernance struct {
	AssessmentID            string  `json:"assessment_id"`
	Decision                string  `json:"decision"`
	DecisionEventSequence   int64   `json:"decision_event_sequence"`
	SupersededAssessmentID  *string `json:"superseded_assessment_id"`
	SupersededEventSequence *int64  `json:"superseded_event_sequence"`
	DecidedAt               string  `json:"decided_at"`
}

type OutcomeAssessmentOwnerAttention struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Urgency      string `json:"urgency"`
	Action       string `json:"action"`
	Reason       string `json:"reason"`
}

type OutcomeAssessmentRisk struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Severity     string `json:"severity"`
	Summary      string `json:"summary"`
	Mitigation   string `json:"mitigation"`
}

type OutcomeAssessmentSubmission struct {
	AssessmentID  string `json:"assessment_id"`
	EventSequence int64  `json:"event_sequence"`
	ChildCount    int64  `json:"child_count"`
	SubmittedAt   string `json:"submitted_at"`
}

type OutcomeAssessmentUnknown struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Summary      string `json:"summary"`
}

type OutcomeCommitmentReceipt struct {
	CommitmentID  string `json:"commitment_id"`
	EventSequence int64  `json:"event_sequence"`
	CreatedAt     string `json:"created_at"`
}

type OutcomeProjectorState struct {
	WorkspaceID       string `json:"workspace_id"`
	LastEventSequence int64  `json:"last_event_sequence"`
	Revision          int64  `json:"revision"`
	UpdatedAt         string `json:"updated_at"`
}

type OwnerCheckpoint struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	ScopeType     string `json:"scope_type"`
	ScopeID       string `json:"scope_id"`
	EventSequence int64  `json:"event_sequence"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
}

type Project struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Revision    int64  `json:"revision"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	CreatedBy   string `json:"created_by"`
	UpdatedBy   string `json:"updated_by"`
}

type Repository struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	Fingerprint     string `json:"fingerprint"`
	ObjectFormat    string `json:"object_format"`
	RootCommitsJson string `json:"root_commits_json"`
	Revision        int64  `json:"revision"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	CreatedBy       string `json:"created_by"`
	UpdatedBy       string `json:"updated_by"`
}

type RunContextDeltaState struct {
	RunID                   string  `json:"run_id"`
	ContextPacketID         string  `json:"context_packet_id"`
	Status                  string  `json:"status"`
	Revision                int64   `json:"revision"`
	ScanEventSequence       int64   `json:"scan_event_sequence"`
	LastSequence            int64   `json:"last_sequence"`
	LastDeltaID             *string `json:"last_delta_id"`
	PendingDeltaID          *string `json:"pending_delta_id"`
	LastAcknowledgedDeltaID *string `json:"last_acknowledged_delta_id"`
	DeltaCount              int64   `json:"delta_count"`
	CumulativeByteSize      int64   `json:"cumulative_byte_size"`
	RebaseReason            *string `json:"rebase_reason"`
	RebaseEventSequence     *int64  `json:"rebase_event_sequence"`
	CreatedAt               string  `json:"created_at"`
	UpdatedAt               string  `json:"updated_at"`
}

type RunLogArtifact struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	Kind          string `json:"kind"`
	ContentSha256 string `json:"content_sha256"`
	CapturedBytes int64  `json:"captured_bytes"`
	OmittedBytes  int64  `json:"omitted_bytes"`
	Truncated     int64  `json:"truncated"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
}

type RunLossResolution struct {
	RunID         string `json:"run_id"`
	LostRevision  int64  `json:"lost_revision"`
	Resolution    string `json:"resolution"`
	Note          string `json:"note"`
	EventSequence int64  `json:"event_sequence"`
	ResolvedAt    string `json:"resolved_at"`
	ResolvedBy    string `json:"resolved_by"`
}

type TaskCheckRequirement struct {
	ID                        string `json:"id"`
	WorkspaceID               string `json:"workspace_id"`
	ProjectID                 string `json:"project_id"`
	TaskID                    string `json:"task_id"`
	TaskRevisionAtCreation    int64  `json:"task_revision_at_creation"`
	CriterionKey              string `json:"criterion_key"`
	Statement                 string `json:"statement"`
	DefinitionID              string `json:"definition_id"`
	DefinitionContentRevision int64  `json:"definition_content_revision"`
	Status                    string `json:"status"`
	Revision                  int64  `json:"revision"`
	CreatedAt                 string `json:"created_at"`
	UpdatedAt                 string `json:"updated_at"`
	CreatedBy                 string `json:"created_by"`
	UpdatedBy                 string `json:"updated_by"`
}

type ThreadParticipant struct {
	ID                 string `json:"id"`
	ThreadID           string `json:"thread_id"`
	WorkspaceID        string `json:"workspace_id"`
	AgentID            string `json:"agent_id"`
	AgentName          string `json:"agent_name"`
	TaskID             string `json:"task_id"`
	TaskTitle          string `json:"task_title"`
	ProjectID          string `json:"project_id"`
	ProjectName        string `json:"project_name"`
	AssignmentID       string `json:"assignment_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
	AgentRevision      int64  `json:"agent_revision"`
	TaskRevision       int64  `json:"task_revision"`
	Ordinal            int64  `json:"ordinal"`
	Status             string `json:"status"`
	InvitedAt          string `json:"invited_at"`
	InvitedBy          string `json:"invited_by"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Revision  int64  `json:"revision"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	CreatedBy string `json:"created_by"`
	UpdatedBy string `json:"updated_by"`
}
