// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type CuratorAutoAcceptance struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	RuleID                 string `json:"rule_id"`
	RuleName               string `json:"rule_name"`
	RuleRevision           int64  `json:"rule_revision"`
	DerivationID           string `json:"derivation_id"`
	KnowledgeRevisionID    string `json:"knowledge_revision_id"`
	AuthorityCheckID       string `json:"authority_check_id"`
	KnowledgeEventSequence int64  `json:"knowledge_event_sequence"`
	EventSequence          int64  `json:"event_sequence"`
	CreatedAt              string `json:"created_at"`
	ActorID                string `json:"actor_id"`
	ActorType              string `json:"actor_type"`
}

type CuratorDerivation struct {
	ID                  string `json:"id"`
	WorkspaceID         string `json:"workspace_id"`
	ProjectID           string `json:"project_id"`
	RuleID              string `json:"rule_id"`
	RuleName            string `json:"rule_name"`
	RuleRevision        int64  `json:"rule_revision"`
	SourceType          string `json:"source_type"`
	SourceID            string `json:"source_id"`
	SourceRevision      int64  `json:"source_revision"`
	SourceContentHash   string `json:"source_content_hash"`
	KnowledgeRevisionID string `json:"knowledge_revision_id"`
	OutputContentHash   string `json:"output_content_hash"`
	CreatedAt           string `json:"created_at"`
	CreatedBy           string `json:"created_by"`
	EventSequence       int64  `json:"event_sequence"`
}

type CuratorRule struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	Name          string `json:"name"`
	Revision      int64  `json:"revision"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
	EventSequence int64  `json:"event_sequence"`
}

type KnowledgeAuthorityCheck struct {
	ID             string  `json:"id"`
	WorkspaceID    string  `json:"workspace_id"`
	RevisionID     string  `json:"revision_id"`
	Action         string  `json:"action"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	Outcome        string  `json:"outcome"`
	Reason         string  `json:"reason"`
	Note           *string `json:"note"`
	IdempotencyKey string  `json:"idempotency_key"`
	RequestHash    string  `json:"request_hash"`
	EventSequence  int64   `json:"event_sequence"`
	CreatedAt      string  `json:"created_at"`
}

type KnowledgeSource struct {
	RevisionID     string `json:"revision_id"`
	Ordinal        int64  `json:"ordinal"`
	SourceType     string `json:"source_type"`
	SourceID       string `json:"source_id"`
	SourceRevision int64  `json:"source_revision"`
	Role           string `json:"role"`
}

type Meeting struct {
	ID                 string  `json:"id"`
	WorkspaceID        string  `json:"workspace_id"`
	ProjectID          string  `json:"project_id"`
	OverlapID          string  `json:"overlap_id"`
	Agenda             string  `json:"agenda"`
	FacilitatorAgentID string  `json:"facilitator_agent_id"`
	Policy             string  `json:"policy"`
	ReviewerAgentID    *string `json:"reviewer_agent_id"`
	AllowedActionsJson string  `json:"allowed_actions_json"`
	Status             string  `json:"status"`
	FrozenInputJson    string  `json:"frozen_input_json"`
	FrozenInputHash    string  `json:"frozen_input_hash"`
	DeadlineAt         string  `json:"deadline_at"`
	StalledReason      *string `json:"stalled_reason"`
	Revision           int64   `json:"revision"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	CreatedBy          string  `json:"created_by"`
	UpdatedBy          string  `json:"updated_by"`
}

type MeetingAction struct {
	ID             string  `json:"id"`
	ProposalID     string  `json:"proposal_id"`
	Ordinal        int64   `json:"ordinal"`
	Type           string  `json:"type"`
	PayloadJson    string  `json:"payload_json"`
	Status         string  `json:"status"`
	ResultEntityID *string `json:"result_entity_id"`
	Diagnostic     *string `json:"diagnostic"`
	AppliedAt      *string `json:"applied_at"`
}

type MeetingContribution struct {
	ID           string `json:"id"`
	MeetingID    string `json:"meeting_id"`
	AgentID      string `json:"agent_id"`
	Round        string `json:"round"`
	Summary      string `json:"summary"`
	EvidenceJson string `json:"evidence_json"`
	SubmittedAt  string `json:"submitted_at"`
}

type MeetingParticipant struct {
	MeetingID string  `json:"meeting_id"`
	AgentID   string  `json:"agent_id"`
	TaskID    *string `json:"task_id"`
	Ordinal   int64   `json:"ordinal"`
	Status    string  `json:"status"`
}

type MeetingProposal struct {
	ID           string  `json:"id"`
	MeetingID    string  `json:"meeting_id"`
	ProposedBy   string  `json:"proposed_by"`
	Summary      string  `json:"summary"`
	Status       string  `json:"status"`
	Revision     int64   `json:"revision"`
	ProposedAt   string  `json:"proposed_at"`
	DecidedAt    *string `json:"decided_at"`
	DecisionNote *string `json:"decision_note"`
}

type ThreadParticipant struct {
	ID                 string `json:"id"`
	ThreadID           string `json:"thread_id"`
	WorkspaceID        string `json:"workspace_id"`
	AgentID            string `json:"agent_id"`
	AgentName          string `json:"agent_name"`
	TaskID             string `json:"task_id"`
	TaskTitle          string `json:"task_title"`
	ProjectID          string `json:"project_id"`
	ProjectName        string `json:"project_name"`
	AssignmentID       string `json:"assignment_id"`
	AssignmentRevision int64  `json:"assignment_revision"`
	AgentRevision      int64  `json:"agent_revision"`
	TaskRevision       int64  `json:"task_revision"`
	Ordinal            int64  `json:"ordinal"`
	Status             string `json:"status"`
	InvitedAt          string `json:"invited_at"`
	InvitedBy          string `json:"invited_by"`
}
