// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_reads.sql

package dbgen

import (
	"context"
)

const countOperatorAgents = `-- name: CountOperatorAgents :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM agents
WHERE workspace_id = ?1
`

func (q *Queries) CountOperatorAgents(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorAgents, workspaceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorApprovals = `-- name: CountOperatorApprovals :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM approval_requests approval
WHERE approval.workspace_id = ?1
  AND EXISTS (
    SELECT 1
    FROM supervisor_actions action
    JOIN supervisor_action_receipts receipt ON receipt.action_id = action.id
    WHERE action.id = approval.action_id AND receipt.condition_key = action.condition_key
  )
  AND (
    CAST(?2 AS TEXT) = ''
    OR EXISTS (SELECT 1 FROM supervisor_actions scoped_action WHERE scoped_action.id = approval.action_id AND scoped_action.project_id = ?2)
  )
  AND (CAST(?3 AS TEXT) = '' OR approval.status = ?3)
  AND (CAST(?4 AS TEXT) = '' OR approval.action_id = ?4)
`

type CountOperatorApprovalsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	ActionID    string `json:"action_id"`
}

func (q *Queries) CountOperatorApprovals(ctx context.Context, arg CountOperatorApprovalsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorApprovals,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.ActionID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorCheckRuns = `-- name: CountOperatorCheckRuns :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM check_runs run
LEFT JOIN check_results result ON result.check_run_id = run.id
WHERE run.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR run.project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR run.task_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR run.requirement_id = ?4)
  AND (CAST(?5 AS TEXT) = '' OR run.definition_id = ?5)
  AND (CAST(?6 AS TEXT) = '' OR run.status = ?6)
  AND (CAST(?7 AS TEXT) = '' OR result.outcome = ?7)
`

type CountOperatorCheckRunsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	ProjectID     string `json:"project_id"`
	TaskID        string `json:"task_id"`
	RequirementID string `json:"requirement_id"`
	DefinitionID  string `json:"definition_id"`
	Status        string `json:"status"`
	Outcome       string `json:"outcome"`
}

func (q *Queries) CountOperatorCheckRuns(ctx context.Context, arg CountOperatorCheckRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorCheckRuns,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.RequirementID,
		arg.DefinitionID,
		arg.Status,
		arg.Outcome,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorClaimDrifts = `-- name: CountOperatorClaimDrifts :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM claim_drifts
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
`

type CountOperatorClaimDriftsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountOperatorClaimDrifts(ctx context.Context, arg CountOperatorClaimDriftsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorClaimDrifts, arg.WorkspaceID, arg.ProjectID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorClaims = `-- name: CountOperatorClaims :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM work_claims
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
`

type CountOperatorClaimsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountOperatorClaims(ctx context.Context, arg CountOperatorClaimsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorClaims, arg.WorkspaceID, arg.ProjectID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorEntityEvents = `-- name: CountOperatorEntityEvents :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM events
WHERE workspace_id = ?1
  AND entity_type = ?2
  AND entity_id = ?3
  AND sequence <= ?4
`

type CountOperatorEntityEventsParams struct {
	WorkspaceID string `json:"workspace_id"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	HighWater   int64  `json:"high_water"`
}

func (q *Queries) CountOperatorEntityEvents(ctx context.Context, arg CountOperatorEntityEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorEntityEvents,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.HighWater,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorEvents = `-- name: CountOperatorEvents :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM events
WHERE workspace_id = ?1
  AND sequence > ?2
  AND sequence <= ?3
`

type CountOperatorEventsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	AfterSequence int64  `json:"after_sequence"`
	HighWater     int64  `json:"high_water"`
}

func (q *Queries) CountOperatorEvents(ctx context.Context, arg CountOperatorEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorEvents, arg.WorkspaceID, arg.AfterSequence, arg.HighWater)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorMeetings = `-- name: CountOperatorMeetings :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM meetings
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
`

type CountOperatorMeetingsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountOperatorMeetings(ctx context.Context, arg CountOperatorMeetingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorMeetings, arg.WorkspaceID, arg.ProjectID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorObjectives = `-- name: CountOperatorObjectives :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM objectives
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
`

type CountOperatorObjectivesParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) CountOperatorObjectives(ctx context.Context, arg CountOperatorObjectivesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorObjectives, arg.WorkspaceID, arg.ProjectID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorOverlaps = `-- name: CountOperatorOverlaps :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM work_overlaps
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
`

type CountOperatorOverlapsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountOperatorOverlaps(ctx context.Context, arg CountOperatorOverlapsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorOverlaps, arg.WorkspaceID, arg.ProjectID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorProjects = `-- name: CountOperatorProjects :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM projects
WHERE workspace_id = ?1
`

func (q *Queries) CountOperatorProjects(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorProjects, workspaceID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorRuns = `-- name: CountOperatorRuns :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM runs
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR task_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR status = ?4)
`

type CountOperatorRunsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	Status      string `json:"status"`
}

func (q *Queries) CountOperatorRuns(ctx context.Context, arg CountOperatorRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorRuns,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.Status,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorTasks = `-- name: CountOperatorTasks :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM tasks t
WHERE t.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR t.project_id = ?2)
  AND (
    CAST(?3 AS INTEGER) = 0
    OR (
      t.status = 'ready'
      AND NOT EXISTS (
        SELECT 1
        FROM task_dependencies dependency_link
        JOIN tasks dependency ON dependency.id = dependency_link.depends_on_task_id
        WHERE dependency_link.task_id = t.id AND dependency.status <> 'completed'
      )
    )
  )
`

type CountOperatorTasksParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	ReadyOnly   int64  `json:"ready_only"`
}

func (q *Queries) CountOperatorTasks(ctx context.Context, arg CountOperatorTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorTasks, arg.WorkspaceID, arg.ProjectID, arg.ReadyOnly)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOperatorWorkspaces = `-- name: CountOperatorWorkspaces :one
SELECT CAST(COUNT(*) AS INTEGER) AS total
FROM workspaces
`

func (q *Queries) CountOperatorWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorWorkspaces)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findFirstUnsupportedOperatorEntityEvent = `-- name: FindFirstUnsupportedOperatorEntityEvent :one
SELECT sequence, type
FROM events
WHERE workspace_id = ?1
  AND entity_type = ?2
  AND entity_id = ?3
  AND sequence <= ?4
  AND crewfold_event_type_known(type) = 0
ORDER BY sequence DESC
LIMIT 1
`

type FindFirstUnsupportedOperatorEntityEventParams struct {
	WorkspaceID string `json:"workspace_id"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	HighWater   int64  `json:"high_water"`
}

type FindFirstUnsupportedOperatorEntityEventRow struct {
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

func (q *Queries) FindFirstUnsupportedOperatorEntityEvent(ctx context.Context, arg FindFirstUnsupportedOperatorEntityEventParams) (FindFirstUnsupportedOperatorEntityEventRow, error) {
	row := q.db.QueryRowContext(ctx, findFirstUnsupportedOperatorEntityEvent,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.HighWater,
	)
	var i FindFirstUnsupportedOperatorEntityEventRow
	err := row.Scan(&i.Sequence, &i.Type)
	return i, err
}

const findFirstUnsupportedOperatorEvent = `-- name: FindFirstUnsupportedOperatorEvent :one
SELECT sequence, type
FROM events
WHERE workspace_id = ?1
  AND sequence > ?2
  AND sequence <= ?3
  AND crewfold_event_type_known(type) = 0
ORDER BY sequence
LIMIT 1
`

type FindFirstUnsupportedOperatorEventParams struct {
	WorkspaceID   string `json:"workspace_id"`
	AfterSequence int64  `json:"after_sequence"`
	HighWater     int64  `json:"high_water"`
}

type FindFirstUnsupportedOperatorEventRow struct {
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

func (q *Queries) FindFirstUnsupportedOperatorEvent(ctx context.Context, arg FindFirstUnsupportedOperatorEventParams) (FindFirstUnsupportedOperatorEventRow, error) {
	row := q.db.QueryRowContext(ctx, findFirstUnsupportedOperatorEvent, arg.WorkspaceID, arg.AfterSequence, arg.HighWater)
	var i FindFirstUnsupportedOperatorEventRow
	err := row.Scan(&i.Sequence, &i.Type)
	return i, err
}

const listOperatorAgents = `-- name: ListOperatorAgents :many
SELECT id, workspace_id, name, role, provider, runtime, enabled,
       max_concurrency, revision, created_at, updated_at, created_by, updated_by
FROM agents
WHERE workspace_id = ?1
  AND (
    CAST(?2 AS TEXT) = ''
    OR name > ?2
    OR (name = ?2 AND id > ?3)
  )
ORDER BY name, id
LIMIT ?4
`

type ListOperatorAgentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CursorName  string `json:"cursor_name"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorAgents(ctx context.Context, arg ListOperatorAgentsParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorAgents,
		arg.WorkspaceID,
		arg.CursorName,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Role,
			&i.Provider,
			&i.Runtime,
			&i.Enabled,
			&i.MaxConcurrency,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorApprovalIDs = `-- name: ListOperatorApprovalIDs :many
SELECT approval.id
FROM approval_requests approval
WHERE approval.workspace_id = ?1
  AND EXISTS (
    SELECT 1
    FROM supervisor_actions action
    JOIN supervisor_action_receipts receipt ON receipt.action_id = action.id
    WHERE action.id = approval.action_id AND receipt.condition_key = action.condition_key
  )
  AND (
    CAST(?2 AS TEXT) = ''
    OR EXISTS (SELECT 1 FROM supervisor_actions scoped_action WHERE scoped_action.id = approval.action_id AND scoped_action.project_id = ?2)
  )
  AND (CAST(?3 AS TEXT) = '' OR approval.status = ?3)
  AND (CAST(?4 AS TEXT) = '' OR approval.action_id = ?4)
  AND (
    CAST(?5 AS TEXT) = ''
    OR approval.created_at > ?5
    OR (approval.created_at = ?5 AND approval.id > ?6)
  )
ORDER BY approval.created_at, approval.id
LIMIT ?7
`

type ListOperatorApprovalIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	ActionID    string `json:"action_id"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorApprovalIDs(ctx context.Context, arg ListOperatorApprovalIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorApprovalIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.ActionID,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorCheckRunIDs = `-- name: ListOperatorCheckRunIDs :many
SELECT run.id
FROM check_runs run
LEFT JOIN check_results result ON result.check_run_id = run.id
WHERE run.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR run.project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR run.task_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR run.requirement_id = ?4)
  AND (CAST(?5 AS TEXT) = '' OR run.definition_id = ?5)
  AND (CAST(?6 AS TEXT) = '' OR run.status = ?6)
  AND (CAST(?7 AS TEXT) = '' OR result.outcome = ?7)
  AND (
    CAST(?8 AS TEXT) = ''
    OR run.created_at < ?8
    OR (run.created_at = ?8 AND run.id < ?9)
  )
ORDER BY run.created_at DESC, run.id DESC
LIMIT ?10
`

type ListOperatorCheckRunIDsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	ProjectID     string `json:"project_id"`
	TaskID        string `json:"task_id"`
	RequirementID string `json:"requirement_id"`
	DefinitionID  string `json:"definition_id"`
	Status        string `json:"status"`
	Outcome       string `json:"outcome"`
	CursorKey     string `json:"cursor_key"`
	CursorID      string `json:"cursor_id"`
	ResultLimit   int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorCheckRunIDs(ctx context.Context, arg ListOperatorCheckRunIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorCheckRunIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.RequirementID,
		arg.DefinitionID,
		arg.Status,
		arg.Outcome,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorClaimDriftIDs = `-- name: ListOperatorClaimDriftIDs :many
SELECT id
FROM claim_drifts
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
  AND (
    CAST(?4 AS TEXT) = ''
    OR first_observed_at < ?4
    OR (first_observed_at = ?4 AND id < ?5)
  )
ORDER BY first_observed_at DESC, id DESC
LIMIT ?6
`

type ListOperatorClaimDriftIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorClaimDriftIDs(ctx context.Context, arg ListOperatorClaimDriftIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorClaimDriftIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorClaimIDs = `-- name: ListOperatorClaimIDs :many
SELECT id
FROM work_claims
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
  AND (
    CAST(?4 AS TEXT) = ''
    OR created_at > ?4
    OR (created_at = ?4 AND id > ?5)
  )
ORDER BY created_at, id
LIMIT ?6
`

type ListOperatorClaimIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorClaimIDs(ctx context.Context, arg ListOperatorClaimIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorClaimIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorEntityEvents = `-- name: ListOperatorEntityEvents :many
SELECT event_id, sequence, type, schema_version, occurred_at, recorded_at,
       actor_id, actor_type, workspace_id, entity_type, entity_id,
       entity_revision, correlation_id, causation_id, data_json
FROM events
WHERE workspace_id = ?1
  AND entity_type = ?2
  AND entity_id = ?3
  AND sequence <= ?4
  AND (CAST(?5 AS INTEGER) = 0 OR sequence < ?5)
ORDER BY sequence DESC
LIMIT ?6
`

type ListOperatorEntityEventsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	EntityType     string `json:"entity_type"`
	EntityID       string `json:"entity_id"`
	HighWater      int64  `json:"high_water"`
	CursorSequence int64  `json:"cursor_sequence"`
	ResultLimit    int64  `json:"result_limit"`
}

type ListOperatorEntityEventsRow struct {
	EventID        string  `json:"event_id"`
	Sequence       int64   `json:"sequence"`
	Type           string  `json:"type"`
	SchemaVersion  int64   `json:"schema_version"`
	OccurredAt     string  `json:"occurred_at"`
	RecordedAt     string  `json:"recorded_at"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	WorkspaceID    string  `json:"workspace_id"`
	EntityType     string  `json:"entity_type"`
	EntityID       string  `json:"entity_id"`
	EntityRevision int64   `json:"entity_revision"`
	CorrelationID  string  `json:"correlation_id"`
	CausationID    *string `json:"causation_id"`
	DataJson       string  `json:"data_json"`
}

func (q *Queries) ListOperatorEntityEvents(ctx context.Context, arg ListOperatorEntityEventsParams) ([]ListOperatorEntityEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorEntityEvents,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.HighWater,
		arg.CursorSequence,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorEntityEventsRow{}
	for rows.Next() {
		var i ListOperatorEntityEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Sequence,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorType,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.EntityRevision,
			&i.CorrelationID,
			&i.CausationID,
			&i.DataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorEvents = `-- name: ListOperatorEvents :many
SELECT event_id, sequence, type, schema_version, occurred_at, recorded_at,
       actor_id, actor_type, workspace_id, entity_type, entity_id,
       entity_revision, correlation_id, causation_id, data_json
FROM events
WHERE workspace_id = ?1
  AND sequence > ?2
  AND sequence <= ?3
ORDER BY sequence
LIMIT ?4
`

type ListOperatorEventsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PageAfter   int64  `json:"page_after"`
	HighWater   int64  `json:"high_water"`
	ResultLimit int64  `json:"result_limit"`
}

type ListOperatorEventsRow struct {
	EventID        string  `json:"event_id"`
	Sequence       int64   `json:"sequence"`
	Type           string  `json:"type"`
	SchemaVersion  int64   `json:"schema_version"`
	OccurredAt     string  `json:"occurred_at"`
	RecordedAt     string  `json:"recorded_at"`
	ActorID        string  `json:"actor_id"`
	ActorType      string  `json:"actor_type"`
	WorkspaceID    string  `json:"workspace_id"`
	EntityType     string  `json:"entity_type"`
	EntityID       string  `json:"entity_id"`
	EntityRevision int64   `json:"entity_revision"`
	CorrelationID  string  `json:"correlation_id"`
	CausationID    *string `json:"causation_id"`
	DataJson       string  `json:"data_json"`
}

func (q *Queries) ListOperatorEvents(ctx context.Context, arg ListOperatorEventsParams) ([]ListOperatorEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorEvents,
		arg.WorkspaceID,
		arg.PageAfter,
		arg.HighWater,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorEventsRow{}
	for rows.Next() {
		var i ListOperatorEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Sequence,
			&i.Type,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorID,
			&i.ActorType,
			&i.WorkspaceID,
			&i.EntityType,
			&i.EntityID,
			&i.EntityRevision,
			&i.CorrelationID,
			&i.CausationID,
			&i.DataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorMeetings = `-- name: ListOperatorMeetings :many
SELECT id, workspace_id, project_id, overlap_id, agenda, facilitator_agent_id,
       policy, reviewer_agent_id, allowed_actions_json, status, frozen_input_hash,
       deadline_at, stalled_reason, revision, created_at, updated_at, created_by,
       updated_by
FROM meetings
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
  AND (
    CAST(?4 AS TEXT) = ''
    OR created_at < ?4
    OR (created_at = ?4 AND id < ?5)
  )
ORDER BY created_at DESC, id DESC
LIMIT ?6
`

type ListOperatorMeetingsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

type ListOperatorMeetingsRow struct {
	ID                 string  `json:"id"`
	WorkspaceID        string  `json:"workspace_id"`
	ProjectID          string  `json:"project_id"`
	OverlapID          string  `json:"overlap_id"`
	Agenda             string  `json:"agenda"`
	FacilitatorAgentID string  `json:"facilitator_agent_id"`
	Policy             string  `json:"policy"`
	ReviewerAgentID    *string `json:"reviewer_agent_id"`
	AllowedActionsJson string  `json:"allowed_actions_json"`
	Status             string  `json:"status"`
	FrozenInputHash    string  `json:"frozen_input_hash"`
	DeadlineAt         string  `json:"deadline_at"`
	StalledReason      *string `json:"stalled_reason"`
	Revision           int64   `json:"revision"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
	CreatedBy          string  `json:"created_by"`
	UpdatedBy          string  `json:"updated_by"`
}

func (q *Queries) ListOperatorMeetings(ctx context.Context, arg ListOperatorMeetingsParams) ([]ListOperatorMeetingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorMeetings,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorMeetingsRow{}
	for rows.Next() {
		var i ListOperatorMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.OverlapID,
			&i.Agenda,
			&i.FacilitatorAgentID,
			&i.Policy,
			&i.ReviewerAgentID,
			&i.AllowedActionsJson,
			&i.Status,
			&i.FrozenInputHash,
			&i.DeadlineAt,
			&i.StalledReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorObjectives = `-- name: ListOperatorObjectives :many
SELECT id, workspace_id, project_id, title, status, budget_tokens,
       budget_cost_cents, budget_time_seconds, revision, created_at,
       updated_at, created_by, updated_by
FROM objectives
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (
    CAST(?3 AS TEXT) = ''
    OR created_at > ?3
    OR (created_at = ?3 AND id > ?4)
  )
ORDER BY created_at, id
LIMIT ?5
`

type ListOperatorObjectivesParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorObjectives(ctx context.Context, arg ListOperatorObjectivesParams) ([]Objective, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorObjectives,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Objective{}
	for rows.Next() {
		var i Objective
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.BudgetTokens,
			&i.BudgetCostCents,
			&i.BudgetTimeSeconds,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorOverlapIDs = `-- name: ListOperatorOverlapIDs :many
SELECT id
FROM work_overlaps
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR status = ?3)
  AND (
    CAST(?4 AS TEXT) = ''
    OR detected_at < ?4
    OR (detected_at = ?4 AND id < ?5)
  )
ORDER BY detected_at DESC, id DESC
LIMIT ?6
`

type ListOperatorOverlapIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	Status      string `json:"status"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorOverlapIDs(ctx context.Context, arg ListOperatorOverlapIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorOverlapIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorProjects = `-- name: ListOperatorProjects :many
SELECT id, workspace_id, name, revision, created_at, updated_at, created_by, updated_by
FROM projects
WHERE workspace_id = ?1
  AND (
    CAST(?2 AS TEXT) = ''
    OR name > ?2
    OR (name = ?2 AND id > ?3)
  )
ORDER BY name, id
LIMIT ?4
`

type ListOperatorProjectsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CursorName  string `json:"cursor_name"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorProjects(ctx context.Context, arg ListOperatorProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorProjects,
		arg.WorkspaceID,
		arg.CursorName,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorRuns = `-- name: ListOperatorRuns :many
SELECT id, workspace_id, project_id, task_id, agent_id, runtime, provider,
       status, COALESCE(blocked_question, '') AS blocked_question,
       COALESCE(result_summary, '') AS result_summary,
       COALESCE(failure_code, '') AS failure_code, revision, created_at,
       updated_at, COALESCE(started_at, '') AS started_at,
       COALESCE(finished_at, '') AS finished_at,
       COALESCE(runtime_handle, '') AS runtime_handle
FROM runs
WHERE workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR project_id = ?2)
  AND (CAST(?3 AS TEXT) = '' OR task_id = ?3)
  AND (CAST(?4 AS TEXT) = '' OR status = ?4)
  AND (
    CAST(?5 AS TEXT) = ''
    OR created_at < ?5
    OR (created_at = ?5 AND id < ?6)
  )
ORDER BY created_at DESC, id DESC
LIMIT ?7
`

type ListOperatorRunsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	TaskID      string `json:"task_id"`
	Status      string `json:"status"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

type ListOperatorRunsRow struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	ProjectID       string `json:"project_id"`
	TaskID          string `json:"task_id"`
	AgentID         string `json:"agent_id"`
	Runtime         string `json:"runtime"`
	Provider        string `json:"provider"`
	Status          string `json:"status"`
	BlockedQuestion string `json:"blocked_question"`
	ResultSummary   string `json:"result_summary"`
	FailureCode     string `json:"failure_code"`
	Revision        int64  `json:"revision"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	StartedAt       string `json:"started_at"`
	FinishedAt      string `json:"finished_at"`
	RuntimeHandle   string `json:"runtime_handle"`
}

func (q *Queries) ListOperatorRuns(ctx context.Context, arg ListOperatorRunsParams) ([]ListOperatorRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorRuns,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.Status,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorRunsRow{}
	for rows.Next() {
		var i ListOperatorRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentID,
			&i.Runtime,
			&i.Provider,
			&i.Status,
			&i.BlockedQuestion,
			&i.ResultSummary,
			&i.FailureCode,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RuntimeHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorTaskIDs = `-- name: ListOperatorTaskIDs :many
SELECT t.id
FROM tasks t
WHERE t.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR t.project_id = ?2)
  AND (
    CAST(?3 AS INTEGER) = 0
    OR (
      t.status = 'ready'
      AND NOT EXISTS (
        SELECT 1
        FROM task_dependencies dependency_link
        JOIN tasks dependency ON dependency.id = dependency_link.depends_on_task_id
        WHERE dependency_link.task_id = t.id AND dependency.status <> 'completed'
      )
    )
  )
  AND (
    CAST(?4 AS TEXT) = ''
    OR t.created_at > ?4
    OR (t.created_at = ?4 AND t.id > ?5)
  )
ORDER BY t.created_at, t.id
LIMIT ?6
`

type ListOperatorTaskIDsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	ReadyOnly   int64  `json:"ready_only"`
	CursorKey   string `json:"cursor_key"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorTaskIDs(ctx context.Context, arg ListOperatorTaskIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorTaskIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ReadyOnly,
		arg.CursorKey,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorWorkspaces = `-- name: ListOperatorWorkspaces :many
SELECT id, name, revision, created_at, updated_at, created_by, updated_by
FROM workspaces
WHERE CAST(?1 AS TEXT) = ''
   OR name > ?1
   OR (name = ?1 AND id > ?2)
ORDER BY name, id
LIMIT ?3
`

type ListOperatorWorkspacesParams struct {
	CursorName  string `json:"cursor_name"`
	CursorID    string `json:"cursor_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOperatorWorkspaces(ctx context.Context, arg ListOperatorWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorWorkspaces, arg.CursorName, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
