// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package dbgen

import (
	"context"
)

const acceptOutcomeAssessmentProjection = `-- name: AcceptOutcomeAssessmentProjection :execrows
UPDATE outcome_assessments
SET review_state='accepted',state_revision=state_revision+1,decided_at=?1,decided_by='local-owner',decision_note=NULLIF(?2,'')
WHERE workspace_id=?3 AND id=?4 AND review_state='proposed' AND state_revision=?5
`

type AcceptOutcomeAssessmentProjectionParams struct {
	DecidedAt             *string     `json:"decided_at"`
	DecisionNote          interface{} `json:"decision_note"`
	WorkspaceID           string      `json:"workspace_id"`
	ID                    string      `json:"id"`
	ExpectedStateRevision int64       `json:"expected_state_revision"`
}

func (q *Queries) AcceptOutcomeAssessmentProjection(ctx context.Context, arg AcceptOutcomeAssessmentProjectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptOutcomeAssessmentProjection,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.WorkspaceID,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceOutcomeProjectorState = `-- name: AdvanceOutcomeProjectorState :execrows
UPDATE outcome_projector_state SET last_event_sequence=?1,revision=revision+1,updated_at=?2
WHERE workspace_id=?3 AND last_event_sequence=?4
`

type AdvanceOutcomeProjectorStateParams struct {
	LastEventSequence     int64  `json:"last_event_sequence"`
	UpdatedAt             string `json:"updated_at"`
	WorkspaceID           string `json:"workspace_id"`
	ExpectedEventSequence int64  `json:"expected_event_sequence"`
}

func (q *Queries) AdvanceOutcomeProjectorState(ctx context.Context, arg AdvanceOutcomeProjectorStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceOutcomeProjectorState,
		arg.LastEventSequence,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ExpectedEventSequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findManagementBriefing = `-- name: FindManagementBriefing :one
SELECT id, revision, workspace_id, scope_type, scope_id, event_cursor, cutoff_event_sequence, checkpoint_id, since_event_sequence, evaluated_at, caught_up, unknown_event_type, unknown_event_sequence, content_json, content_sha256, byte_size, created_at FROM management_briefings WHERE workspace_id=?1
 AND scope_type=?2 AND scope_id=?3
 AND event_cursor=?4 AND checkpoint_id=?5 AND content_sha256=?6
`

type FindManagementBriefingParams struct {
	WorkspaceID   string `json:"workspace_id"`
	ScopeType     string `json:"scope_type"`
	ScopeID       string `json:"scope_id"`
	EventCursor   int64  `json:"event_cursor"`
	CheckpointID  string `json:"checkpoint_id"`
	ContentSha256 string `json:"content_sha256"`
}

func (q *Queries) FindManagementBriefing(ctx context.Context, arg FindManagementBriefingParams) (ManagementBriefing, error) {
	row := q.db.QueryRowContext(ctx, findManagementBriefing,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.EventCursor,
		arg.CheckpointID,
		arg.ContentSha256,
	)
	var i ManagementBriefing
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.EventCursor,
		&i.CutoffEventSequence,
		&i.CheckpointID,
		&i.SinceEventSequence,
		&i.EvaluatedAt,
		&i.CaughtUp,
		&i.UnknownEventType,
		&i.UnknownEventSequence,
		&i.ContentJson,
		&i.ContentSha256,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getAcceptedDecisionForOutcome = `-- name: GetAcceptedDecisionForOutcome :one
SELECT revision.id AS revision_id,revision.content_hash,revision.currency_status,revision.freshness_policy,
 revision.fresh_until,revision.state_revision,
 (SELECT event.sequence FROM events event WHERE event.workspace_id=item.workspace_id
   AND event.entity_type='knowledge_revision' AND event.entity_id=revision.id
   AND event.type='knowledge.accepted' ORDER BY event.sequence DESC LIMIT 1) AS event_sequence
FROM knowledge_revisions revision JOIN knowledge_items item ON item.id=revision.item_id
WHERE item.workspace_id=?1 AND item.project_id=?2
 AND (item.task_scope_id IS NULL OR item.task_scope_id=?3)
 AND item.type='decision' AND revision.id=?4 AND revision.review_status='accepted'
`

type GetAcceptedDecisionForOutcomeParams struct {
	WorkspaceID string  `json:"workspace_id"`
	ProjectID   string  `json:"project_id"`
	TaskID      *string `json:"task_id"`
	RevisionID  string  `json:"revision_id"`
}

type GetAcceptedDecisionForOutcomeRow struct {
	RevisionID      string  `json:"revision_id"`
	ContentHash     string  `json:"content_hash"`
	CurrencyStatus  string  `json:"currency_status"`
	FreshnessPolicy string  `json:"freshness_policy"`
	FreshUntil      *string `json:"fresh_until"`
	StateRevision   int64   `json:"state_revision"`
	EventSequence   int64   `json:"event_sequence"`
}

func (q *Queries) GetAcceptedDecisionForOutcome(ctx context.Context, arg GetAcceptedDecisionForOutcomeParams) (GetAcceptedDecisionForOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, getAcceptedDecisionForOutcome,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TaskID,
		arg.RevisionID,
	)
	var i GetAcceptedDecisionForOutcomeRow
	err := row.Scan(
		&i.RevisionID,
		&i.ContentHash,
		&i.CurrencyStatus,
		&i.FreshnessPolicy,
		&i.FreshUntil,
		&i.StateRevision,
		&i.EventSequence,
	)
	return i, err
}

const getCurrentAcceptedOutcomeAssessmentID = `-- name: GetCurrentAcceptedOutcomeAssessmentID :one
SELECT id FROM outcome_assessments
WHERE commitment_id=?1 AND review_state='accepted'
`

func (q *Queries) GetCurrentAcceptedOutcomeAssessmentID(ctx context.Context, commitmentID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCurrentAcceptedOutcomeAssessmentID, commitmentID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getDeliverableCommitment = `-- name: GetDeliverableCommitment :one
SELECT commitment.id, commitment.workspace_id, commitment.project_id, commitment.objective_id, commitment.task_id, commitment.commitment_key, commitment.title, commitment.description, commitment.acceptance_criteria_json, commitment.content_json, commitment.content_sha256, commitment.created_at, commitment.created_by FROM deliverable_commitments commitment
WHERE commitment.workspace_id=?1 AND commitment.id=?2
`

type GetDeliverableCommitmentParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetDeliverableCommitment(ctx context.Context, arg GetDeliverableCommitmentParams) (DeliverableCommitment, error) {
	row := q.db.QueryRowContext(ctx, getDeliverableCommitment, arg.WorkspaceID, arg.ID)
	var i DeliverableCommitment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.TaskID,
		&i.CommitmentKey,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteriaJson,
		&i.ContentJson,
		&i.ContentSha256,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getManagementBriefing = `-- name: GetManagementBriefing :one
SELECT id, revision, workspace_id, scope_type, scope_id, event_cursor, cutoff_event_sequence, checkpoint_id, since_event_sequence, evaluated_at, caught_up, unknown_event_type, unknown_event_sequence, content_json, content_sha256, byte_size, created_at FROM management_briefings WHERE workspace_id=?1 AND id=?2
`

type GetManagementBriefingParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetManagementBriefing(ctx context.Context, arg GetManagementBriefingParams) (ManagementBriefing, error) {
	row := q.db.QueryRowContext(ctx, getManagementBriefing, arg.WorkspaceID, arg.ID)
	var i ManagementBriefing
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.EventCursor,
		&i.CutoffEventSequence,
		&i.CheckpointID,
		&i.SinceEventSequence,
		&i.EvaluatedAt,
		&i.CaughtUp,
		&i.UnknownEventType,
		&i.UnknownEventSequence,
		&i.ContentJson,
		&i.ContentSha256,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getManagementBriefingClaim = `-- name: GetManagementBriefingClaim :one
SELECT briefing_id, ordinal, claim_id, semantic_key, kind, urgency, summary, status, project_id, source_event_sequence, claim_json FROM management_briefing_claims WHERE briefing_id=?1 AND claim_id=?2
`

type GetManagementBriefingClaimParams struct {
	BriefingID string `json:"briefing_id"`
	ClaimID    string `json:"claim_id"`
}

func (q *Queries) GetManagementBriefingClaim(ctx context.Context, arg GetManagementBriefingClaimParams) (ManagementBriefingClaim, error) {
	row := q.db.QueryRowContext(ctx, getManagementBriefingClaim, arg.BriefingID, arg.ClaimID)
	var i ManagementBriefingClaim
	err := row.Scan(
		&i.BriefingID,
		&i.Ordinal,
		&i.ClaimID,
		&i.SemanticKey,
		&i.Kind,
		&i.Urgency,
		&i.Summary,
		&i.Status,
		&i.ProjectID,
		&i.SourceEventSequence,
		&i.ClaimJson,
	)
	return i, err
}

const getManagementBriefingReceipt = `-- name: GetManagementBriefingReceipt :one
SELECT briefing_id, claim_count, source_count, sealed_at FROM management_briefing_receipts WHERE briefing_id=?1
`

func (q *Queries) GetManagementBriefingReceipt(ctx context.Context, briefingID string) (ManagementBriefingReceipt, error) {
	row := q.db.QueryRowContext(ctx, getManagementBriefingReceipt, briefingID)
	var i ManagementBriefingReceipt
	err := row.Scan(
		&i.BriefingID,
		&i.ClaimCount,
		&i.SourceCount,
		&i.SealedAt,
	)
	return i, err
}

const getOutcomeAssessment = `-- name: GetOutcomeAssessment :one
SELECT assessment.id, assessment.workspace_id, assessment.project_id, assessment.objective_id, assessment.task_id, assessment.commitment_id, assessment.revision, assessment.state_revision, assessment.review_state, assessment.conclusion, assessment.delivered_scope_json, assessment.unmet_scope_json, assessment.content_json, assessment.content_sha256, assessment.supersedes_assessment_id, assessment.proposed_at, assessment.proposed_by, assessment.decided_at, assessment.decided_by, assessment.decision_note FROM outcome_assessments assessment
WHERE assessment.workspace_id=?1 AND assessment.id=?2
`

type GetOutcomeAssessmentParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetOutcomeAssessment(ctx context.Context, arg GetOutcomeAssessmentParams) (OutcomeAssessment, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeAssessment, arg.WorkspaceID, arg.ID)
	var i OutcomeAssessment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.TaskID,
		&i.CommitmentID,
		&i.Revision,
		&i.StateRevision,
		&i.ReviewState,
		&i.Conclusion,
		&i.DeliveredScopeJson,
		&i.UnmetScopeJson,
		&i.ContentJson,
		&i.ContentSha256,
		&i.SupersedesAssessmentID,
		&i.ProposedAt,
		&i.ProposedBy,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.DecisionNote,
	)
	return i, err
}

const getOutcomeAssessmentAcceptanceBasis = `-- name: GetOutcomeAssessmentAcceptanceBasis :one
SELECT assessment_id, event_sequence, source_sha256, created_at, created_by FROM outcome_assessment_acceptance_basis WHERE assessment_id=?1
`

func (q *Queries) GetOutcomeAssessmentAcceptanceBasis(ctx context.Context, assessmentID string) (OutcomeAssessmentAcceptanceBasis, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeAssessmentAcceptanceBasis, assessmentID)
	var i OutcomeAssessmentAcceptanceBasis
	err := row.Scan(
		&i.AssessmentID,
		&i.EventSequence,
		&i.SourceSha256,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getOutcomeAssessmentGovernance = `-- name: GetOutcomeAssessmentGovernance :one
SELECT governance.assessment_id, governance.decision, governance.decision_event_sequence, governance.superseded_assessment_id, governance.superseded_event_sequence, governance.decided_at FROM outcome_assessment_governance governance WHERE governance.assessment_id=?1
`

func (q *Queries) GetOutcomeAssessmentGovernance(ctx context.Context, assessmentID string) (OutcomeAssessmentGovernance, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeAssessmentGovernance, assessmentID)
	var i OutcomeAssessmentGovernance
	err := row.Scan(
		&i.AssessmentID,
		&i.Decision,
		&i.DecisionEventSequence,
		&i.SupersededAssessmentID,
		&i.SupersededEventSequence,
		&i.DecidedAt,
	)
	return i, err
}

const getOutcomeAssessmentSubmission = `-- name: GetOutcomeAssessmentSubmission :one
SELECT submission.assessment_id, submission.event_sequence, submission.child_count, submission.submitted_at FROM outcome_assessment_submissions submission WHERE submission.assessment_id=?1
`

func (q *Queries) GetOutcomeAssessmentSubmission(ctx context.Context, assessmentID string) (OutcomeAssessmentSubmission, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeAssessmentSubmission, assessmentID)
	var i OutcomeAssessmentSubmission
	err := row.Scan(
		&i.AssessmentID,
		&i.EventSequence,
		&i.ChildCount,
		&i.SubmittedAt,
	)
	return i, err
}

const getOutcomeAssessmentSuccessorGovernance = `-- name: GetOutcomeAssessmentSuccessorGovernance :one
SELECT successor.id AS successor_assessment_id,successor.commitment_id,successor.review_state,
 governance.decision_event_sequence,governance.superseded_event_sequence,governance.decided_at
FROM outcome_assessments successor
JOIN outcome_assessment_governance governance ON governance.assessment_id=successor.id AND governance.decision='accepted'
WHERE governance.superseded_assessment_id=?1
`

type GetOutcomeAssessmentSuccessorGovernanceRow struct {
	SuccessorAssessmentID   string `json:"successor_assessment_id"`
	CommitmentID            string `json:"commitment_id"`
	ReviewState             string `json:"review_state"`
	DecisionEventSequence   int64  `json:"decision_event_sequence"`
	SupersededEventSequence *int64 `json:"superseded_event_sequence"`
	DecidedAt               string `json:"decided_at"`
}

func (q *Queries) GetOutcomeAssessmentSuccessorGovernance(ctx context.Context, assessmentID *string) (GetOutcomeAssessmentSuccessorGovernanceRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeAssessmentSuccessorGovernance, assessmentID)
	var i GetOutcomeAssessmentSuccessorGovernanceRow
	err := row.Scan(
		&i.SuccessorAssessmentID,
		&i.CommitmentID,
		&i.ReviewState,
		&i.DecisionEventSequence,
		&i.SupersededEventSequence,
		&i.DecidedAt,
	)
	return i, err
}

const getOutcomeCheckEvidence = `-- name: GetOutcomeCheckEvidence :one
SELECT evidence.id,evidence.requirement_id,evidence.requirement_revision,evidence.check_result_id,
 evidence.freshness_revision,evidence.class,evidence.effect,evidence.created_at,
 run.workspace_id,run.project_id,run.task_id,result.outcome,
 pinned.status AS pinned_freshness,current.status AS current_freshness,current.revision AS current_freshness_revision,
 requirement.status AS requirement_status,requirement.revision AS current_requirement_revision,
 (evidence.check_result_id=(
   SELECT latest_result.id FROM check_runs latest_run
   LEFT JOIN check_results latest_result ON latest_result.check_run_id=latest_run.id
   WHERE latest_run.requirement_id=evidence.requirement_id AND latest_run.requirement_revision=requirement.revision
   ORDER BY latest_run.created_at DESC,latest_run.id DESC LIMIT 1
 )) AS current_requirement_result,
 (SELECT event.sequence FROM events event WHERE event.workspace_id=run.workspace_id AND event.entity_type='check_result'
   AND event.entity_id=result.id AND event.entity_revision=evidence.freshness_revision
   AND event.type IN ('check.result_recorded','check.freshness_observed','check.freshness_stale')
   ORDER BY event.sequence DESC LIMIT 1) AS event_sequence
FROM check_requirement_evidence evidence
JOIN check_results result ON result.id=evidence.check_result_id
JOIN check_runs run ON run.id=result.check_run_id
JOIN task_check_requirements requirement ON requirement.id=evidence.requirement_id
JOIN check_result_freshness pinned ON pinned.check_result_id=result.id AND pinned.revision=evidence.freshness_revision
JOIN check_result_freshness current ON current.check_result_id=result.id
 AND current.revision=(SELECT MAX(latest.revision) FROM check_result_freshness latest WHERE latest.check_result_id=result.id)
WHERE run.workspace_id=?1 AND evidence.id=?2
`

type GetOutcomeCheckEvidenceParams struct {
	WorkspaceID string `json:"workspace_id"`
	EvidenceID  string `json:"evidence_id"`
}

type GetOutcomeCheckEvidenceRow struct {
	ID                         string      `json:"id"`
	RequirementID              string      `json:"requirement_id"`
	RequirementRevision        int64       `json:"requirement_revision"`
	CheckResultID              string      `json:"check_result_id"`
	FreshnessRevision          int64       `json:"freshness_revision"`
	Class                      string      `json:"class"`
	Effect                     string      `json:"effect"`
	CreatedAt                  string      `json:"created_at"`
	WorkspaceID                string      `json:"workspace_id"`
	ProjectID                  string      `json:"project_id"`
	TaskID                     string      `json:"task_id"`
	Outcome                    string      `json:"outcome"`
	PinnedFreshness            string      `json:"pinned_freshness"`
	CurrentFreshness           string      `json:"current_freshness"`
	CurrentFreshnessRevision   int64       `json:"current_freshness_revision"`
	RequirementStatus          string      `json:"requirement_status"`
	CurrentRequirementRevision int64       `json:"current_requirement_revision"`
	CurrentRequirementResult   interface{} `json:"current_requirement_result"`
	EventSequence              int64       `json:"event_sequence"`
}

func (q *Queries) GetOutcomeCheckEvidence(ctx context.Context, arg GetOutcomeCheckEvidenceParams) (GetOutcomeCheckEvidenceRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeCheckEvidence, arg.WorkspaceID, arg.EvidenceID)
	var i GetOutcomeCheckEvidenceRow
	err := row.Scan(
		&i.ID,
		&i.RequirementID,
		&i.RequirementRevision,
		&i.CheckResultID,
		&i.FreshnessRevision,
		&i.Class,
		&i.Effect,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TaskID,
		&i.Outcome,
		&i.PinnedFreshness,
		&i.CurrentFreshness,
		&i.CurrentFreshnessRevision,
		&i.RequirementStatus,
		&i.CurrentRequirementRevision,
		&i.CurrentRequirementResult,
		&i.EventSequence,
	)
	return i, err
}

const getOutcomeCommitmentReceipt = `-- name: GetOutcomeCommitmentReceipt :one
SELECT receipt.commitment_id, receipt.event_sequence, receipt.created_at FROM outcome_commitment_receipts receipt WHERE receipt.commitment_id=?1
`

func (q *Queries) GetOutcomeCommitmentReceipt(ctx context.Context, commitmentID string) (OutcomeCommitmentReceipt, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeCommitmentReceipt, commitmentID)
	var i OutcomeCommitmentReceipt
	err := row.Scan(&i.CommitmentID, &i.EventSequence, &i.CreatedAt)
	return i, err
}

const getOutcomeCommitmentScope = `-- name: GetOutcomeCommitmentScope :one
SELECT task.workspace_id,task.project_id,task.objective_id,task.revision AS task_revision,
 objective.revision AS objective_revision,task.status AS task_status,objective.status AS objective_status
FROM tasks task JOIN objectives objective ON objective.id=task.objective_id
WHERE task.workspace_id=?1 AND task.id=?2
 AND objective.workspace_id=task.workspace_id AND objective.project_id=task.project_id
`

type GetOutcomeCommitmentScopeParams struct {
	WorkspaceID string `json:"workspace_id"`
	TaskID      string `json:"task_id"`
}

type GetOutcomeCommitmentScopeRow struct {
	WorkspaceID       string  `json:"workspace_id"`
	ProjectID         string  `json:"project_id"`
	ObjectiveID       *string `json:"objective_id"`
	TaskRevision      int64   `json:"task_revision"`
	ObjectiveRevision int64   `json:"objective_revision"`
	TaskStatus        string  `json:"task_status"`
	ObjectiveStatus   string  `json:"objective_status"`
}

func (q *Queries) GetOutcomeCommitmentScope(ctx context.Context, arg GetOutcomeCommitmentScopeParams) (GetOutcomeCommitmentScopeRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeCommitmentScope, arg.WorkspaceID, arg.TaskID)
	var i GetOutcomeCommitmentScopeRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.TaskRevision,
		&i.ObjectiveRevision,
		&i.TaskStatus,
		&i.ObjectiveStatus,
	)
	return i, err
}

const getOutcomeHandoffEvidence = `-- name: GetOutcomeHandoffEvidence :one
SELECT handoff.id,handoff.run_id,handoff.task_id,handoff.summary,handoff.evidence_json,handoff.created_at,
 run.revision AS run_revision,run.status AS run_status,
 (SELECT event.sequence FROM events event WHERE event.workspace_id=run.workspace_id AND event.entity_type='task'
   AND event.type='task.handoff_recorded' AND json_extract(event.data_json,'$.handoff_id')=handoff.id
   ORDER BY event.sequence DESC LIMIT 1) AS event_sequence,
 (SELECT event.entity_revision FROM events event WHERE event.workspace_id=run.workspace_id AND event.entity_type='task'
   AND event.type='task.handoff_recorded' AND json_extract(event.data_json,'$.handoff_id')=handoff.id
   ORDER BY event.sequence DESC LIMIT 1) AS source_revision
FROM run_handoffs handoff JOIN runs run ON run.id=handoff.run_id
WHERE run.workspace_id=?1 AND handoff.id=?2
`

type GetOutcomeHandoffEvidenceParams struct {
	WorkspaceID string `json:"workspace_id"`
	HandoffID   string `json:"handoff_id"`
}

type GetOutcomeHandoffEvidenceRow struct {
	ID             string `json:"id"`
	RunID          string `json:"run_id"`
	TaskID         string `json:"task_id"`
	Summary        string `json:"summary"`
	EvidenceJson   string `json:"evidence_json"`
	CreatedAt      string `json:"created_at"`
	RunRevision    int64  `json:"run_revision"`
	RunStatus      string `json:"run_status"`
	EventSequence  int64  `json:"event_sequence"`
	SourceRevision int64  `json:"source_revision"`
}

func (q *Queries) GetOutcomeHandoffEvidence(ctx context.Context, arg GetOutcomeHandoffEvidenceParams) (GetOutcomeHandoffEvidenceRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeHandoffEvidence, arg.WorkspaceID, arg.HandoffID)
	var i GetOutcomeHandoffEvidenceRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.Summary,
		&i.EvidenceJson,
		&i.CreatedAt,
		&i.RunRevision,
		&i.RunStatus,
		&i.EventSequence,
		&i.SourceRevision,
	)
	return i, err
}

const getOutcomeJournalEvent = `-- name: GetOutcomeJournalEvent :one
SELECT event.sequence, event.event_id, event.type, event.schema_version, event.occurred_at, event.recorded_at, event.actor_id, event.actor_type, event.workspace_id, event.entity_type, event.entity_id, event.entity_revision, event.correlation_id, event.causation_id, event.data_json FROM events event WHERE event.sequence=?1
`

func (q *Queries) GetOutcomeJournalEvent(ctx context.Context, eventSequence int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeJournalEvent, eventSequence)
	var i Event
	err := row.Scan(
		&i.Sequence,
		&i.EventID,
		&i.Type,
		&i.SchemaVersion,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorID,
		&i.ActorType,
		&i.WorkspaceID,
		&i.EntityType,
		&i.EntityID,
		&i.EntityRevision,
		&i.CorrelationID,
		&i.CausationID,
		&i.DataJson,
	)
	return i, err
}

const getOutcomeProjectorState = `-- name: GetOutcomeProjectorState :one
SELECT workspace_id, last_event_sequence, revision, updated_at FROM outcome_projector_state WHERE workspace_id=?1
`

func (q *Queries) GetOutcomeProjectorState(ctx context.Context, workspaceID string) (OutcomeProjectorState, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeProjectorState, workspaceID)
	var i OutcomeProjectorState
	err := row.Scan(
		&i.WorkspaceID,
		&i.LastEventSequence,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutcomeScopeObjective = `-- name: GetOutcomeScopeObjective :one
SELECT workspace_id,project_id,id FROM objectives
WHERE workspace_id=?1 AND id=?2
`

type GetOutcomeScopeObjectiveParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeID     string `json:"scope_id"`
}

type GetOutcomeScopeObjectiveRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetOutcomeScopeObjective(ctx context.Context, arg GetOutcomeScopeObjectiveParams) (GetOutcomeScopeObjectiveRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeScopeObjective, arg.WorkspaceID, arg.ScopeID)
	var i GetOutcomeScopeObjectiveRow
	err := row.Scan(&i.WorkspaceID, &i.ProjectID, &i.ID)
	return i, err
}

const getOutcomeScopeProject = `-- name: GetOutcomeScopeProject :one
SELECT workspace_id,id FROM projects
WHERE workspace_id=?1 AND id=?2
`

type GetOutcomeScopeProjectParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeID     string `json:"scope_id"`
}

type GetOutcomeScopeProjectRow struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetOutcomeScopeProject(ctx context.Context, arg GetOutcomeScopeProjectParams) (GetOutcomeScopeProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeScopeProject, arg.WorkspaceID, arg.ScopeID)
	var i GetOutcomeScopeProjectRow
	err := row.Scan(&i.WorkspaceID, &i.ID)
	return i, err
}

const getOutcomeScopeProjectByName = `-- name: GetOutcomeScopeProjectByName :one
SELECT workspace_id,id FROM projects
WHERE workspace_id=?1 AND name=?2
`

type GetOutcomeScopeProjectByNameParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeName   string `json:"scope_name"`
}

type GetOutcomeScopeProjectByNameRow struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetOutcomeScopeProjectByName(ctx context.Context, arg GetOutcomeScopeProjectByNameParams) (GetOutcomeScopeProjectByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeScopeProjectByName, arg.WorkspaceID, arg.ScopeName)
	var i GetOutcomeScopeProjectByNameRow
	err := row.Scan(&i.WorkspaceID, &i.ID)
	return i, err
}

const getOutcomeScopeTask = `-- name: GetOutcomeScopeTask :one
SELECT workspace_id,project_id,objective_id,id FROM tasks
WHERE workspace_id=?1 AND id=?2
`

type GetOutcomeScopeTaskParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeID     string `json:"scope_id"`
}

type GetOutcomeScopeTaskRow struct {
	WorkspaceID string  `json:"workspace_id"`
	ProjectID   string  `json:"project_id"`
	ObjectiveID *string `json:"objective_id"`
	ID          string  `json:"id"`
}

func (q *Queries) GetOutcomeScopeTask(ctx context.Context, arg GetOutcomeScopeTaskParams) (GetOutcomeScopeTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeScopeTask, arg.WorkspaceID, arg.ScopeID)
	var i GetOutcomeScopeTaskRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.ID,
	)
	return i, err
}

const getOutcomeTaskRevision = `-- name: GetOutcomeTaskRevision :one
SELECT task.workspace_id,task.project_id,task.objective_id,task.revision,
 (SELECT event.sequence FROM events event WHERE event.workspace_id=task.workspace_id AND event.entity_type='task' AND event.entity_id=task.id AND event.entity_revision=task.revision ORDER BY event.sequence DESC LIMIT 1) AS event_sequence
FROM tasks task
WHERE task.workspace_id=?1 AND task.id=?2
`

type GetOutcomeTaskRevisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	TaskID      string `json:"task_id"`
}

type GetOutcomeTaskRevisionRow struct {
	WorkspaceID   string  `json:"workspace_id"`
	ProjectID     string  `json:"project_id"`
	ObjectiveID   *string `json:"objective_id"`
	Revision      int64   `json:"revision"`
	EventSequence int64   `json:"event_sequence"`
}

func (q *Queries) GetOutcomeTaskRevision(ctx context.Context, arg GetOutcomeTaskRevisionParams) (GetOutcomeTaskRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeTaskRevision, arg.WorkspaceID, arg.TaskID)
	var i GetOutcomeTaskRevisionRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.Revision,
		&i.EventSequence,
	)
	return i, err
}

const getOwnerCheckpoint = `-- name: GetOwnerCheckpoint :one
SELECT id, workspace_id, scope_type, scope_id, event_sequence, created_at, created_by FROM owner_checkpoints WHERE workspace_id=?1 AND id=?2
`

type GetOwnerCheckpointParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetOwnerCheckpoint(ctx context.Context, arg GetOwnerCheckpointParams) (OwnerCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getOwnerCheckpoint, arg.WorkspaceID, arg.ID)
	var i OwnerCheckpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.EventSequence,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertDeliverableCommitment = `-- name: InsertDeliverableCommitment :exec
INSERT INTO deliverable_commitments(
 id,workspace_id,project_id,objective_id,task_id,commitment_key,title,description,
 acceptance_criteria_json,content_json,content_sha256,created_at,created_by
) VALUES(
 ?1,?2,?3,?4,?5,
 ?6,?7,?8,?9,
 ?10,?11,?12,'local-owner'
)
`

type InsertDeliverableCommitmentParams struct {
	ID                     string `json:"id"`
	WorkspaceID            string `json:"workspace_id"`
	ProjectID              string `json:"project_id"`
	ObjectiveID            string `json:"objective_id"`
	TaskID                 string `json:"task_id"`
	CommitmentKey          string `json:"commitment_key"`
	Title                  string `json:"title"`
	Description            string `json:"description"`
	AcceptanceCriteriaJson string `json:"acceptance_criteria_json"`
	ContentJson            string `json:"content_json"`
	ContentSha256          string `json:"content_sha256"`
	CreatedAt              string `json:"created_at"`
}

func (q *Queries) InsertDeliverableCommitment(ctx context.Context, arg InsertDeliverableCommitmentParams) error {
	_, err := q.db.ExecContext(ctx, insertDeliverableCommitment,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
		arg.CommitmentKey,
		arg.Title,
		arg.Description,
		arg.AcceptanceCriteriaJson,
		arg.ContentJson,
		arg.ContentSha256,
		arg.CreatedAt,
	)
	return err
}

const insertManagementBriefing = `-- name: InsertManagementBriefing :exec
INSERT INTO management_briefings(
 id,revision,workspace_id,scope_type,scope_id,event_cursor,cutoff_event_sequence,checkpoint_id,
 since_event_sequence,evaluated_at,caught_up,unknown_event_type,unknown_event_sequence,
 content_json,content_sha256,byte_size,created_at
) VALUES(
 ?1,?2,?3,?4,?5,
 ?6,?7,?8,?9,
 ?10,?11,NULLIF(?12,''),NULLIF(?13,0),
 ?14,?15,?16,?17
)
`

type InsertManagementBriefingParams struct {
	ID                   string      `json:"id"`
	Revision             int64       `json:"revision"`
	WorkspaceID          string      `json:"workspace_id"`
	ScopeType            string      `json:"scope_type"`
	ScopeID              string      `json:"scope_id"`
	EventCursor          int64       `json:"event_cursor"`
	CutoffEventSequence  int64       `json:"cutoff_event_sequence"`
	CheckpointID         string      `json:"checkpoint_id"`
	SinceEventSequence   int64       `json:"since_event_sequence"`
	EvaluatedAt          string      `json:"evaluated_at"`
	CaughtUp             int64       `json:"caught_up"`
	UnknownEventType     interface{} `json:"unknown_event_type"`
	UnknownEventSequence interface{} `json:"unknown_event_sequence"`
	ContentJson          string      `json:"content_json"`
	ContentSha256        string      `json:"content_sha256"`
	ByteSize             int64       `json:"byte_size"`
	CreatedAt            string      `json:"created_at"`
}

func (q *Queries) InsertManagementBriefing(ctx context.Context, arg InsertManagementBriefingParams) error {
	_, err := q.db.ExecContext(ctx, insertManagementBriefing,
		arg.ID,
		arg.Revision,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.EventCursor,
		arg.CutoffEventSequence,
		arg.CheckpointID,
		arg.SinceEventSequence,
		arg.EvaluatedAt,
		arg.CaughtUp,
		arg.UnknownEventType,
		arg.UnknownEventSequence,
		arg.ContentJson,
		arg.ContentSha256,
		arg.ByteSize,
		arg.CreatedAt,
	)
	return err
}

const insertManagementBriefingClaim = `-- name: InsertManagementBriefingClaim :exec
INSERT INTO management_briefing_claims(
 briefing_id,ordinal,claim_id,semantic_key,kind,urgency,summary,status,project_id,source_event_sequence,claim_json
) VALUES(
 ?1,?2,?3,?4,?5,?6,
 ?7,?8,NULLIF(?9,''),?10,?11
)
`

type InsertManagementBriefingClaimParams struct {
	BriefingID          string      `json:"briefing_id"`
	Ordinal             int64       `json:"ordinal"`
	ClaimID             string      `json:"claim_id"`
	SemanticKey         string      `json:"semantic_key"`
	Kind                string      `json:"kind"`
	Urgency             string      `json:"urgency"`
	Summary             string      `json:"summary"`
	Status              string      `json:"status"`
	ProjectID           interface{} `json:"project_id"`
	SourceEventSequence int64       `json:"source_event_sequence"`
	ClaimJson           string      `json:"claim_json"`
}

func (q *Queries) InsertManagementBriefingClaim(ctx context.Context, arg InsertManagementBriefingClaimParams) error {
	_, err := q.db.ExecContext(ctx, insertManagementBriefingClaim,
		arg.BriefingID,
		arg.Ordinal,
		arg.ClaimID,
		arg.SemanticKey,
		arg.Kind,
		arg.Urgency,
		arg.Summary,
		arg.Status,
		arg.ProjectID,
		arg.SourceEventSequence,
		arg.ClaimJson,
	)
	return err
}

const insertManagementBriefingClaimSource = `-- name: InsertManagementBriefingClaimSource :exec
INSERT INTO management_briefing_claim_sources(
 briefing_id,claim_id,ordinal,entity_type,entity_id,entity_revision,content_sha256,event_sequence,
 evidence_class,evidence_effect,pinned_freshness,current_freshness
) VALUES(
 ?1,?2,?3,?4,?5,
 ?6,?7,?8,
 ?9,?10,?11,?12
)
`

type InsertManagementBriefingClaimSourceParams struct {
	BriefingID       string `json:"briefing_id"`
	ClaimID          string `json:"claim_id"`
	Ordinal          int64  `json:"ordinal"`
	EntityType       string `json:"entity_type"`
	EntityID         string `json:"entity_id"`
	EntityRevision   int64  `json:"entity_revision"`
	ContentSha256    string `json:"content_sha256"`
	EventSequence    int64  `json:"event_sequence"`
	EvidenceClass    string `json:"evidence_class"`
	EvidenceEffect   string `json:"evidence_effect"`
	PinnedFreshness  string `json:"pinned_freshness"`
	CurrentFreshness string `json:"current_freshness"`
}

func (q *Queries) InsertManagementBriefingClaimSource(ctx context.Context, arg InsertManagementBriefingClaimSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertManagementBriefingClaimSource,
		arg.BriefingID,
		arg.ClaimID,
		arg.Ordinal,
		arg.EntityType,
		arg.EntityID,
		arg.EntityRevision,
		arg.ContentSha256,
		arg.EventSequence,
		arg.EvidenceClass,
		arg.EvidenceEffect,
		arg.PinnedFreshness,
		arg.CurrentFreshness,
	)
	return err
}

const insertManagementBriefingReceipt = `-- name: InsertManagementBriefingReceipt :exec
INSERT INTO management_briefing_receipts(briefing_id,claim_count,source_count,sealed_at)
VALUES(?1,?2,?3,?4)
`

type InsertManagementBriefingReceiptParams struct {
	BriefingID  string `json:"briefing_id"`
	ClaimCount  int64  `json:"claim_count"`
	SourceCount int64  `json:"source_count"`
	SealedAt    string `json:"sealed_at"`
}

func (q *Queries) InsertManagementBriefingReceipt(ctx context.Context, arg InsertManagementBriefingReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertManagementBriefingReceipt,
		arg.BriefingID,
		arg.ClaimCount,
		arg.SourceCount,
		arg.SealedAt,
	)
	return err
}

const insertOutcomeAssessment = `-- name: InsertOutcomeAssessment :exec
INSERT INTO outcome_assessments(
 id,workspace_id,project_id,objective_id,task_id,commitment_id,revision,state_revision,
 review_state,conclusion,delivered_scope_json,unmet_scope_json,content_json,content_sha256,
 supersedes_assessment_id,proposed_at,proposed_by,decided_at,decided_by,decision_note
) VALUES(
 ?1,?2,?3,?4,?5,
 ?6,?7,1,'proposed',?8,
 ?9,?10,?11,?12,
 NULLIF(?13,''),?14,'local-owner',NULL,NULL,NULL
)
`

type InsertOutcomeAssessmentParams struct {
	ID                     string      `json:"id"`
	WorkspaceID            string      `json:"workspace_id"`
	ProjectID              string      `json:"project_id"`
	ObjectiveID            string      `json:"objective_id"`
	TaskID                 string      `json:"task_id"`
	CommitmentID           string      `json:"commitment_id"`
	Revision               int64       `json:"revision"`
	Conclusion             string      `json:"conclusion"`
	DeliveredScopeJson     string      `json:"delivered_scope_json"`
	UnmetScopeJson         string      `json:"unmet_scope_json"`
	ContentJson            string      `json:"content_json"`
	ContentSha256          string      `json:"content_sha256"`
	SupersedesAssessmentID interface{} `json:"supersedes_assessment_id"`
	ProposedAt             string      `json:"proposed_at"`
}

func (q *Queries) InsertOutcomeAssessment(ctx context.Context, arg InsertOutcomeAssessmentParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessment,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
		arg.CommitmentID,
		arg.Revision,
		arg.Conclusion,
		arg.DeliveredScopeJson,
		arg.UnmetScopeJson,
		arg.ContentJson,
		arg.ContentSha256,
		arg.SupersedesAssessmentID,
		arg.ProposedAt,
	)
	return err
}

const insertOutcomeAssessmentAcceptanceBasis = `-- name: InsertOutcomeAssessmentAcceptanceBasis :exec
INSERT INTO outcome_assessment_acceptance_basis(assessment_id,event_sequence,source_sha256,created_at,created_by)
VALUES(?1,?2,?3,?4,'local-owner')
`

type InsertOutcomeAssessmentAcceptanceBasisParams struct {
	AssessmentID  string `json:"assessment_id"`
	EventSequence int64  `json:"event_sequence"`
	SourceSha256  string `json:"source_sha256"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertOutcomeAssessmentAcceptanceBasis(ctx context.Context, arg InsertOutcomeAssessmentAcceptanceBasisParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentAcceptanceBasis,
		arg.AssessmentID,
		arg.EventSequence,
		arg.SourceSha256,
		arg.CreatedAt,
	)
	return err
}

const insertOutcomeAssessmentDecisionRef = `-- name: InsertOutcomeAssessmentDecisionRef :exec
INSERT INTO outcome_assessment_decision_refs(
 assessment_id,ordinal,revision_id,content_sha256,event_sequence
) VALUES(?1,?2,?3,?4,?5)
`

type InsertOutcomeAssessmentDecisionRefParams struct {
	AssessmentID  string `json:"assessment_id"`
	Ordinal       int64  `json:"ordinal"`
	RevisionID    string `json:"revision_id"`
	ContentSha256 string `json:"content_sha256"`
	EventSequence int64  `json:"event_sequence"`
}

func (q *Queries) InsertOutcomeAssessmentDecisionRef(ctx context.Context, arg InsertOutcomeAssessmentDecisionRefParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentDecisionRef,
		arg.AssessmentID,
		arg.Ordinal,
		arg.RevisionID,
		arg.ContentSha256,
		arg.EventSequence,
	)
	return err
}

const insertOutcomeAssessmentDeviation = `-- name: InsertOutcomeAssessmentDeviation :exec
INSERT INTO outcome_assessment_deviations(assessment_id,ordinal,kind,summary,related_task_id,related_task_revision)
VALUES(?1,?2,?3,?4,NULLIF(?5,''),NULLIF(?6,0))
`

type InsertOutcomeAssessmentDeviationParams struct {
	AssessmentID        string      `json:"assessment_id"`
	Ordinal             int64       `json:"ordinal"`
	Kind                string      `json:"kind"`
	Summary             string      `json:"summary"`
	RelatedTaskID       interface{} `json:"related_task_id"`
	RelatedTaskRevision interface{} `json:"related_task_revision"`
}

func (q *Queries) InsertOutcomeAssessmentDeviation(ctx context.Context, arg InsertOutcomeAssessmentDeviationParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentDeviation,
		arg.AssessmentID,
		arg.Ordinal,
		arg.Kind,
		arg.Summary,
		arg.RelatedTaskID,
		arg.RelatedTaskRevision,
	)
	return err
}

const insertOutcomeAssessmentEffect = `-- name: InsertOutcomeAssessmentEffect :exec
INSERT INTO outcome_assessment_effects(assessment_id,ordinal,kind,direction,summary)
VALUES(?1,?2,?3,?4,?5)
`

type InsertOutcomeAssessmentEffectParams struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Kind         string `json:"kind"`
	Direction    string `json:"direction"`
	Summary      string `json:"summary"`
}

func (q *Queries) InsertOutcomeAssessmentEffect(ctx context.Context, arg InsertOutcomeAssessmentEffectParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentEffect,
		arg.AssessmentID,
		arg.Ordinal,
		arg.Kind,
		arg.Direction,
		arg.Summary,
	)
	return err
}

const insertOutcomeAssessmentEvidenceRef = `-- name: InsertOutcomeAssessmentEvidenceRef :exec
INSERT INTO outcome_assessment_evidence_refs(
 assessment_id,ordinal,source_type,source_id,source_revision,source_sha256,event_sequence,class,effect,pinned_freshness
) VALUES(
 ?1,?2,?3,?4,?5,
 ?6,?7,?8,?9,?10
)
`

type InsertOutcomeAssessmentEvidenceRefParams struct {
	AssessmentID    string `json:"assessment_id"`
	Ordinal         int64  `json:"ordinal"`
	SourceType      string `json:"source_type"`
	SourceID        string `json:"source_id"`
	SourceRevision  int64  `json:"source_revision"`
	SourceSha256    string `json:"source_sha256"`
	EventSequence   int64  `json:"event_sequence"`
	Class           string `json:"class"`
	Effect          string `json:"effect"`
	PinnedFreshness string `json:"pinned_freshness"`
}

func (q *Queries) InsertOutcomeAssessmentEvidenceRef(ctx context.Context, arg InsertOutcomeAssessmentEvidenceRefParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentEvidenceRef,
		arg.AssessmentID,
		arg.Ordinal,
		arg.SourceType,
		arg.SourceID,
		arg.SourceRevision,
		arg.SourceSha256,
		arg.EventSequence,
		arg.Class,
		arg.Effect,
		arg.PinnedFreshness,
	)
	return err
}

const insertOutcomeAssessmentFollowUpTask = `-- name: InsertOutcomeAssessmentFollowUpTask :exec
INSERT INTO outcome_assessment_follow_up_tasks(assessment_id,ordinal,task_id,task_revision,event_sequence)
VALUES(?1,?2,?3,?4,?5)
`

type InsertOutcomeAssessmentFollowUpTaskParams struct {
	AssessmentID  string `json:"assessment_id"`
	Ordinal       int64  `json:"ordinal"`
	TaskID        string `json:"task_id"`
	TaskRevision  int64  `json:"task_revision"`
	EventSequence int64  `json:"event_sequence"`
}

func (q *Queries) InsertOutcomeAssessmentFollowUpTask(ctx context.Context, arg InsertOutcomeAssessmentFollowUpTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentFollowUpTask,
		arg.AssessmentID,
		arg.Ordinal,
		arg.TaskID,
		arg.TaskRevision,
		arg.EventSequence,
	)
	return err
}

const insertOutcomeAssessmentGovernance = `-- name: InsertOutcomeAssessmentGovernance :exec
INSERT INTO outcome_assessment_governance(
 assessment_id,decision,decision_event_sequence,superseded_assessment_id,superseded_event_sequence,decided_at
) VALUES(
 ?1,?2,?3,
 NULLIF(?4,''),NULLIF(?5,0),?6
)
`

type InsertOutcomeAssessmentGovernanceParams struct {
	AssessmentID            string      `json:"assessment_id"`
	Decision                string      `json:"decision"`
	DecisionEventSequence   int64       `json:"decision_event_sequence"`
	SupersededAssessmentID  interface{} `json:"superseded_assessment_id"`
	SupersededEventSequence interface{} `json:"superseded_event_sequence"`
	DecidedAt               string      `json:"decided_at"`
}

func (q *Queries) InsertOutcomeAssessmentGovernance(ctx context.Context, arg InsertOutcomeAssessmentGovernanceParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentGovernance,
		arg.AssessmentID,
		arg.Decision,
		arg.DecisionEventSequence,
		arg.SupersededAssessmentID,
		arg.SupersededEventSequence,
		arg.DecidedAt,
	)
	return err
}

const insertOutcomeAssessmentOwnerAttention = `-- name: InsertOutcomeAssessmentOwnerAttention :exec
INSERT INTO outcome_assessment_owner_attention(assessment_id,ordinal,urgency,action,reason)
VALUES(?1,?2,?3,?4,?5)
`

type InsertOutcomeAssessmentOwnerAttentionParams struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Urgency      string `json:"urgency"`
	Action       string `json:"action"`
	Reason       string `json:"reason"`
}

func (q *Queries) InsertOutcomeAssessmentOwnerAttention(ctx context.Context, arg InsertOutcomeAssessmentOwnerAttentionParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentOwnerAttention,
		arg.AssessmentID,
		arg.Ordinal,
		arg.Urgency,
		arg.Action,
		arg.Reason,
	)
	return err
}

const insertOutcomeAssessmentRisk = `-- name: InsertOutcomeAssessmentRisk :exec
INSERT INTO outcome_assessment_risks(assessment_id,ordinal,severity,summary,mitigation)
VALUES(?1,?2,?3,?4,?5)
`

type InsertOutcomeAssessmentRiskParams struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Severity     string `json:"severity"`
	Summary      string `json:"summary"`
	Mitigation   string `json:"mitigation"`
}

func (q *Queries) InsertOutcomeAssessmentRisk(ctx context.Context, arg InsertOutcomeAssessmentRiskParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentRisk,
		arg.AssessmentID,
		arg.Ordinal,
		arg.Severity,
		arg.Summary,
		arg.Mitigation,
	)
	return err
}

const insertOutcomeAssessmentSubmission = `-- name: InsertOutcomeAssessmentSubmission :exec
INSERT INTO outcome_assessment_submissions(assessment_id,event_sequence,child_count,submitted_at)
VALUES(?1,?2,?3,?4)
`

type InsertOutcomeAssessmentSubmissionParams struct {
	AssessmentID  string `json:"assessment_id"`
	EventSequence int64  `json:"event_sequence"`
	ChildCount    int64  `json:"child_count"`
	SubmittedAt   string `json:"submitted_at"`
}

func (q *Queries) InsertOutcomeAssessmentSubmission(ctx context.Context, arg InsertOutcomeAssessmentSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentSubmission,
		arg.AssessmentID,
		arg.EventSequence,
		arg.ChildCount,
		arg.SubmittedAt,
	)
	return err
}

const insertOutcomeAssessmentUnknown = `-- name: InsertOutcomeAssessmentUnknown :exec
INSERT INTO outcome_assessment_unknowns(assessment_id,ordinal,summary)
VALUES(?1,?2,?3)
`

type InsertOutcomeAssessmentUnknownParams struct {
	AssessmentID string `json:"assessment_id"`
	Ordinal      int64  `json:"ordinal"`
	Summary      string `json:"summary"`
}

func (q *Queries) InsertOutcomeAssessmentUnknown(ctx context.Context, arg InsertOutcomeAssessmentUnknownParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeAssessmentUnknown, arg.AssessmentID, arg.Ordinal, arg.Summary)
	return err
}

const insertOutcomeCommitmentReceipt = `-- name: InsertOutcomeCommitmentReceipt :exec
INSERT INTO outcome_commitment_receipts(commitment_id,event_sequence,created_at)
VALUES(?1,?2,?3)
`

type InsertOutcomeCommitmentReceiptParams struct {
	CommitmentID  string `json:"commitment_id"`
	EventSequence int64  `json:"event_sequence"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertOutcomeCommitmentReceipt(ctx context.Context, arg InsertOutcomeCommitmentReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeCommitmentReceipt, arg.CommitmentID, arg.EventSequence, arg.CreatedAt)
	return err
}

const insertOutcomeProjectorState = `-- name: InsertOutcomeProjectorState :exec
INSERT INTO outcome_projector_state(workspace_id,last_event_sequence,revision,updated_at)
VALUES(?1,0,1,?2)
`

type InsertOutcomeProjectorStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) InsertOutcomeProjectorState(ctx context.Context, arg InsertOutcomeProjectorStateParams) error {
	_, err := q.db.ExecContext(ctx, insertOutcomeProjectorState, arg.WorkspaceID, arg.UpdatedAt)
	return err
}

const insertOwnerCheckpoint = `-- name: InsertOwnerCheckpoint :exec
INSERT INTO owner_checkpoints(id,workspace_id,scope_type,scope_id,event_sequence,created_at,created_by)
VALUES(?1,?2,?3,?4,?5,?6,'local-owner')
`

type InsertOwnerCheckpointParams struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	ScopeType     string `json:"scope_type"`
	ScopeID       string `json:"scope_id"`
	EventSequence int64  `json:"event_sequence"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertOwnerCheckpoint(ctx context.Context, arg InsertOwnerCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertOwnerCheckpoint,
		arg.ID,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.EventSequence,
		arg.CreatedAt,
	)
	return err
}

const listAcceptedOutcomeAssessmentClaims = `-- name: ListAcceptedOutcomeAssessmentClaims :many
SELECT assessment.id AS assessment_id,assessment.state_revision,assessment.review_state,assessment.conclusion,assessment.content_sha256,
 assessment.project_id,assessment.objective_id,assessment.task_id,assessment.commitment_id,
 commitment.title AS commitment_title,commitment.content_sha256 AS commitment_sha256,
 receipt.event_sequence AS commitment_event_sequence,
 governance.decision_event_sequence AS event_sequence,basis.source_sha256 AS acceptance_basis_sha256,
 governance.superseded_assessment_id,governance.superseded_event_sequence,
 prior.content_sha256 AS superseded_content_sha256,prior.state_revision AS superseded_state_revision
FROM outcome_assessments assessment
JOIN deliverable_commitments commitment ON commitment.id=assessment.commitment_id
JOIN outcome_commitment_receipts receipt ON receipt.commitment_id=commitment.id
JOIN outcome_assessment_governance governance ON governance.assessment_id=assessment.id AND governance.decision='accepted'
JOIN outcome_assessment_acceptance_basis basis ON basis.assessment_id=assessment.id AND basis.event_sequence=governance.decision_event_sequence
LEFT JOIN outcome_assessments prior ON prior.id=governance.superseded_assessment_id
WHERE assessment.workspace_id=?1 AND assessment.review_state='accepted'
 AND governance.decision_event_sequence<=?2
 AND (CAST(?3 AS TEXT)='' OR assessment.project_id=?3)
 AND (CAST(?4 AS TEXT)='' OR assessment.objective_id=?4)
 AND (CAST(?5 AS TEXT)='' OR assessment.task_id=?5)
ORDER BY governance.decision_event_sequence DESC,assessment.id
`

type ListAcceptedOutcomeAssessmentClaimsParams struct {
	WorkspaceID string `json:"workspace_id"`
	EventCursor int64  `json:"event_cursor"`
	ProjectID   string `json:"project_id"`
	ObjectiveID string `json:"objective_id"`
	TaskID      string `json:"task_id"`
}

type ListAcceptedOutcomeAssessmentClaimsRow struct {
	AssessmentID            string  `json:"assessment_id"`
	StateRevision           int64   `json:"state_revision"`
	ReviewState             string  `json:"review_state"`
	Conclusion              string  `json:"conclusion"`
	ContentSha256           string  `json:"content_sha256"`
	ProjectID               string  `json:"project_id"`
	ObjectiveID             string  `json:"objective_id"`
	TaskID                  string  `json:"task_id"`
	CommitmentID            string  `json:"commitment_id"`
	CommitmentTitle         string  `json:"commitment_title"`
	CommitmentSha256        string  `json:"commitment_sha256"`
	CommitmentEventSequence int64   `json:"commitment_event_sequence"`
	EventSequence           int64   `json:"event_sequence"`
	AcceptanceBasisSha256   string  `json:"acceptance_basis_sha256"`
	SupersededAssessmentID  *string `json:"superseded_assessment_id"`
	SupersededEventSequence *int64  `json:"superseded_event_sequence"`
	SupersededContentSha256 *string `json:"superseded_content_sha256"`
	SupersededStateRevision *int64  `json:"superseded_state_revision"`
}

func (q *Queries) ListAcceptedOutcomeAssessmentClaims(ctx context.Context, arg ListAcceptedOutcomeAssessmentClaimsParams) ([]ListAcceptedOutcomeAssessmentClaimsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedOutcomeAssessmentClaims,
		arg.WorkspaceID,
		arg.EventCursor,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcceptedOutcomeAssessmentClaimsRow{}
	for rows.Next() {
		var i ListAcceptedOutcomeAssessmentClaimsRow
		if err := rows.Scan(
			&i.AssessmentID,
			&i.StateRevision,
			&i.ReviewState,
			&i.Conclusion,
			&i.ContentSha256,
			&i.ProjectID,
			&i.ObjectiveID,
			&i.TaskID,
			&i.CommitmentID,
			&i.CommitmentTitle,
			&i.CommitmentSha256,
			&i.CommitmentEventSequence,
			&i.EventSequence,
			&i.AcceptanceBasisSha256,
			&i.SupersededAssessmentID,
			&i.SupersededEventSequence,
			&i.SupersededContentSha256,
			&i.SupersededStateRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentAcceptedEvent = `-- name: ListAssessmentAcceptedEvent :one
SELECT event.sequence FROM events event WHERE event.workspace_id=?1
 AND event.entity_type='outcome_assessment' AND event.entity_id=?2
 AND event.type='outcome.assessment_accepted' ORDER BY event.sequence DESC LIMIT 1
`

type ListAssessmentAcceptedEventParams struct {
	WorkspaceID  string `json:"workspace_id"`
	AssessmentID string `json:"assessment_id"`
}

func (q *Queries) ListAssessmentAcceptedEvent(ctx context.Context, arg ListAssessmentAcceptedEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, listAssessmentAcceptedEvent, arg.WorkspaceID, arg.AssessmentID)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const listDeliverableCommitments = `-- name: ListDeliverableCommitments :many
SELECT commitment.id, commitment.workspace_id, commitment.project_id, commitment.objective_id, commitment.task_id, commitment.commitment_key, commitment.title, commitment.description, commitment.acceptance_criteria_json, commitment.content_json, commitment.content_sha256, commitment.created_at, commitment.created_by FROM deliverable_commitments commitment
WHERE commitment.workspace_id=?1
 AND (CAST(?2 AS TEXT)='' OR commitment.project_id=?2)
 AND (CAST(?3 AS TEXT)='' OR commitment.objective_id=?3)
 AND (CAST(?4 AS TEXT)='' OR commitment.task_id=?4)
ORDER BY commitment.project_id,commitment.objective_id,commitment.task_id,commitment.commitment_key,commitment.id
LIMIT ?5
`

type ListDeliverableCommitmentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	ObjectiveID string `json:"objective_id"`
	TaskID      string `json:"task_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListDeliverableCommitments(ctx context.Context, arg ListDeliverableCommitmentsParams) ([]DeliverableCommitment, error) {
	rows, err := q.db.QueryContext(ctx, listDeliverableCommitments,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliverableCommitment{}
	for rows.Next() {
		var i DeliverableCommitment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ObjectiveID,
			&i.TaskID,
			&i.CommitmentKey,
			&i.Title,
			&i.Description,
			&i.AcceptanceCriteriaJson,
			&i.ContentJson,
			&i.ContentSha256,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementBriefingClaimSources = `-- name: ListManagementBriefingClaimSources :many
SELECT briefing_id, claim_id, ordinal, entity_type, entity_id, entity_revision, content_sha256, event_sequence, evidence_class, evidence_effect, pinned_freshness, current_freshness FROM management_briefing_claim_sources
WHERE briefing_id=?1 AND claim_id=?2 ORDER BY ordinal
`

type ListManagementBriefingClaimSourcesParams struct {
	BriefingID string `json:"briefing_id"`
	ClaimID    string `json:"claim_id"`
}

func (q *Queries) ListManagementBriefingClaimSources(ctx context.Context, arg ListManagementBriefingClaimSourcesParams) ([]ManagementBriefingClaimSource, error) {
	rows, err := q.db.QueryContext(ctx, listManagementBriefingClaimSources, arg.BriefingID, arg.ClaimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagementBriefingClaimSource{}
	for rows.Next() {
		var i ManagementBriefingClaimSource
		if err := rows.Scan(
			&i.BriefingID,
			&i.ClaimID,
			&i.Ordinal,
			&i.EntityType,
			&i.EntityID,
			&i.EntityRevision,
			&i.ContentSha256,
			&i.EventSequence,
			&i.EvidenceClass,
			&i.EvidenceEffect,
			&i.PinnedFreshness,
			&i.CurrentFreshness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementBriefingClaims = `-- name: ListManagementBriefingClaims :many
SELECT briefing_id, ordinal, claim_id, semantic_key, kind, urgency, summary, status, project_id, source_event_sequence, claim_json FROM management_briefing_claims WHERE briefing_id=?1 ORDER BY ordinal
`

func (q *Queries) ListManagementBriefingClaims(ctx context.Context, briefingID string) ([]ManagementBriefingClaim, error) {
	rows, err := q.db.QueryContext(ctx, listManagementBriefingClaims, briefingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagementBriefingClaim{}
	for rows.Next() {
		var i ManagementBriefingClaim
		if err := rows.Scan(
			&i.BriefingID,
			&i.Ordinal,
			&i.ClaimID,
			&i.SemanticKey,
			&i.Kind,
			&i.Urgency,
			&i.Summary,
			&i.Status,
			&i.ProjectID,
			&i.SourceEventSequence,
			&i.ClaimJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOutcomeContradictions = `-- name: ListOpenOutcomeContradictions :many
SELECT contradiction.id,contradiction.state_revision,contradiction.project_id,contradiction.report_note,
 contradiction.left_revision_id,contradiction.right_revision_id,contradiction.confirm_event_sequence AS event_sequence
FROM knowledge_contradictions contradiction
WHERE contradiction.workspace_id=?1 AND contradiction.status='open'
 AND contradiction.confirm_event_sequence<=?2
 AND (CAST(?3 AS TEXT)='' OR contradiction.project_id=?3)
ORDER BY contradiction.confirm_event_sequence DESC,contradiction.id
`

type ListOpenOutcomeContradictionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	EventCursor *int64 `json:"event_cursor"`
	ProjectID   string `json:"project_id"`
}

type ListOpenOutcomeContradictionsRow struct {
	ID              string `json:"id"`
	StateRevision   int64  `json:"state_revision"`
	ProjectID       string `json:"project_id"`
	ReportNote      string `json:"report_note"`
	LeftRevisionID  string `json:"left_revision_id"`
	RightRevisionID string `json:"right_revision_id"`
	EventSequence   *int64 `json:"event_sequence"`
}

func (q *Queries) ListOpenOutcomeContradictions(ctx context.Context, arg ListOpenOutcomeContradictionsParams) ([]ListOpenOutcomeContradictionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenOutcomeContradictions, arg.WorkspaceID, arg.EventCursor, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenOutcomeContradictionsRow{}
	for rows.Next() {
		var i ListOpenOutcomeContradictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StateRevision,
			&i.ProjectID,
			&i.ReportNote,
			&i.LeftRevisionID,
			&i.RightRevisionID,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentDecisionRefs = `-- name: ListOutcomeAssessmentDecisionRefs :many
SELECT assessment_id, ordinal, revision_id, content_sha256, event_sequence FROM outcome_assessment_decision_refs WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentDecisionRefs(ctx context.Context, assessmentID string) ([]OutcomeAssessmentDecisionRef, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentDecisionRefs, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentDecisionRef{}
	for rows.Next() {
		var i OutcomeAssessmentDecisionRef
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.RevisionID,
			&i.ContentSha256,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentDeviations = `-- name: ListOutcomeAssessmentDeviations :many
SELECT assessment_id, ordinal, kind, summary, related_task_id, related_task_revision FROM outcome_assessment_deviations WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentDeviations(ctx context.Context, assessmentID string) ([]OutcomeAssessmentDeviation, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentDeviations, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentDeviation{}
	for rows.Next() {
		var i OutcomeAssessmentDeviation
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.Kind,
			&i.Summary,
			&i.RelatedTaskID,
			&i.RelatedTaskRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentEffects = `-- name: ListOutcomeAssessmentEffects :many
SELECT assessment_id, ordinal, kind, direction, summary FROM outcome_assessment_effects WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentEffects(ctx context.Context, assessmentID string) ([]OutcomeAssessmentEffect, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentEffects, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentEffect{}
	for rows.Next() {
		var i OutcomeAssessmentEffect
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.Kind,
			&i.Direction,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentEvidenceRefs = `-- name: ListOutcomeAssessmentEvidenceRefs :many
SELECT assessment_id, ordinal, source_type, source_id, source_revision, source_sha256, event_sequence, class, effect, pinned_freshness FROM outcome_assessment_evidence_refs WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentEvidenceRefs(ctx context.Context, assessmentID string) ([]OutcomeAssessmentEvidenceRef, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentEvidenceRefs, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentEvidenceRef{}
	for rows.Next() {
		var i OutcomeAssessmentEvidenceRef
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.SourceType,
			&i.SourceID,
			&i.SourceRevision,
			&i.SourceSha256,
			&i.EventSequence,
			&i.Class,
			&i.Effect,
			&i.PinnedFreshness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentFollowUpTasks = `-- name: ListOutcomeAssessmentFollowUpTasks :many
SELECT assessment_id, ordinal, task_id, task_revision, event_sequence FROM outcome_assessment_follow_up_tasks WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentFollowUpTasks(ctx context.Context, assessmentID string) ([]OutcomeAssessmentFollowUpTask, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentFollowUpTasks, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentFollowUpTask{}
	for rows.Next() {
		var i OutcomeAssessmentFollowUpTask
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.TaskID,
			&i.TaskRevision,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentIDs = `-- name: ListOutcomeAssessmentIDs :many
SELECT assessment.id FROM outcome_assessments assessment
WHERE assessment.workspace_id=?1
 AND (CAST(?2 AS TEXT)='' OR assessment.project_id=?2)
 AND (CAST(?3 AS TEXT)='' OR assessment.objective_id=?3)
 AND (CAST(?4 AS TEXT)='' OR assessment.task_id=?4)
 AND (CAST(?5 AS TEXT)='' OR assessment.commitment_id=?5)
 AND (CAST(?6 AS TEXT)='' OR assessment.review_state=?6)
 AND (CAST(?7 AS TEXT)='' OR assessment.conclusion=?7)
ORDER BY assessment.project_id,assessment.objective_id,assessment.task_id,assessment.commitment_id,assessment.revision
LIMIT ?8
`

type ListOutcomeAssessmentIDsParams struct {
	WorkspaceID  string `json:"workspace_id"`
	ProjectID    string `json:"project_id"`
	ObjectiveID  string `json:"objective_id"`
	TaskID       string `json:"task_id"`
	CommitmentID string `json:"commitment_id"`
	ReviewState  string `json:"review_state"`
	Conclusion   string `json:"conclusion"`
	ResultLimit  int64  `json:"result_limit"`
}

func (q *Queries) ListOutcomeAssessmentIDs(ctx context.Context, arg ListOutcomeAssessmentIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentIDs,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
		arg.CommitmentID,
		arg.ReviewState,
		arg.Conclusion,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentOwnerAttention = `-- name: ListOutcomeAssessmentOwnerAttention :many
SELECT assessment_id, ordinal, urgency, "action", reason FROM outcome_assessment_owner_attention WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentOwnerAttention(ctx context.Context, assessmentID string) ([]OutcomeAssessmentOwnerAttention, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentOwnerAttention, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentOwnerAttention{}
	for rows.Next() {
		var i OutcomeAssessmentOwnerAttention
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.Urgency,
			&i.Action,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentRisks = `-- name: ListOutcomeAssessmentRisks :many
SELECT assessment_id, ordinal, severity, summary, mitigation FROM outcome_assessment_risks WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentRisks(ctx context.Context, assessmentID string) ([]OutcomeAssessmentRisk, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentRisks, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentRisk{}
	for rows.Next() {
		var i OutcomeAssessmentRisk
		if err := rows.Scan(
			&i.AssessmentID,
			&i.Ordinal,
			&i.Severity,
			&i.Summary,
			&i.Mitigation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeAssessmentUnknowns = `-- name: ListOutcomeAssessmentUnknowns :many
SELECT assessment_id, ordinal, summary FROM outcome_assessment_unknowns WHERE assessment_id=?1 ORDER BY ordinal
`

func (q *Queries) ListOutcomeAssessmentUnknowns(ctx context.Context, assessmentID string) ([]OutcomeAssessmentUnknown, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeAssessmentUnknowns, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutcomeAssessmentUnknown{}
	for rows.Next() {
		var i OutcomeAssessmentUnknown
		if err := rows.Scan(&i.AssessmentID, &i.Ordinal, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomeProjectorEvents = `-- name: ListOutcomeProjectorEvents :many
SELECT sequence,type FROM events WHERE workspace_id=?1
 AND sequence>?2 AND sequence<=?3
ORDER BY sequence LIMIT 1000
`

type ListOutcomeProjectorEventsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	AfterSequence  int64  `json:"after_sequence"`
	CutoffSequence int64  `json:"cutoff_sequence"`
}

type ListOutcomeProjectorEventsRow struct {
	Sequence int64  `json:"sequence"`
	Type     string `json:"type"`
}

func (q *Queries) ListOutcomeProjectorEvents(ctx context.Context, arg ListOutcomeProjectorEventsParams) ([]ListOutcomeProjectorEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomeProjectorEvents, arg.WorkspaceID, arg.AfterSequence, arg.CutoffSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutcomeProjectorEventsRow{}
	for rows.Next() {
		var i ListOutcomeProjectorEventsRow
		if err := rows.Scan(&i.Sequence, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerCheckpoints = `-- name: ListOwnerCheckpoints :many
SELECT id, workspace_id, scope_type, scope_id, event_sequence, created_at, created_by FROM owner_checkpoints WHERE workspace_id=?1
 AND (CAST(?2 AS TEXT)='' OR scope_type=?2)
 AND (CAST(?3 AS TEXT)='' OR scope_id=?3)
ORDER BY event_sequence DESC,id DESC LIMIT ?4
`

type ListOwnerCheckpointsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeType   string `json:"scope_type"`
	ScopeID     string `json:"scope_id"`
	ResultLimit int64  `json:"result_limit"`
}

func (q *Queries) ListOwnerCheckpoints(ctx context.Context, arg ListOwnerCheckpointsParams) ([]OwnerCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerCheckpoints,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnerCheckpoint{}
	for rows.Next() {
		var i OwnerCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.ScopeID,
			&i.EventSequence,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassessedOutcomeCommitments = `-- name: ListUnassessedOutcomeCommitments :many
SELECT commitment.id,commitment.project_id,commitment.objective_id,commitment.task_id,
 commitment.title,commitment.content_sha256,receipt.event_sequence
FROM deliverable_commitments commitment
JOIN outcome_commitment_receipts receipt ON receipt.commitment_id=commitment.id
WHERE commitment.workspace_id=?1
 AND receipt.event_sequence<=?2
 AND (CAST(?3 AS TEXT)='' OR commitment.project_id=?3)
 AND (CAST(?4 AS TEXT)='' OR commitment.objective_id=?4)
 AND (CAST(?5 AS TEXT)='' OR commitment.task_id=?5)
 AND NOT EXISTS(SELECT 1 FROM outcome_assessments assessment
  WHERE assessment.commitment_id=commitment.id AND assessment.review_state='accepted')
ORDER BY receipt.event_sequence DESC,commitment.id
`

type ListUnassessedOutcomeCommitmentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	EventCursor int64  `json:"event_cursor"`
	ProjectID   string `json:"project_id"`
	ObjectiveID string `json:"objective_id"`
	TaskID      string `json:"task_id"`
}

type ListUnassessedOutcomeCommitmentsRow struct {
	ID            string `json:"id"`
	ProjectID     string `json:"project_id"`
	ObjectiveID   string `json:"objective_id"`
	TaskID        string `json:"task_id"`
	Title         string `json:"title"`
	ContentSha256 string `json:"content_sha256"`
	EventSequence int64  `json:"event_sequence"`
}

func (q *Queries) ListUnassessedOutcomeCommitments(ctx context.Context, arg ListUnassessedOutcomeCommitmentsParams) ([]ListUnassessedOutcomeCommitmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnassessedOutcomeCommitments,
		arg.WorkspaceID,
		arg.EventCursor,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.TaskID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnassessedOutcomeCommitmentsRow{}
	for rows.Next() {
		var i ListUnassessedOutcomeCommitmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ObjectiveID,
			&i.TaskID,
			&i.Title,
			&i.ContentSha256,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxWorkspaceEventSequence = `-- name: MaxWorkspaceEventSequence :one
SELECT CAST(COALESCE(MAX(sequence),0) AS INTEGER) AS event_sequence FROM events
WHERE workspace_id=?1
`

func (q *Queries) MaxWorkspaceEventSequence(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxWorkspaceEventSequence, workspaceID)
	var event_sequence int64
	err := row.Scan(&event_sequence)
	return event_sequence, err
}

const nextManagementBriefingRevision = `-- name: NextManagementBriefingRevision :one
SELECT CAST(COALESCE(MAX(revision),0)+1 AS INTEGER) AS next_revision FROM management_briefings
WHERE workspace_id=?1 AND scope_type=?2 AND scope_id=?3
`

type NextManagementBriefingRevisionParams struct {
	WorkspaceID string `json:"workspace_id"`
	ScopeType   string `json:"scope_type"`
	ScopeID     string `json:"scope_id"`
}

func (q *Queries) NextManagementBriefingRevision(ctx context.Context, arg NextManagementBriefingRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextManagementBriefingRevision, arg.WorkspaceID, arg.ScopeType, arg.ScopeID)
	var next_revision int64
	err := row.Scan(&next_revision)
	return next_revision, err
}

const nextOutcomeAssessmentRevision = `-- name: NextOutcomeAssessmentRevision :one
SELECT CAST(COALESCE(MAX(revision),0)+1 AS INTEGER) AS next_revision
FROM outcome_assessments WHERE commitment_id=?1
`

func (q *Queries) NextOutcomeAssessmentRevision(ctx context.Context, commitmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextOutcomeAssessmentRevision, commitmentID)
	var next_revision int64
	err := row.Scan(&next_revision)
	return next_revision, err
}

const outcomeContradictionTouchesScopeDecision = `-- name: OutcomeContradictionTouchesScopeDecision :one
SELECT EXISTS(
 SELECT 1 FROM knowledge_revisions revision
 JOIN knowledge_items item ON item.id=revision.item_id
 WHERE revision.id IN (?1,?2)
  AND item.workspace_id=?3
  AND (
   (CAST(?4 AS TEXT)<>'' AND (item.task_scope_id IS NULL OR item.task_scope_id=?4))
   OR (CAST(?4 AS TEXT)='' AND CAST(?5 AS TEXT)<>'' AND
       (item.task_scope_id IS NULL OR item.task_scope_id IN (SELECT task.id FROM tasks task WHERE task.objective_id=?5)))
  )
) AS relevant
`

type OutcomeContradictionTouchesScopeDecisionParams struct {
	LeftRevisionID  string `json:"left_revision_id"`
	RightRevisionID string `json:"right_revision_id"`
	WorkspaceID     string `json:"workspace_id"`
	TaskID          string `json:"task_id"`
	ObjectiveID     string `json:"objective_id"`
}

func (q *Queries) OutcomeContradictionTouchesScopeDecision(ctx context.Context, arg OutcomeContradictionTouchesScopeDecisionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, outcomeContradictionTouchesScopeDecision,
		arg.LeftRevisionID,
		arg.RightRevisionID,
		arg.WorkspaceID,
		arg.TaskID,
		arg.ObjectiveID,
	)
	var relevant bool
	err := row.Scan(&relevant)
	return relevant, err
}

const outcomeDecisionHasOpenContradiction = `-- name: OutcomeDecisionHasOpenContradiction :one
SELECT EXISTS(
 SELECT 1 FROM knowledge_contradictions contradiction
 WHERE contradiction.workspace_id=?1 AND contradiction.status='open'
  AND (contradiction.left_revision_id=?2 OR contradiction.right_revision_id=?2)
) AS disputed
`

type OutcomeDecisionHasOpenContradictionParams struct {
	WorkspaceID string `json:"workspace_id"`
	RevisionID  string `json:"revision_id"`
}

func (q *Queries) OutcomeDecisionHasOpenContradiction(ctx context.Context, arg OutcomeDecisionHasOpenContradictionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, outcomeDecisionHasOpenContradiction, arg.WorkspaceID, arg.RevisionID)
	var disputed bool
	err := row.Scan(&disputed)
	return disputed, err
}

const outcomeHandoffIsIndependentReview = `-- name: OutcomeHandoffIsIndependentReview :one
SELECT EXISTS(
 SELECT 1 FROM run_handoffs handoff
 JOIN manager_proposal_effects effect ON effect.entity_type='task' AND effect.entity_id=handoff.task_id AND effect.effect_type='created'
 JOIN manager_proposal_actions action ON action.id=effect.action_id AND action.proposal_id=effect.proposal_id AND action.type='request_review'
 JOIN manager_proposals proposal ON proposal.id=effect.proposal_id AND proposal.status='accepted'
 WHERE handoff.id=?1 AND proposal.workspace_id=?2
   AND json_extract(action.payload_json,'$.task.task_id')=?3
) AS independent_review
`

type OutcomeHandoffIsIndependentReviewParams struct {
	HandoffID      string `json:"handoff_id"`
	WorkspaceID    string `json:"workspace_id"`
	AssessedTaskID string `json:"assessed_task_id"`
}

func (q *Queries) OutcomeHandoffIsIndependentReview(ctx context.Context, arg OutcomeHandoffIsIndependentReviewParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, outcomeHandoffIsIndependentReview, arg.HandoffID, arg.WorkspaceID, arg.AssessedTaskID)
	var independent_review bool
	err := row.Scan(&independent_review)
	return independent_review, err
}

const rejectOutcomeAssessmentProjection = `-- name: RejectOutcomeAssessmentProjection :execrows
UPDATE outcome_assessments
SET review_state='rejected',state_revision=state_revision+1,decided_at=?1,decided_by='local-owner',decision_note=NULLIF(?2,'')
WHERE workspace_id=?3 AND id=?4 AND review_state='proposed' AND state_revision=?5
`

type RejectOutcomeAssessmentProjectionParams struct {
	DecidedAt             *string     `json:"decided_at"`
	DecisionNote          interface{} `json:"decision_note"`
	WorkspaceID           string      `json:"workspace_id"`
	ID                    string      `json:"id"`
	ExpectedStateRevision int64       `json:"expected_state_revision"`
}

func (q *Queries) RejectOutcomeAssessmentProjection(ctx context.Context, arg RejectOutcomeAssessmentProjectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rejectOutcomeAssessmentProjection,
		arg.DecidedAt,
		arg.DecisionNote,
		arg.WorkspaceID,
		arg.ID,
		arg.ExpectedStateRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeOutcomeAssessmentProjection = `-- name: SupersedeOutcomeAssessmentProjection :execrows
UPDATE outcome_assessments
SET review_state='superseded',state_revision=state_revision+1
WHERE workspace_id=?1 AND id=?2 AND review_state='accepted'
`

type SupersedeOutcomeAssessmentProjectionParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) SupersedeOutcomeAssessmentProjection(ctx context.Context, arg SupersedeOutcomeAssessmentProjectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, supersedeOutcomeAssessmentProjection, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
