// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portable_knowledge.sql

package dbgen

import (
	"context"
)

const countPortableKnowledgeContradictionIdentity = `-- name: CountPortableKnowledgeContradictionIdentity :one
SELECT COUNT(*) FROM knowledge_contradictions
WHERE id = ?1
   OR (workspace_id = ?2
       AND left_revision_id = ?3
       AND right_revision_id = ?4)
`

type CountPortableKnowledgeContradictionIdentityParams struct {
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	LeftRevisionID  string `json:"left_revision_id"`
	RightRevisionID string `json:"right_revision_id"`
}

func (q *Queries) CountPortableKnowledgeContradictionIdentity(ctx context.Context, arg CountPortableKnowledgeContradictionIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPortableKnowledgeContradictionIdentity,
		arg.ID,
		arg.WorkspaceID,
		arg.LeftRevisionID,
		arg.RightRevisionID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPortableKnowledgeItemIdentity = `-- name: CountPortableKnowledgeItemIdentity :one
SELECT COUNT(*) FROM knowledge_items WHERE id = ?
`

func (q *Queries) CountPortableKnowledgeItemIdentity(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPortableKnowledgeItemIdentity, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPortableKnowledgeProjectState = `-- name: CountPortableKnowledgeProjectState :one
WITH target AS (
    SELECT CAST(?1 AS TEXT) AS workspace_id,
           CAST(?2 AS TEXT) AS project_id
)
SELECT
    (SELECT COUNT(*) FROM knowledge_items item, target
     WHERE item.workspace_id = target.workspace_id AND item.project_id = target.project_id) AS item_count,
    (SELECT COUNT(*) FROM knowledge_contradictions contradiction, target
     WHERE contradiction.workspace_id = target.workspace_id AND contradiction.project_id = target.project_id) AS contradiction_count,
    (SELECT COUNT(*) FROM knowledge_imports receipt, target
     WHERE receipt.workspace_id = target.workspace_id AND receipt.project_id = target.project_id) AS import_count
`

type CountPortableKnowledgeProjectStateParams struct {
	TargetWorkspaceID string `json:"target_workspace_id"`
	TargetProjectID   string `json:"target_project_id"`
}

type CountPortableKnowledgeProjectStateRow struct {
	ItemCount          int64 `json:"item_count"`
	ContradictionCount int64 `json:"contradiction_count"`
	ImportCount        int64 `json:"import_count"`
}

func (q *Queries) CountPortableKnowledgeProjectState(ctx context.Context, arg CountPortableKnowledgeProjectStateParams) (CountPortableKnowledgeProjectStateRow, error) {
	row := q.db.QueryRowContext(ctx, countPortableKnowledgeProjectState, arg.TargetWorkspaceID, arg.TargetProjectID)
	var i CountPortableKnowledgeProjectStateRow
	err := row.Scan(&i.ItemCount, &i.ContradictionCount, &i.ImportCount)
	return i, err
}

const countPortableKnowledgeRevisionIdentity = `-- name: CountPortableKnowledgeRevisionIdentity :one
SELECT COUNT(*) FROM knowledge_revisions WHERE id = ?
`

func (q *Queries) CountPortableKnowledgeRevisionIdentity(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPortableKnowledgeRevisionIdentity, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPortableKnowledgeAnchorIdentity = `-- name: GetPortableKnowledgeAnchorIdentity :one
SELECT workspace_id, project_id, created_at, created_by
FROM knowledge_task_scope_anchors WHERE task_id = ?
`

type GetPortableKnowledgeAnchorIdentityRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) GetPortableKnowledgeAnchorIdentity(ctx context.Context, taskID string) (GetPortableKnowledgeAnchorIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getPortableKnowledgeAnchorIdentity, taskID)
	var i GetPortableKnowledgeAnchorIdentityRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPortableKnowledgeImportReceipt = `-- name: GetPortableKnowledgeImportReceipt :one
SELECT id, bundle_id, workspace_id, project_id, content_sha256, rendering_sha256,
       manifest_json, markdown, idempotency_key, request_hash, imported_at,
       imported_by, imported_by_type, created_workspace, created_project,
       created_task_scope_anchors, completed_event_sequence
FROM knowledge_imports
WHERE workspace_id = ?1 AND project_id = ?2
`

type GetPortableKnowledgeImportReceiptParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) GetPortableKnowledgeImportReceipt(ctx context.Context, arg GetPortableKnowledgeImportReceiptParams) (KnowledgeImport, error) {
	row := q.db.QueryRowContext(ctx, getPortableKnowledgeImportReceipt, arg.WorkspaceID, arg.ProjectID)
	var i KnowledgeImport
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ContentSha256,
		&i.RenderingSha256,
		&i.ManifestJson,
		&i.Markdown,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ImportedAt,
		&i.ImportedBy,
		&i.ImportedByType,
		&i.CreatedWorkspace,
		&i.CreatedProject,
		&i.CreatedTaskScopeAnchors,
		&i.CompletedEventSequence,
	)
	return i, err
}

const getPortableTaskIdentity = `-- name: GetPortableTaskIdentity :one
SELECT workspace_id, project_id, created_at, created_by FROM tasks WHERE id = ?
`

type GetPortableTaskIdentityRow struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) GetPortableTaskIdentity(ctx context.Context, id string) (GetPortableTaskIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getPortableTaskIdentity, id)
	var i GetPortableTaskIdentityRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertPortableKnowledgeAnchor = `-- name: InsertPortableKnowledgeAnchor :exec
INSERT INTO knowledge_task_scope_anchors(task_id, workspace_id, project_id, created_at, created_by)
VALUES(?1, ?2, ?3, ?4, ?5)
`

type InsertPortableKnowledgeAnchorParams struct {
	TaskID      string `json:"task_id"`
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) InsertPortableKnowledgeAnchor(ctx context.Context, arg InsertPortableKnowledgeAnchorParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableKnowledgeAnchor,
		arg.TaskID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertPortableKnowledgeContradiction = `-- name: InsertPortableKnowledgeContradiction :exec
INSERT INTO knowledge_contradictions(
    id, workspace_id, project_id, left_revision_id, right_revision_id,
    status, state_revision, report_note, reported_at, reported_by,
    reported_by_type, detected_event_sequence,
    confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
    dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
    resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
    resolution_event_sequence, resolution_cause_event_sequence
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8, ?9,
    ?10, ?11, ?12,
    ?13, ?14, ?15,
    ?16, ?17,
    ?18, ?19, ?20,
    ?21, ?22,
    ?23, ?24, ?25,
    ?26, ?27,
    ?28, ?29
)
`

type InsertPortableKnowledgeContradictionParams struct {
	ID                           string  `json:"id"`
	WorkspaceID                  string  `json:"workspace_id"`
	ProjectID                    string  `json:"project_id"`
	LeftRevisionID               string  `json:"left_revision_id"`
	RightRevisionID              string  `json:"right_revision_id"`
	Status                       string  `json:"status"`
	StateRevision                int64   `json:"state_revision"`
	ReportNote                   string  `json:"report_note"`
	ReportedAt                   string  `json:"reported_at"`
	ReportedBy                   string  `json:"reported_by"`
	ReportedByType               string  `json:"reported_by_type"`
	DetectedEventSequence        int64   `json:"detected_event_sequence"`
	ConfirmedAt                  *string `json:"confirmed_at"`
	ConfirmedBy                  *string `json:"confirmed_by"`
	ConfirmedByType              *string `json:"confirmed_by_type"`
	ConfirmNote                  *string `json:"confirm_note"`
	ConfirmEventSequence         *int64  `json:"confirm_event_sequence"`
	DismissedAt                  *string `json:"dismissed_at"`
	DismissedBy                  *string `json:"dismissed_by"`
	DismissedByType              *string `json:"dismissed_by_type"`
	DismissNote                  *string `json:"dismiss_note"`
	DismissEventSequence         *int64  `json:"dismiss_event_sequence"`
	ResolutionReason             *string `json:"resolution_reason"`
	ResolvedAt                   *string `json:"resolved_at"`
	ResolvedBy                   *string `json:"resolved_by"`
	ResolvedByType               *string `json:"resolved_by_type"`
	ResolutionNote               *string `json:"resolution_note"`
	ResolutionEventSequence      *int64  `json:"resolution_event_sequence"`
	ResolutionCauseEventSequence *int64  `json:"resolution_cause_event_sequence"`
}

func (q *Queries) InsertPortableKnowledgeContradiction(ctx context.Context, arg InsertPortableKnowledgeContradictionParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableKnowledgeContradiction,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.LeftRevisionID,
		arg.RightRevisionID,
		arg.Status,
		arg.StateRevision,
		arg.ReportNote,
		arg.ReportedAt,
		arg.ReportedBy,
		arg.ReportedByType,
		arg.DetectedEventSequence,
		arg.ConfirmedAt,
		arg.ConfirmedBy,
		arg.ConfirmedByType,
		arg.ConfirmNote,
		arg.ConfirmEventSequence,
		arg.DismissedAt,
		arg.DismissedBy,
		arg.DismissedByType,
		arg.DismissNote,
		arg.DismissEventSequence,
		arg.ResolutionReason,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.ResolvedByType,
		arg.ResolutionNote,
		arg.ResolutionEventSequence,
		arg.ResolutionCauseEventSequence,
	)
	return err
}

const insertPortableKnowledgeImportEntity = `-- name: InsertPortableKnowledgeImportEntity :exec
INSERT INTO knowledge_import_entities(import_id, entity_type, entity_id, event_sequence, imported_at)
VALUES(?1, ?2, ?3, ?4, ?5)
`

type InsertPortableKnowledgeImportEntityParams struct {
	ImportID      string `json:"import_id"`
	EntityType    string `json:"entity_type"`
	EntityID      string `json:"entity_id"`
	EventSequence *int64 `json:"event_sequence"`
	ImportedAt    string `json:"imported_at"`
}

func (q *Queries) InsertPortableKnowledgeImportEntity(ctx context.Context, arg InsertPortableKnowledgeImportEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableKnowledgeImportEntity,
		arg.ImportID,
		arg.EntityType,
		arg.EntityID,
		arg.EventSequence,
		arg.ImportedAt,
	)
	return err
}

const insertPortableKnowledgeImportReceipt = `-- name: InsertPortableKnowledgeImportReceipt :exec
INSERT INTO knowledge_imports(
    id, bundle_id, workspace_id, project_id, content_sha256, rendering_sha256,
    manifest_json, markdown, idempotency_key, request_hash, imported_at,
    imported_by, imported_by_type, created_workspace, created_project,
    created_task_scope_anchors, completed_event_sequence
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15,
    ?16, ?17
)
`

type InsertPortableKnowledgeImportReceiptParams struct {
	ID                      string `json:"id"`
	BundleID                string `json:"bundle_id"`
	WorkspaceID             string `json:"workspace_id"`
	ProjectID               string `json:"project_id"`
	ContentSha256           string `json:"content_sha256"`
	RenderingSha256         string `json:"rendering_sha256"`
	ManifestJson            []byte `json:"manifest_json"`
	Markdown                []byte `json:"markdown"`
	IdempotencyKey          string `json:"idempotency_key"`
	RequestHash             string `json:"request_hash"`
	ImportedAt              string `json:"imported_at"`
	ImportedBy              string `json:"imported_by"`
	ImportedByType          string `json:"imported_by_type"`
	CreatedWorkspace        int64  `json:"created_workspace"`
	CreatedProject          int64  `json:"created_project"`
	CreatedTaskScopeAnchors int64  `json:"created_task_scope_anchors"`
	CompletedEventSequence  int64  `json:"completed_event_sequence"`
}

func (q *Queries) InsertPortableKnowledgeImportReceipt(ctx context.Context, arg InsertPortableKnowledgeImportReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableKnowledgeImportReceipt,
		arg.ID,
		arg.BundleID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ContentSha256,
		arg.RenderingSha256,
		arg.ManifestJson,
		arg.Markdown,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ImportedAt,
		arg.ImportedBy,
		arg.ImportedByType,
		arg.CreatedWorkspace,
		arg.CreatedProject,
		arg.CreatedTaskScopeAnchors,
		arg.CompletedEventSequence,
	)
	return err
}

const insertPortableKnowledgeRevision = `-- name: InsertPortableKnowledgeRevision :exec
INSERT INTO knowledge_revisions(
    id, item_id, revision_number, state_revision, title, body, content_hash,
    review_status, currency_status, confidence, verification_status,
    freshness_policy, fresh_until, supersedes_revision_id,
    proposed_at, proposed_by, proposed_by_type,
    accepted_at, accepted_by, accepted_by_type,
    rejected_at, rejected_by, rejected_by_type,
    stale_at, stale_by, stale_by_type, decision_note, stale_reason
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16,
    ?17, ?18, ?19,
    ?20, ?21, ?22,
    ?23, ?24, ?25,
    ?26, ?27, ?28
)
`

type InsertPortableKnowledgeRevisionParams struct {
	ID                   string  `json:"id"`
	ItemID               string  `json:"item_id"`
	RevisionNumber       int64   `json:"revision_number"`
	StateRevision        int64   `json:"state_revision"`
	Title                string  `json:"title"`
	Body                 string  `json:"body"`
	ContentHash          string  `json:"content_hash"`
	ReviewStatus         string  `json:"review_status"`
	CurrencyStatus       string  `json:"currency_status"`
	Confidence           string  `json:"confidence"`
	VerificationStatus   string  `json:"verification_status"`
	FreshnessPolicy      string  `json:"freshness_policy"`
	FreshUntil           *string `json:"fresh_until"`
	SupersedesRevisionID *string `json:"supersedes_revision_id"`
	ProposedAt           string  `json:"proposed_at"`
	ProposedBy           string  `json:"proposed_by"`
	ProposedByType       string  `json:"proposed_by_type"`
	AcceptedAt           *string `json:"accepted_at"`
	AcceptedBy           *string `json:"accepted_by"`
	AcceptedByType       *string `json:"accepted_by_type"`
	RejectedAt           *string `json:"rejected_at"`
	RejectedBy           *string `json:"rejected_by"`
	RejectedByType       *string `json:"rejected_by_type"`
	StaleAt              *string `json:"stale_at"`
	StaleBy              *string `json:"stale_by"`
	StaleByType          *string `json:"stale_by_type"`
	DecisionNote         *string `json:"decision_note"`
	StaleReason          *string `json:"stale_reason"`
}

func (q *Queries) InsertPortableKnowledgeRevision(ctx context.Context, arg InsertPortableKnowledgeRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableKnowledgeRevision,
		arg.ID,
		arg.ItemID,
		arg.RevisionNumber,
		arg.StateRevision,
		arg.Title,
		arg.Body,
		arg.ContentHash,
		arg.ReviewStatus,
		arg.CurrencyStatus,
		arg.Confidence,
		arg.VerificationStatus,
		arg.FreshnessPolicy,
		arg.FreshUntil,
		arg.SupersedesRevisionID,
		arg.ProposedAt,
		arg.ProposedBy,
		arg.ProposedByType,
		arg.AcceptedAt,
		arg.AcceptedBy,
		arg.AcceptedByType,
		arg.RejectedAt,
		arg.RejectedBy,
		arg.RejectedByType,
		arg.StaleAt,
		arg.StaleBy,
		arg.StaleByType,
		arg.DecisionNote,
		arg.StaleReason,
	)
	return err
}

const insertPortableProject = `-- name: InsertPortableProject :exec
INSERT INTO projects(id, workspace_id, name, revision, created_at, updated_at, created_by, updated_by)
VALUES(?1, ?2, ?3, ?4,
       ?5, ?6, ?7, ?8)
`

type InsertPortableProjectParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Revision    int64  `json:"revision"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	CreatedBy   string `json:"created_by"`
	UpdatedBy   string `json:"updated_by"`
}

func (q *Queries) InsertPortableProject(ctx context.Context, arg InsertPortableProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const insertPortableWorkspace = `-- name: InsertPortableWorkspace :exec
INSERT INTO workspaces(id, name, revision, created_at, updated_at, created_by, updated_by)
VALUES(?1, ?2, ?3, ?4,
       ?5, ?6, ?7)
`

type InsertPortableWorkspaceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Revision  int64  `json:"revision"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	CreatedBy string `json:"created_by"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) InsertPortableWorkspace(ctx context.Context, arg InsertPortableWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertPortableWorkspace,
		arg.ID,
		arg.Name,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const listPortableKnowledgeContradictions = `-- name: ListPortableKnowledgeContradictions :many
SELECT id, workspace_id, project_id, left_revision_id, right_revision_id,
       status, state_revision, report_note, reported_at, reported_by,
       reported_by_type, detected_event_sequence,
       confirmed_at, confirmed_by, confirmed_by_type, confirm_note, confirm_event_sequence,
       dismissed_at, dismissed_by, dismissed_by_type, dismiss_note, dismiss_event_sequence,
       resolution_reason, resolved_at, resolved_by, resolved_by_type, resolution_note,
       resolution_event_sequence, resolution_cause_event_sequence
FROM knowledge_contradictions
WHERE workspace_id = ?1 AND project_id = ?2
ORDER BY id
`

type ListPortableKnowledgeContradictionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) ListPortableKnowledgeContradictions(ctx context.Context, arg ListPortableKnowledgeContradictionsParams) ([]KnowledgeContradiction, error) {
	rows, err := q.db.QueryContext(ctx, listPortableKnowledgeContradictions, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeContradiction{}
	for rows.Next() {
		var i KnowledgeContradiction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.LeftRevisionID,
			&i.RightRevisionID,
			&i.Status,
			&i.StateRevision,
			&i.ReportNote,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.ReportedByType,
			&i.DetectedEventSequence,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.ConfirmedByType,
			&i.ConfirmNote,
			&i.ConfirmEventSequence,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.DismissedByType,
			&i.DismissNote,
			&i.DismissEventSequence,
			&i.ResolutionReason,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolvedByType,
			&i.ResolutionNote,
			&i.ResolutionEventSequence,
			&i.ResolutionCauseEventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortableKnowledgeItems = `-- name: ListPortableKnowledgeItems :many
SELECT ki.id, ki.workspace_id, ki.project_id,
       COALESCE(binding.task_id, ki.task_scope_id, '') AS task_scope_id,
       ki.type, ki.created_at, ki.created_by, ki.created_by_type
FROM knowledge_items ki
LEFT JOIN knowledge_item_task_scopes binding ON binding.item_id = ki.id
WHERE ki.workspace_id = ?1 AND ki.project_id = ?2
ORDER BY ki.id
`

type ListPortableKnowledgeItemsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

type ListPortableKnowledgeItemsRow struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	ProjectID     string `json:"project_id"`
	TaskScopeID   string `json:"task_scope_id"`
	Type          string `json:"type"`
	CreatedAt     string `json:"created_at"`
	CreatedBy     string `json:"created_by"`
	CreatedByType string `json:"created_by_type"`
}

func (q *Queries) ListPortableKnowledgeItems(ctx context.Context, arg ListPortableKnowledgeItemsParams) ([]ListPortableKnowledgeItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPortableKnowledgeItems, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortableKnowledgeItemsRow{}
	for rows.Next() {
		var i ListPortableKnowledgeItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TaskScopeID,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortableKnowledgeRevisionIDsForItem = `-- name: ListPortableKnowledgeRevisionIDsForItem :many
SELECT id FROM knowledge_revisions WHERE item_id = ? ORDER BY revision_number, id
`

func (q *Queries) ListPortableKnowledgeRevisionIDsForItem(ctx context.Context, itemID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPortableKnowledgeRevisionIDsForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortableKnowledgeTargetAnchors = `-- name: ListPortableKnowledgeTargetAnchors :many
SELECT task_id, workspace_id, project_id, created_at, created_by
FROM knowledge_task_scope_anchors
WHERE workspace_id = ?1 AND project_id = ?2
ORDER BY task_id
`

type ListPortableKnowledgeTargetAnchorsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) ListPortableKnowledgeTargetAnchors(ctx context.Context, arg ListPortableKnowledgeTargetAnchorsParams) ([]KnowledgeTaskScopeAnchor, error) {
	rows, err := q.db.QueryContext(ctx, listPortableKnowledgeTargetAnchors, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeTaskScopeAnchor{}
	for rows.Next() {
		var i KnowledgeTaskScopeAnchor
		if err := rows.Scan(
			&i.TaskID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortableKnowledgeTaskScopeAnchors = `-- name: ListPortableKnowledgeTaskScopeAnchors :many
SELECT DISTINCT a.task_id, a.workspace_id, a.project_id, a.created_at, a.created_by
FROM knowledge_task_scope_anchors a
JOIN knowledge_item_task_scopes binding ON binding.task_id = a.task_id
JOIN knowledge_items ki ON ki.id = binding.item_id
WHERE ki.workspace_id = ?1 AND ki.project_id = ?2
ORDER BY a.task_id
`

type ListPortableKnowledgeTaskScopeAnchorsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

func (q *Queries) ListPortableKnowledgeTaskScopeAnchors(ctx context.Context, arg ListPortableKnowledgeTaskScopeAnchorsParams) ([]KnowledgeTaskScopeAnchor, error) {
	rows, err := q.db.QueryContext(ctx, listPortableKnowledgeTaskScopeAnchors, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeTaskScopeAnchor{}
	for rows.Next() {
		var i KnowledgeTaskScopeAnchor
		if err := rows.Scan(
			&i.TaskID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portableKnowledgeEventHighWater = `-- name: PortableKnowledgeEventHighWater :one
SELECT CAST(COALESCE(MAX(sequence), 0) AS INTEGER) FROM events
`

func (q *Queries) PortableKnowledgeEventHighWater(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, portableKnowledgeEventHighWater)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const portableKnowledgeSnapshotPreflight = `-- name: PortableKnowledgeSnapshotPreflight :one
SELECT
    (SELECT COUNT(*) FROM knowledge_items item
     WHERE item.workspace_id = ?1 AND item.project_id = ?2) AS item_count,
    (SELECT COUNT(*) FROM knowledge_revisions revision
     JOIN knowledge_items item ON item.id = revision.item_id
     WHERE item.workspace_id = ?1 AND item.project_id = ?2) AS revision_count,
    (SELECT COUNT(*) FROM knowledge_contradictions contradiction
     WHERE contradiction.workspace_id = ?1 AND contradiction.project_id = ?2) AS contradiction_count,
    COALESCE((SELECT SUM(
        length(CAST(revision.title AS BLOB)) + length(CAST(revision.body AS BLOB)) +
        length(CAST(COALESCE(revision.decision_note, '') AS BLOB)) +
        length(CAST(COALESCE(revision.stale_reason, '') AS BLOB)) + 1
    ) FROM knowledge_revisions revision
      JOIN knowledge_items item ON item.id = revision.item_id
      WHERE item.workspace_id = ?1 AND item.project_id = ?2), 0) +
    COALESCE((SELECT SUM(
        length(CAST(source.source_type AS BLOB)) + length(CAST(source.source_id AS BLOB)) +
        length(CAST(source.role AS BLOB)) + 1
    ) FROM knowledge_sources source
      JOIN knowledge_revisions revision ON revision.id = source.revision_id
      JOIN knowledge_items item ON item.id = revision.item_id
      WHERE item.workspace_id = ?1 AND item.project_id = ?2), 0) +
    COALESCE((SELECT SUM(
        length(CAST(contradiction.report_note AS BLOB)) +
        length(CAST(COALESCE(contradiction.confirm_note, '') AS BLOB)) +
        length(CAST(COALESCE(contradiction.dismiss_note, '') AS BLOB)) +
        length(CAST(COALESCE(contradiction.resolution_note, '') AS BLOB)) + 1
    ) FROM knowledge_contradictions contradiction
      WHERE contradiction.workspace_id = ?1 AND contradiction.project_id = ?2), 0) +
    (SELECT COUNT(*) FROM knowledge_items item
     WHERE item.workspace_id = ?1 AND item.project_id = ?2) AS payload_byte_floor
`

type PortableKnowledgeSnapshotPreflightParams struct {
	WorkspaceID string `json:"workspace_id"`
	ProjectID   string `json:"project_id"`
}

type PortableKnowledgeSnapshotPreflightRow struct {
	ItemCount          int64 `json:"item_count"`
	RevisionCount      int64 `json:"revision_count"`
	ContradictionCount int64 `json:"contradiction_count"`
	PayloadByteFloor   int64 `json:"payload_byte_floor"`
}

func (q *Queries) PortableKnowledgeSnapshotPreflight(ctx context.Context, arg PortableKnowledgeSnapshotPreflightParams) (PortableKnowledgeSnapshotPreflightRow, error) {
	row := q.db.QueryRowContext(ctx, portableKnowledgeSnapshotPreflight, arg.WorkspaceID, arg.ProjectID)
	var i PortableKnowledgeSnapshotPreflightRow
	err := row.Scan(
		&i.ItemCount,
		&i.RevisionCount,
		&i.ContradictionCount,
		&i.PayloadByteFloor,
	)
	return i, err
}
