// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	DecideMeetingProposal(ctx context.Context, arg DecideMeetingProposalParams) error
	FindActiveMeetingForOverlap(ctx context.Context, overlapID string) (string, error)
	GetMeeting(ctx context.Context, arg GetMeetingParams) (Meeting, error)
	GetMeetingContribution(ctx context.Context, arg GetMeetingContributionParams) (MeetingContribution, error)
	GetMeetingProposal(ctx context.Context, meetingID string) (MeetingProposal, error)
	HasLiveTaskRun(ctx context.Context, taskID string) (bool, error)
	InsertMeeting(ctx context.Context, arg InsertMeetingParams) error
	InsertMeetingAction(ctx context.Context, arg InsertMeetingActionParams) error
	InsertMeetingAssignment(ctx context.Context, arg InsertMeetingAssignmentParams) error
	InsertMeetingContribution(ctx context.Context, arg InsertMeetingContributionParams) error
	InsertMeetingDependency(ctx context.Context, arg InsertMeetingDependencyParams) error
	InsertMeetingParticipant(ctx context.Context, arg InsertMeetingParticipantParams) error
	InsertMeetingProposal(ctx context.Context, arg InsertMeetingProposalParams) error
	InsertMeetingTaskRole(ctx context.Context, arg InsertMeetingTaskRoleParams) error
	InsertSplitTask(ctx context.Context, arg InsertSplitTaskParams) error
	ListMeetingActions(ctx context.Context, proposalID string) ([]MeetingAction, error)
	ListMeetingContributions(ctx context.Context, meetingID string) ([]MeetingContribution, error)
	ListMeetingParticipants(ctx context.Context, meetingID string) ([]MeetingParticipant, error)
	MarkMeetingActionApplied(ctx context.Context, arg MarkMeetingActionAppliedParams) error
	MaxEventSequence(ctx context.Context) (int64, error)
	MeetingDependencyExists(ctx context.Context, arg MeetingDependencyExistsParams) (bool, error)
	ReleaseMeetingClaim(ctx context.Context, arg ReleaseMeetingClaimParams) error
	ReleaseTaskAssignmentsForMeeting(ctx context.Context, arg ReleaseTaskAssignmentsForMeetingParams) error
	SetMeetingTaskAssigned(ctx context.Context, arg SetMeetingTaskAssignedParams) error
	SetMeetingTaskCancelled(ctx context.Context, arg SetMeetingTaskCancelledParams) error
	TouchMeetingTask(ctx context.Context, arg TouchMeetingTaskParams) error
	UpdateMeetingParticipantStatus(ctx context.Context, arg UpdateMeetingParticipantStatusParams) error
	UpdateMeetingState(ctx context.Context, arg UpdateMeetingStateParams) error
}

var _ Querier = (*Queries)(nil)
