// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	AcceptKnowledgeRevision(ctx context.Context, arg AcceptKnowledgeRevisionParams) (int64, error)
	AcknowledgeRunContextDelta(ctx context.Context, arg AcknowledgeRunContextDeltaParams) (int64, error)
	AdvanceRunContextDeltaScan(ctx context.Context, arg AdvanceRunContextDeltaScanParams) (int64, error)
	ConfirmKnowledgeContradiction(ctx context.Context, arg ConfirmKnowledgeContradictionParams) (int64, error)
	CountContextDependencies(ctx context.Context, taskID string) (int64, error)
	CountContextDependents(ctx context.Context, dependsOnTaskID string) (int64, error)
	CountContextParticipantThreads(ctx context.Context, arg CountContextParticipantThreadsParams) (int64, error)
	CountKnowledgeContradictionAuthorityChecks(ctx context.Context, arg CountKnowledgeContradictionAuthorityChecksParams) (int64, error)
	CountOpenKnowledgeContradictionsForRevision(ctx context.Context, arg CountOpenKnowledgeContradictionsForRevisionParams) (int64, error)
	CountPortableKnowledgeContradictionIdentity(ctx context.Context, arg CountPortableKnowledgeContradictionIdentityParams) (int64, error)
	CountPortableKnowledgeItemIdentity(ctx context.Context, id string) (int64, error)
	CountPortableKnowledgeProjectState(ctx context.Context, arg CountPortableKnowledgeProjectStateParams) (CountPortableKnowledgeProjectStateRow, error)
	CountPortableKnowledgeRevisionIdentity(ctx context.Context, id string) (int64, error)
	DecideMeetingProposal(ctx context.Context, arg DecideMeetingProposalParams) error
	DismissKnowledgeContradiction(ctx context.Context, arg DismissKnowledgeContradictionParams) (int64, error)
	FindAcceptedKnowledgeSuccessor(ctx context.Context, arg FindAcceptedKnowledgeSuccessorParams) (string, error)
	FindActiveMeetingForOverlap(ctx context.Context, overlapID string) (string, error)
	FindLiveKnowledgeSuccessor(ctx context.Context, supersedesRevisionID *string) (string, error)
	FindThreadParticipantByBinding(ctx context.Context, arg FindThreadParticipantByBindingParams) (ThreadParticipant, error)
	GetContextDeltaAcknowledgement(ctx context.Context, arg GetContextDeltaAcknowledgementParams) (ContextDeltaAcknowledgement, error)
	GetContextDeltaByID(ctx context.Context, id string) (ContextDelta, error)
	GetContextEventCursor(ctx context.Context) (int64, error)
	GetContextRepositoryFingerprint(ctx context.Context, arg GetContextRepositoryFingerprintParams) (string, error)
	GetContradictionReporterRunScope(ctx context.Context, runID string) (GetContradictionReporterRunScopeRow, error)
	GetCuratorAutoAcceptanceByKnowledge(ctx context.Context, arg GetCuratorAutoAcceptanceByKnowledgeParams) (CuratorAutoAcceptance, error)
	GetCuratorDerivationByKnowledge(ctx context.Context, arg GetCuratorDerivationByKnowledgeParams) (CuratorDerivation, error)
	GetCuratorMeetingProposalSource(ctx context.Context, proposalID string) (GetCuratorMeetingProposalSourceRow, error)
	GetEffectiveCuratorRule(ctx context.Context, arg GetEffectiveCuratorRuleParams) (CuratorRule, error)
	GetEligibleParticipantAssignment(ctx context.Context, arg GetEligibleParticipantAssignmentParams) (GetEligibleParticipantAssignmentRow, error)
	GetKnowledgeActorRunWorkspace(ctx context.Context, id string) (string, error)
	GetKnowledgeAuthorityCheckByKey(ctx context.Context, arg GetKnowledgeAuthorityCheckByKeyParams) (KnowledgeAuthorityCheck, error)
	GetKnowledgeContradiction(ctx context.Context, arg GetKnowledgeContradictionParams) (KnowledgeContradiction, error)
	GetKnowledgeContradictionAuthorityCheckByKey(ctx context.Context, arg GetKnowledgeContradictionAuthorityCheckByKeyParams) (KnowledgeContradictionAuthorityCheck, error)
	GetKnowledgeContradictionByPair(ctx context.Context, arg GetKnowledgeContradictionByPairParams) (KnowledgeContradiction, error)
	GetKnowledgeRevision(ctx context.Context, arg GetKnowledgeRevisionParams) (GetKnowledgeRevisionRow, error)
	GetKnowledgeSourceMeeting(ctx context.Context, id string) (GetKnowledgeSourceMeetingRow, error)
	GetKnowledgeSourceMeetingProposal(ctx context.Context, id string) (GetKnowledgeSourceMeetingProposalRow, error)
	GetKnowledgeSourceTask(ctx context.Context, id string) (GetKnowledgeSourceTaskRow, error)
	GetKnowledgeTaskScopeAnchor(ctx context.Context, taskID string) (KnowledgeTaskScopeAnchor, error)
	GetMeeting(ctx context.Context, arg GetMeetingParams) (Meeting, error)
	GetMeetingContribution(ctx context.Context, arg GetMeetingContributionParams) (MeetingContribution, error)
	GetMeetingProposal(ctx context.Context, meetingID string) (MeetingProposal, error)
	GetParticipantThreadState(ctx context.Context, arg GetParticipantThreadStateParams) (GetParticipantThreadStateRow, error)
	GetPortableKnowledgeAnchorIdentity(ctx context.Context, taskID string) (GetPortableKnowledgeAnchorIdentityRow, error)
	GetPortableKnowledgeImportReceipt(ctx context.Context, arg GetPortableKnowledgeImportReceiptParams) (KnowledgeImport, error)
	GetPortableTaskIdentity(ctx context.Context, id string) (GetPortableTaskIdentityRow, error)
	GetRunContextDeltaByID(ctx context.Context, arg GetRunContextDeltaByIDParams) (ContextDelta, error)
	GetRunContextDeltaState(ctx context.Context, runID string) (RunContextDeltaState, error)
	GetWorkspaceContextDeltaByID(ctx context.Context, arg GetWorkspaceContextDeltaByIDParams) (ContextDelta, error)
	GetWorkspaceContextPacket(ctx context.Context, arg GetWorkspaceContextPacketParams) (GetWorkspaceContextPacketRow, error)
	HasLiveTaskRun(ctx context.Context, taskID string) (bool, error)
	InsertContextDelta(ctx context.Context, arg InsertContextDeltaParams) error
	InsertContextDeltaAcknowledgement(ctx context.Context, arg InsertContextDeltaAcknowledgementParams) error
	InsertContextPacket(ctx context.Context, arg InsertContextPacketParams) error
	InsertCuratorAutoAcceptance(ctx context.Context, arg InsertCuratorAutoAcceptanceParams) error
	InsertCuratorDerivation(ctx context.Context, arg InsertCuratorDerivationParams) error
	InsertCuratorRule(ctx context.Context, arg InsertCuratorRuleParams) error
	InsertKnowledgeAuthorityCheck(ctx context.Context, arg InsertKnowledgeAuthorityCheckParams) error
	InsertKnowledgeContradiction(ctx context.Context, arg InsertKnowledgeContradictionParams) error
	InsertKnowledgeContradictionAuthorityCheck(ctx context.Context, arg InsertKnowledgeContradictionAuthorityCheckParams) error
	InsertKnowledgeItem(ctx context.Context, arg InsertKnowledgeItemParams) error
	InsertKnowledgeItemTaskScope(ctx context.Context, arg InsertKnowledgeItemTaskScopeParams) error
	InsertKnowledgeRevision(ctx context.Context, arg InsertKnowledgeRevisionParams) error
	InsertKnowledgeSource(ctx context.Context, arg InsertKnowledgeSourceParams) error
	InsertKnowledgeTaskScopeAnchor(ctx context.Context, arg InsertKnowledgeTaskScopeAnchorParams) error
	InsertMeeting(ctx context.Context, arg InsertMeetingParams) error
	InsertMeetingAction(ctx context.Context, arg InsertMeetingActionParams) error
	InsertMeetingAssignment(ctx context.Context, arg InsertMeetingAssignmentParams) error
	InsertMeetingContribution(ctx context.Context, arg InsertMeetingContributionParams) error
	InsertMeetingDependency(ctx context.Context, arg InsertMeetingDependencyParams) error
	InsertMeetingParticipant(ctx context.Context, arg InsertMeetingParticipantParams) error
	InsertMeetingProposal(ctx context.Context, arg InsertMeetingProposalParams) error
	InsertMeetingTaskRole(ctx context.Context, arg InsertMeetingTaskRoleParams) error
	InsertParticipantThread(ctx context.Context, arg InsertParticipantThreadParams) error
	InsertPortableKnowledgeAnchor(ctx context.Context, arg InsertPortableKnowledgeAnchorParams) error
	InsertPortableKnowledgeContradiction(ctx context.Context, arg InsertPortableKnowledgeContradictionParams) error
	InsertPortableKnowledgeImportEntity(ctx context.Context, arg InsertPortableKnowledgeImportEntityParams) error
	InsertPortableKnowledgeImportReceipt(ctx context.Context, arg InsertPortableKnowledgeImportReceiptParams) error
	InsertPortableKnowledgeRevision(ctx context.Context, arg InsertPortableKnowledgeRevisionParams) error
	InsertPortableProject(ctx context.Context, arg InsertPortableProjectParams) error
	InsertPortableWorkspace(ctx context.Context, arg InsertPortableWorkspaceParams) error
	InsertRunContextDeltaState(ctx context.Context, arg InsertRunContextDeltaStateParams) error
	InsertSplitTask(ctx context.Context, arg InsertSplitTaskParams) error
	InsertThreadParticipant(ctx context.Context, arg InsertThreadParticipantParams) error
	ListAllOpenKnowledgeContradictionsForRevision(ctx context.Context, arg ListAllOpenKnowledgeContradictionsForRevisionParams) ([]KnowledgeContradiction, error)
	ListAllRunContextDeltas(ctx context.Context, runID string) ([]ContextDelta, error)
	ListContextDependencies(ctx context.Context, taskID string) ([]ListContextDependenciesRow, error)
	ListContextDependents(ctx context.Context, arg ListContextDependentsParams) ([]ListContextDependentsRow, error)
	ListContextParticipantThreadIDs(ctx context.Context, arg ListContextParticipantThreadIDsParams) ([]string, error)
	ListCuratorEligibleRevisionIDs(ctx context.Context, arg ListCuratorEligibleRevisionIDsParams) ([]string, error)
	ListCuratorMeetingProposalCandidates(ctx context.Context, arg ListCuratorMeetingProposalCandidatesParams) ([]ListCuratorMeetingProposalCandidatesRow, error)
	ListCuratorQueueRevisionIDs(ctx context.Context, arg ListCuratorQueueRevisionIDsParams) ([]string, error)
	ListKnowledgeAuthorityChecks(ctx context.Context, arg ListKnowledgeAuthorityChecksParams) ([]KnowledgeAuthorityCheck, error)
	ListKnowledgeContradictionAuthorityChecks(ctx context.Context, arg ListKnowledgeContradictionAuthorityChecksParams) ([]KnowledgeContradictionAuthorityCheck, error)
	ListKnowledgeContradictionIDs(ctx context.Context, arg ListKnowledgeContradictionIDsParams) ([]string, error)
	ListKnowledgeRevisionIDs(ctx context.Context, arg ListKnowledgeRevisionIDsParams) ([]string, error)
	ListKnowledgeRevisionSources(ctx context.Context, revisionID string) ([]KnowledgeSource, error)
	ListMeetingActions(ctx context.Context, proposalID string) ([]MeetingAction, error)
	ListMeetingContributions(ctx context.Context, meetingID string) ([]MeetingContribution, error)
	ListMeetingParticipants(ctx context.Context, meetingID string) ([]MeetingParticipant, error)
	ListOpenKnowledgeContradictionsForRevision(ctx context.Context, arg ListOpenKnowledgeContradictionsForRevisionParams) ([]KnowledgeContradiction, error)
	ListPortableKnowledgeContradictions(ctx context.Context, arg ListPortableKnowledgeContradictionsParams) ([]KnowledgeContradiction, error)
	ListPortableKnowledgeItems(ctx context.Context, arg ListPortableKnowledgeItemsParams) ([]ListPortableKnowledgeItemsRow, error)
	ListPortableKnowledgeRevisionIDsForItem(ctx context.Context, itemID string) ([]string, error)
	ListPortableKnowledgeTargetAnchors(ctx context.Context, arg ListPortableKnowledgeTargetAnchorsParams) ([]KnowledgeTaskScopeAnchor, error)
	ListPortableKnowledgeTaskScopeAnchors(ctx context.Context, arg ListPortableKnowledgeTaskScopeAnchorsParams) ([]KnowledgeTaskScopeAnchor, error)
	ListRunContextDeltas(ctx context.Context, arg ListRunContextDeltasParams) ([]ContextDelta, error)
	ListThreadParticipants(ctx context.Context, threadID string) ([]ThreadParticipant, error)
	ListThreadParticipantsByAgent(ctx context.Context, arg ListThreadParticipantsByAgentParams) ([]ThreadParticipant, error)
	MarkKnowledgeRevisionStale(ctx context.Context, arg MarkKnowledgeRevisionStaleParams) (int64, error)
	MarkMeetingActionApplied(ctx context.Context, arg MarkMeetingActionAppliedParams) error
	MarkRunContextDeltaPending(ctx context.Context, arg MarkRunContextDeltaPendingParams) (int64, error)
	MarkRunContextRebaseRequired(ctx context.Context, arg MarkRunContextRebaseRequiredParams) (int64, error)
	MaxEventSequence(ctx context.Context) (int64, error)
	MaxKnowledgeRevisionNumber(ctx context.Context, itemID string) (int64, error)
	MeetingDependencyExists(ctx context.Context, arg MeetingDependencyExistsParams) (bool, error)
	PortableKnowledgeEventHighWater(ctx context.Context) (int64, error)
	PortableKnowledgeSnapshotPreflight(ctx context.Context, arg PortableKnowledgeSnapshotPreflightParams) (PortableKnowledgeSnapshotPreflightRow, error)
	RejectKnowledgeRevision(ctx context.Context, arg RejectKnowledgeRevisionParams) (int64, error)
	ReleaseMeetingClaim(ctx context.Context, arg ReleaseMeetingClaimParams) error
	ReleaseTaskAssignmentsForMeeting(ctx context.Context, arg ReleaseTaskAssignmentsForMeetingParams) error
	ResolveKnowledgeContradiction(ctx context.Context, arg ResolveKnowledgeContradictionParams) (int64, error)
	RunAuthorizedForMessage(ctx context.Context, arg RunAuthorizedForMessageParams) (int64, error)
	SetMeetingTaskAssigned(ctx context.Context, arg SetMeetingTaskAssignedParams) error
	SetMeetingTaskCancelled(ctx context.Context, arg SetMeetingTaskCancelledParams) error
	SupersedeKnowledgeRevision(ctx context.Context, arg SupersedeKnowledgeRevisionParams) (int64, error)
	TouchMeetingTask(ctx context.Context, arg TouchMeetingTaskParams) error
	UpdateMeetingParticipantStatus(ctx context.Context, arg UpdateMeetingParticipantStatusParams) error
	UpdateMeetingState(ctx context.Context, arg UpdateMeetingStateParams) error
}

var _ Querier = (*Queries)(nil)
